Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2020-12, with the labels that each got.

#76 Fix/disabled clusters in sc builder
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/sets.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/refresh.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/cmake/windows-studyparts.cmake
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/options/scenario-builder/scenario-builder.cpp
  src/ui/simulator/windows/options/scenario-builder/scenario-builder.h
Labels: PR: waiting for review, bug

#89 update yuni for ortools stable use and cxx 17 support
  .github/workflows/linux-system.yml
  src/cmake/dependencies/CMakeLists.txt
  src/ext/yuni/src/yuni/core/getopt/option.h
  src/tests/end-to-end/solver-call.cpp
Labels: bug

#88 add libsirius_solver.so copy also on linux
  src/cmake/utils.cmake
Labels: bug, linux

#90 Feature/mark version 8.0
  NEWS.txt
  docs/ref_guides/antares-general-reference-guide.docx
  docs/ref_guides/antares-general-reference-guide.pdf
  src/CMakeLists.txt
  src/changelog.mdown
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
Labels: PR: waiting for review

#91 update for new or-tools API to check solver availability
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
Labels: enhancement

#92 pytest version for simple-test
  src/tests/end-to-end/test_simple-test.py
Labels: question
