Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-04, with the labels that each got.

#211 Feature/remove license from UI
  src/internet/license.h
  src/ui/simulator/application/main/check-license-at-startup.hxx
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/events.simulation.cpp
  src/ui/simulator/application/main/help.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/cmake/messages.cmake
  src/ui/simulator/cmake/windows-startupwizard.cmake
  src/ui/simulator/windows/onLineConsent/on-line-consent.cpp
  src/ui/simulator/windows/onLineConsent/on-line-consent.h
  src/ui/simulator/windows/proxy/proxysetup.cpp
  src/ui/simulator/windows/proxy/proxysetup.h
  src/ui/simulator/windows/startupwizard.cpp
Labels: GUI, size/XL, work in progress

#216 Use xdg-open instead of outdated gnome-open
  src/ui/simulator/application/main/help.cpp
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/application/main/refresh.cpp
  src/ui/simulator/windows/analyzer/analyzer.cpp
Labels: GUI, linux, size/S

#217 Remove license - (1) : removing 2 important files and consequences
  src/internet/CMakeLists.txt
  src/internet/hello_web.cpp
  src/internet/license.h
  src/internet/licensetimer.cpp
  src/internet/licensetimer.h
  src/internet/limits.cpp
  src/internet/limits.h
  src/libs/antares/sys/policy.cpp
  src/solver/main.cpp
  src/ui/simulator/application/application.cpp
  src/ui/simulator/application/main/check-license-at-startup.hxx
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/windows/version.cpp
  src/ui/simulator/windows/version.h
Labels: PR: waiting for review, size/XL

#231 Limit NODU with unit number
  src/solver/variable/state.cpp
Labels: size/XS

#232 Fix handling of float nominal capacity in GUI
  src/ui/simulator/windows/inspector/frame.cpp
Labels: size/XS

#235 Remove dockerHub actions
  .github/workflows/dockerHub.yml
  .github/workflows/dockerHubPublish.yml
Labels: size/L

#233 Ratio for congestionProbability must use mc years weight
  src/solver/variable/economy/links/congestionProbability.h
Labels: PR: waiting for review, bug, size/S

#196 Format .hpp source files
  src/ext/yuni/src/yuni/core/process/program/unix.inc.hpp
  src/ext/yuni/src/yuni/core/process/program/windows.inc.hpp
  src/ext/yuni/src/yuni/core/slist/iterator.inc.hpp
  src/ext/yuni/src/yuni/core/string/iterator.inc.hpp
  src/ext/yuni/src/yuni/io/directory/info/iterator.inc.hpp
  src/ext/yuni/src/yuni/messaging/transport/rest/request.inc.hpp
  src/ext/yuni/src/yuni/messaging/worker.inc.hpp
  src/format-code.sh
  src/libs/antares/Enum.hpp
  src/libs/antares/exception/AssertionError.hpp
  src/libs/antares/exception/UnfeasibleProblemError.hpp
  src/libs/antares/stdcxx/demangle.hpp
  src/libs/antares/study/OrtoolsSolver.hpp
  src/libs/antares/study/UnfeasibleProblemBehavior.hpp
  src/solver/variable/commons/miscGenMinusRowPSP.h
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/windows/version.cpp
Labels: PR: waiting for review, enhancement, size/XXL

#238 Remove unused MatriceContraintes from struct PROBLEME_HEBDO
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: cleaning, size/M

#242 Simplify hydro remix condition
  src/solver/simulation/common-hydro-levels.cpp
Labels: cleaning, size/XS
