Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-08, with the labels that each got.

#321 UI : renewables/.../list.ini : remove parasitic warning
  src/libs/antares/study/parts/renewable/cluster_list.cpp
Labels: size/XS

#318 Fix crash related to "delete all clusters", thermal & renewable
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/parts/renewable/container.cpp
  src/libs/antares/study/parts/renewable/container.h
  src/libs/antares/study/parts/thermal/container.cpp
  src/libs/antares/study/parts/thermal/container.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/ui-runtimeinfos.cpp
  src/solver/main.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/solver.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/area.inc.hxx
  src/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/state.cpp
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: size/L

#324 UI - factor visible cluster items
  src/ui/simulator/cmake/components-htmllistbox.cmake
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/cluster-item.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/cluster-item.h
  src/ui/simulator/toolbox/components/htmllistbox/item/renewable-cluster-item.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/renewable-cluster-item.h
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster-item.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster-item.h
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster.h
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.h
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.h
Labels: size/XL, cleaning

#317 Use operator() on Parameter::renewableGeneration
  src/libs/antares/study/parameters.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/simulation/panel.cpp
Labels: size/S

#327 Include RES generation in hydro management
  src/solver/hydro/management/management.cpp
Labels: size/S

#331 Renewable production returns zero if cluster is disabled
  src/libs/antares/study/parts/renewable/cluster.cpp
Labels: size/XS

#332 Linux : allow ui to find solver when packaged in TGZ archive
  src/libs/antares/solver.cpp
Labels: linux, size/XS, GUI

#319 UI : factor thermal/renewable area summary classes
  src/ui/simulator/cmake/components-htmllistbox.cmake
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/datagrid/renderer/area/common.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/common.areasummary.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable.areasummary.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermal.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermal.areasummary.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/cluster-item.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/cluster-item.h
  src/ui/simulator/toolbox/components/htmllistbox/item/renewable-cluster-item.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/renewable-cluster-item.h
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster-item.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster-item.h
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/thermal-cluster.h
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.h
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.h
Labels: size/XXL, GUI

#329 When excluding output variables, reset it_info
  src/libs/antares/study/variable-print-info.cpp
Labels: size/XS

#330 UI - factor classes for sorting clusters by certain order
  src/ui/simulator/cmake/components-htmllistbox.cmake
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/htmllistbox/datasource/cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/cluster-order.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster-order.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster-order.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
Labels: size/XXL, GUI, cleaning

#346 UI - playlist and var selection : make the 2 panes extensible
  src/ui/simulator/windows/options/playlist/playlist.cpp
  src/ui/simulator/windows/options/select-output/select-output.cpp
Labels: size/XS

#347 Fix wxWidgets error message when opening "Advanced parameters"
  src/ui/simulator/windows/options/advanced/advanced.cpp
Labels: size/XS

#337 Fix intermodal condition #336
  src/libs/antares/study/parameters.cpp
  src/solver/simulation/timeseries-numbers.cpp
Labels: size/XS

#339 Remove all renewable clusters if renewableModelling==rgAggregated
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
Labels: size/M

#348 Remove unused onUpdAggregateListDueToGroupChange functions
  src/ui/simulator/windows/renewables/cluster.cpp
  src/ui/simulator/windows/renewables/cluster.h
  src/ui/simulator/windows/thermal/cluster.cpp
  src/ui/simulator/windows/thermal/cluster.h
Labels: size/M, cleaning

#340 UI - clusters time series : extracting common code from cluster TS classes
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
Labels: size/L, GUI, cleaning

#352 UI : adding new icons for renewable clusters
  src/ui/simulator/resources/images/16x16/renewable.png
  src/ui/simulator/resources/images/16x16/renewable_add.png
  src/ui/simulator/resources/images/16x16/renewable_remove.png
  src/ui/simulator/toolbox/components/htmllistbox/item/renewable-cluster-item.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
Labels: enhancement, size/XS, GUI

#350 Remove unused scenario-builder.h
  src/ui/simulator/cmake/windows-studyparts.cmake
  src/ui/simulator/windows/options/scenario-builder.h
Labels: size/M, cleaning

#354 Renewable clusters for RES as default on study creation
  src/libs/antares/study/study.cpp
  src/ui/simulator/windows/options/advanced/advanced.cpp
Labels: enhancement, PR: waiting for review, size/S, GUI

#353 GUI : Refactor property change
  src/libs/antares/study/parts/common/cluster.h
  src/ui/simulator/cmake/windows-inspector.cmake
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.cluster.update.cpp
  src/ui/simulator/windows/inspector/property.cluster.update.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XL

#349 UI : factor sc builder
  src/ui/simulator/application/main/build/scenario-builder.cpp
Labels: size/M, GUI

#365 UI: Fix cluster default
  src/ui/simulator/windows/options/advanced/advanced.cpp
Labels: PR: waiting for review, size/S, GUI

#360 UI - keep selection on cluster when group changes
  src/ui/simulator/toolbox/components/htmllistbox/component.cpp
  src/ui/simulator/toolbox/components/htmllistbox/component.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/cluster-order.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster-order.h
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster-order.h
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.h
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.h
Labels: PR: ready for merge, size/L, GUI

#363 UI - input menu behaviour when changing renewable modelling
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
Labels: PR: waiting for correction, size/M, GUI
