Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-12, with the labels that each got.

#475 Display commit-id in GUI and CLI
  src/CMakeLists.txt
  src/config.h.cmake
  src/solver/misc/options.cpp
  src/ui/simulator/windows/about/aboutbox.cpp
Labels: size/S

#449 NTC: use TS numbers in optimization problem
  src/solver/simulation/adequacy-draft.cpp
  src/solver/simulation/sim_calcul_adequation.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/simulation.h
Labels: PR: waiting for review, size/M

#467 NTC : refactor read of scenariobuilder.dat before introducing NTC
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/sets.cpp
  src/solver/simulation/apply-scenario.cpp
Labels: PR: waiting for correction, size/L

#482 fix thermal TS error message includes area name
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/libs/antares/study/parts/thermal/prepro.h
Labels: size/S

#481 [UI] Search solver in the build directory first
  src/libs/antares/solver.cpp
Labels: linux, size/XS, GUI

#483 Fix when loading links NTC time series from files
  src/libs/antares/study/area/links.cpp
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
Labels: PR: waiting for review, size/XS

#491 Fix hydro level discontinuities
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/XS

#489 Fix study updater for v8.1
  src/libs/antares/study/area/list.cpp
Labels: PR: waiting for review, size/XS

#486 Study cleaner: keep data related to links
  src/libs/antares/study/cleaner/cleaner-v20.cpp
Labels: size/S

#488 Study cleaner: keep files & folders related to renewable clusters
  src/libs/antares/study/cleaner/cleaner-v20.cpp
Labels: size/M

#484 NTC - scenario builder - save scenariobuilder.dat
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/rules.hxx
  src/libs/antares/study/scenario-builder/sets.cpp
  src/libs/antares/study/scenario-builder/sets.h
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
Labels: PR: waiting for review, size/XL

#494 Feature/ntc sc builder read data
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/rules.hxx
  src/libs/antares/study/scenario-builder/sets.cpp
  src/libs/antares/study/scenario-builder/sets.h
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
Labels: size/XL
