Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-07, with the labels that each got.

#272 Add gen. modulation interpretation for renewable TS
  src/libs/antares/study/parts/renewable/cluster.cpp
  src/libs/antares/study/parts/renewable/cluster.h
Labels: size/XS

#275 Add details-res output files
  src/solver/cmake/variable.cmake
  src/solver/variable/adequacy/all.h
  src/solver/variable/categories.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/info.h
  src/solver/variable/surveyresults/reportbuilder.hxx
  src/solver/variable/surveyresults/surveyresults.h
Labels: size/XL

#284 UI : take unit count and nominal capacity into account in RES clusters main panel
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable-modulation.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable.areasummary.cpp
  src/ui/simulator/toolbox/components/htmllistbox/item/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
Labels: size/M

#287 De-duplicate clusterRename
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/common/cluster.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/L

#285 Fix build with g++ 11.1.0
  src/libs/antares/study/area/links.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/simulation/solver.utils.h
Labels: size/XS

#292 UI : rename ENR x -> Other RES x
  src/ui/simulator/windows/inspector/accumulator.hxx
Labels: size/XS

#293 Disable renewable modulation
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable-modulation.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable-modulation.h
  src/ui/simulator/windows/renewables/cluster.cpp
Labels: size/L

#294 UI Allow change of units number
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XS

#289 Generate wind and solar TS only when rgModelling==rgAggregated
  src/solver/simulation/solver.data.cpp
Labels: size/XS

#295 UI : Add installed capacity for renewable clusters
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/S

#299 UI : allowing to delete all renewable clusters of an area
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.h
Labels: PR: waiting for review

#278 Add thermal groups other 2, 3, 4
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/solver/variable/economy/dispatchableGeneration.h
  src/ui/simulator/windows/inspector/accumulator.hxx
Labels: size/M

#309 Add renewable detail to output
  src/ui/simulator/windows/output/output.cpp
  src/ui/simulator/windows/output/output.h
  src/ui/simulator/windows/output/panel/area-link.cpp
Labels: GUI

#312 UI : hide or show tabs depending on renewable modeling parameter value
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/components/notebook/notebook.cpp
  src/ui/simulator/toolbox/components/notebook/notebook.h
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/advanced/advanced.h
  src/ui/simulator/windows/simulation/panel.cpp
  src/ui/simulator/windows/simulation/panel.h
Labels: size/L
