Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-02, with the labels that each got.

#102 Antares Test : PyTest and CTest for study output compare
  .github/workflows/releasesLinux.yml
  .github/workflows/releasesWindows.yml
  INSTALL.md
  src/tests/CMakeLists.txt
  src/tests/examples/code_generator.py
  src/tests/examples/conftest.py
  src/tests/examples/output_compare_test.py
  src/tests/examples/study.py
Labels: PR: ready for merge, bug, enhancement

#115 [Re]move dead code related to PNE
  src/solver/cmake/solver.cmake
  src/solver/hydro/daily/h2o_j_resoudre_le_probleme_lineaire.c
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.c
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.c
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_pne.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: PR: waiting for review

#139 Antares Test : unfeasible problem pytest
  src/tests/CMakeLists.txt
  src/tests/examples/output_compare_test.py
  src/tests/examples/specific_test.py
Labels: enhancement

#146 Features/check output by cols
  .github/workflows/linux-system.yml
  .github/workflows/windows-vcpkg.yml
  src/tests/examples/output_compare_test.py
Labels: enhancement

#148 disable output compare on linux for unfeasible problem tests
  src/tests/examples/output_compare_test.py
Labels: bug

#151 Downloading tests and examples
  src/distrib/CMakeLists.txt.in
  src/tests/CMakeLists.txt
Labels: PR: waiting for review, bug

#153 Remove COUT_TRANSPORT #define'd constant
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
Labels: PR: waiting for review

#145 Fix warnings
  src/internet/CMakeLists.txt
  src/internet/getstarttime.cpp
  src/internet/getstarttime.h
  src/internet/hello_web.cpp
  src/internet/licensetimer.cpp
  src/libs/antares/array/matrix.h
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/action/context.cpp
  src/libs/antares/study/action/handler/antares-study/area/allocation-hydro-post.cpp
  src/libs/antares/study/action/handler/antares-study/thermal-cluster/root-node.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/constraint/constraint.cpp
  src/libs/antares/study/estimate.memory-footprint.cpp
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/allocation.cpp
  src/libs/antares/study/parts/hydro/allocation.h
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/ui-runtimeinfos.cpp
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/grid.hxx
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/solver.hxx
  src/solver/variable/area.hxx
  src/solver/variable/commons/links/links.cpp.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/setofareas.hxx
  src/solver/variable/surveyresults/data.h
  src/solver/variable/surveyresults/reportbuilder.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
  src/solver/variable/surveyresults/surveyresults.h
  src/tests/src/libs/antares/array/matrix-bypass-load.h
  src/tests/src/libs/antares/array/tests-matrix-save.cpp
  src/tests/src/libs/antares/array/tests-matrix-save.h
  src/ui/common/component/spotlight/iitem.cpp
  src/ui/common/dispatcher/gui.cpp
  src/ui/simulator/application/main/constraintsbuilder.cpp
  src/ui/simulator/toolbox/components/map/control.cpp
  src/ui/simulator/toolbox/components/map/nodes/connection.cpp
  src/ui/simulator/toolbox/components/map/settings.h
  src/ui/simulator/toolbox/components/notebook/mapnotebook.cpp
  src/ui/simulator/toolbox/components/notebook/notebook.cpp
  src/ui/simulator/windows/message.cpp
Labels: PR: ready for merge, enhancement

#142 hydro reservoir levels : need for a new advanced parameter
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/cmake/hydro.cmake
  src/solver/hydro/daily2/h2o2_j_apply_costs.cpp
  src/solver/hydro/daily2/h2o2_j_construire_les_contraintes.cpp
  src/solver/hydro/daily2/h2o2_j_construire_les_variables.cpp
  src/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/daily2/h2o2_j_fonctions.h
  src/solver/hydro/daily2/h2o2_j_free.cpp
  src/solver/hydro/daily2/h2o2_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily2/h2o2_j_initialiser_les_second_membre.cpp
  src/solver/hydro/daily2/h2o2_j_instanciation.cpp
  src/solver/hydro/daily2/h2o2_j_optim_costs.cpp
  src/solver/hydro/daily2/h2o2_j_optimiser_un_mois.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/management/daily.cpp
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/advanced/advanced.h
Labels: enhancement

#157 Skip connection to license server 2
  src/ui/simulator/windows/proxy/proxysetup.cpp
  src/ui/simulator/windows/proxy/proxysetup.h
Labels: PR: waiting for review, enhancement

#163 Add option BUILD_SWAP
  src/CMakeLists.txt
  src/libs/antares/CMakeLists.txt
  src/solver/CMakeLists.txt
  src/solver/cmake/hydro.cmake
  src/solver/cmake/main.cmake
  src/solver/cmake/randomness.cmake
  src/solver/cmake/simulation.cmake
  src/solver/cmake/solver.cmake
  src/solver/cmake/ts-generator.cmake
  src/solver/cmake/variable.cmake
  src/tools/CMakeLists.txt
Labels: enhancement

#168 Add export on CMakeLists.txt
  src/solver/CMakeLists.txt
  src/tools/batchrun/CMakeLists.txt
  src/tools/cleaner/CMakeLists.txt
  src/tools/config/CMakeLists.txt
  src/tools/finder/CMakeLists.txt
  src/tools/updater/CMakeLists.txt
  src/tools/vacuum/CMakeLists.txt
  src/tools/yby-aggregator/CMakeLists.txt
  src/ui/simulator/CMakeLists.txt
Labels: enhancement

#176 fix : remove tests resources before NSIS installer creation
  .github/workflows/releasesWindows.yml
  .github/workflows/windows-vcpkg.yml
Labels: bug
