Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-11, with the labels that each got.

#419 Tests area's optimization.ini generation
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/filter.cpp
  src/libs/antares/study/filter.h
  src/libs/antares/study/filter.hxx
  src/libs/antares/study/links/property-links-helper.h
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/area/CMakeLists.txt
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/geographic-trimming-grid.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: work in progress, size/XL

#434 Remove Chocolatey's cpack
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#435 Fix build on CentOS 7
  src/tests/src/libs/antares/study/area/CMakeLists.txt
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/M

#437 CentOS 7: upgrade devtoolset-7 -> devtoolset-9
  .github/workflows/centos7-release.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7-system.yml
  docker/centos7-basic-requirements
Labels: size/S

#438 Remove compatibility with GCC <= 7
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/S

#439 Introduce and use Matrix<>::swap
  src/libs/antares/array/matrix.h
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/area/links.cpp
Labels: size/S

#440 Do not remove Chocolatey's cpack.exe
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#451 Merge 'doc' branch
  README.md
  docs/build/0-INSTALL.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
Labels: size/L

#454 Merge develop
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
  README.md
  docs/build/0-INSTALL.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/L

#455 Merge develop
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
  README.md
  docs/build/0-INSTALL.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/L

#456 Merge develop
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
  README.md
  docs/build/0-INSTALL.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/L

#457 Merge develop
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
  README.md
  docs/build/0-INSTALL.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/L

#459 Merge develop
  .github/workflows/windows-pre-compiled-only.yml
  .github/workflows/windows-vcpkg.yml
  README.md
  docs/build/0-INSTALL.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
  src/tests/src/libs/antares/study/area/files-helper.cpp
  src/tests/src/libs/antares/study/area/files-helper.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
Labels: size/L

#421 review INSTALL procedure
  INSTALL-centos.md
  INSTALL-ubuntu.md
  INSTALL-windows.md
  INSTALL.md
  README.md
  docs/build/0-INSTALL.md
  docs/build/1-Development-requirements.md
  docs/build/2-Dependencies-install.md
  docs/build/3-Build.md
  docs/build/4-Tests.md
  docs/build/5-Installer-creation.md
  docs/build/INSTALL-centos.md
  docs/build/INSTALL-ubuntu.md
  docs/build/INSTALL-windows.md
  docs/index.md
  mkdocs.yml
Labels: size/XXL

#432 NTC with multi time series : internal structures
  src/libs/antares/array/matrix.h
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/action/handler/antares-study/link/hurdles-cost.cpp
  src/libs/antares/study/action/handler/antares-study/link/impedances.cpp
  src/libs/antares/study/action/handler/antares-study/link/ntc.cpp
  src/libs/antares/study/action/handler/antares-study/link/unload-data.cpp
  src/libs/antares/study/area/constants.h
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/create.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_adequation.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/links/congestionProbability.h
  src/solver/variable/economy/links/hurdleCosts.h
  src/solver/variable/economy/links/loopFlow.h
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
Labels: work in progress, size/XL

#447 Add data structures for link TS numbers
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/sim_variables_globales.cpp
Labels: size/M

#431 Infeasible problem analysis: pretty print
  docs/reference-guide/1-reference-guide.md
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/CMakeLists.txt
  src/solver/cmake/infeasible-problem-analysis.cmake
  src/solver/cmake/solver.cmake
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/constraint.h
  src/solver/infeasible-problem-analysis/exceptions.cpp
  src/solver/infeasible-problem-analysis/exceptions.h
  src/solver/infeasible-problem-analysis/problem.cpp
  src/solver/infeasible-problem-analysis/problem.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/solver/infeasible-problem-analysis/report.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_outils.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
  src/solver/utils/ortools_wrapper.h
Labels: size/XL

#448 Use time-series index in CONG PROB computation
  src/solver/variable/economy/links/congestionProbability.h
Labels: size/XS

#462 Check all NTC TS in the Kirchoff constraint builder
  src/solver/constraints-builder/cbuilder.cpp
Labels: PR: waiting for review

#461 Fix intra-modal TS number check and random generation
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/simulation/timeseries-numbers.h
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: PR: waiting for review, size/L

#472 Fix segfault with disabled thermal clusters
  src/libs/antares/study/parts/renewable/container.cpp
  src/libs/antares/study/parts/thermal/container.cpp
Labels: size/XS
