Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-03, with the labels that each got.

#150 add check for branch name in CI and with git hooks
  .githooks/pre-commit
  .github/workflows/branchNameValidation.yml
  CONTRIBUTING.md
  CONTRIBUTING.txt
  src/distrib/win32/sourcefiles.inc.nsh
Labels: enhancement

#182 Remove warnings for unused variables formatNames, formatExt, etc.
  src/ui/simulator/toolbox/components/map/component.cpp
  src/ui/simulator/toolbox/components/map/settings.h
  src/ui/simulator/windows/exportmap.cpp
Labels: PR: waiting for review

#185 correction of MC years weight write
  src/libs/antares/study/parameters.cpp
Labels: bug

#192 fix hydro hot start with refresh span enabled
  NEWS.txt
  src/changelog.mdown
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
Labels: bug

#189 copy dll and resources for windows zip installer
  .github/workflows/centos7-system.yml
  .github/workflows/linux-system.yml
  .github/workflows/windows-BUILD_DEPS.yml
  .github/workflows/windows-vcpkg.yml
  src/ui/simulator/CMakeLists.txt
Labels: enhancement

#187 Deallocate global variables
  src/solver/main.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
Labels: PR: waiting for review, bug

#188 Determine first week of the simulation (for xpansion outputs) - 2
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/adequacy-draft.cpp
  src/solver/simulation/adequacy-draft.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
Labels: enhancement

#195 correction of export of xpansion files if playlist used
  NEWS.txt
  src/changelog.mdown
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
Labels: bug

#179 Code cleaning : PROBLEME_HEBDO
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: enhancement

#193 Refresh span set by user cannot be less than 1
  src/ui/simulator/toolbox/components/datagrid/renderer/simulation.cpp
Labels: PR: waiting for review, bug

#199 Feature/change version 8 0 1
  NEWS.txt
  src/CMakeLists.txt
  src/changelog.mdown
  src/libs/antares/study/version.cpp
Labels: enhancement

#203 remove --fix-missing option for apt-get update
  .github/workflows/linux-BUILD_DEPS.yml
  .github/workflows/linux-system.yml
  .github/workflows/releasesLinux.yml
Labels: bug

#202 Update ubuntu doc : remove instructions for CMake installation
  INSTALL-ubuntu.md
Labels: PR: waiting for review

#205 Apply clang-format
  src/libs/antares/study/action/handler/antares-study/area/allocation-hydro-post.cpp
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/parameters.cpp
  src/solver/hydro/daily2/h2o2_j_apply_costs.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/components/map/component.cpp
  src/ui/simulator/toolbox/components/notebook/mapnotebook.cpp
  src/ui/simulator/windows/exportmap.cpp
  src/ui/simulator/windows/onLineConsent/on-line-consent.cpp
  src/ui/simulator/windows/onLineConsent/on-line-consent.h
  src/ui/simulator/windows/proxy/proxysetup.cpp
Labels: size/L

#197 Fix freeze when changing area color
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/processevent.cpp
  src/ui/simulator/cmake/application.cmake
Labels: bug, size/M

#207 correction of MC year weight use for PSP and MISC NDG
  src/solver/variable/commons/miscGenMinusRowPSP.h
  src/solver/variable/commons/psp.h
  src/tests/examples/code_generator.py
  src/tests/examples/output_compare_test.py
Labels: bug, size/S

#208 change version and changelog for 8.0.2
  NEWS.txt
  src/CMakeLists.txt
  src/changelog.mdown
Labels: enhancement, size/S
