Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-01, with the labels that each got.

#103 Update label when using reverse and selection button and correction for status changes with numeric values
  src/ui/simulator/toolbox/components/datagrid/renderer/mc-playlist.cpp
  src/ui/simulator/windows/options/playlist/playlist.cpp
Labels: PR: ready for merge, bug

#105 Change MC years weight to float instead of int
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/variable/storage/averagedata.h
  src/solver/variable/storage/stdDeviation.h
  src/tests/end-to-end/simple-study.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/mc-playlist.cpp
  src/ui/simulator/windows/options/playlist/playlist.cpp
Labels: PR: ready for merge, enhancement

#108 Scenario builder + hydro levels : bug fix
  src/solver/hydro/management/daily.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/solver.hxx
Labels: bug

#129 disable glop solver
  src/solver/utils/ortools_utils.cpp
Labels: bug

#131 Fix/invalid export xpansion struct names
  src/solver/optimisation/opt_export_structure.cpp
Labels: PR: waiting for review, bug

#128 Update log in case of upgrade needed because of study input update
  src/libs/antares/study/load.cpp
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/tests/data/free_data_sample/Desktop.ini
  src/tests/data/free_data_sample/settings/generaldata.ini
  src/tests/data/free_data_sample/study.antares
Labels: enhancement

#116 Fix/sc builder hydro auto reframe entry
  src/libs/antares/study/scenario-builder/hydroLevelsData.cpp
  src/libs/antares/study/scenario-builder/scBuilderUtils.cpp
  src/libs/antares/study/scenario-builder/scBuilderUtils.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.h
Labels: PR: waiting for review
