Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2021-09, with the labels that each got.

#375 Fix hydro heuristic
  src/solver/hydro/management/management.cpp
Labels: size/S

#376 UI : ts management status bug
  src/ui/simulator/toolbox/components/datagrid/renderer/ts-management-clusters-as-renewables.cpp
Labels: bug, PR: waiting for review, size/XS, GUI

#366 Fix handling of skipped binding constraints
  src/libs/antares/study/constraint/constraint.h
  src/libs/antares/study/constraint/constraint.hxx
  src/ui/simulator/toolbox/components/datagrid/renderer/bindingconstraint/offsets.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/bindingconstraint/weights.cpp
Labels: PR: waiting for review, size/L

#367 Remove libantares-ui-component-htmllistbox
  src/ui/simulator/cmake/components.cmake
Labels: size/M

#382 Feature/sonarcloud
  .github/workflows/sonarcloud.yml
  sonar-project.properties
  src/CMakeLists.txt
  src/cmake/CodeCoverage.cmake
Labels: size/L, code

#389 remove src/ext from sonarcloud analysis
  sonar-project.properties
Labels: size/XS, code

#377 LPsolve measurements
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
  src/solver/simulation/solver.utils.h
  src/solver/utils/optimization_statistics.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/state.hxx
Labels: size/L

#388 Pass typeVar instead of &Probleme, remove unused function argument
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_wrapper.h
Labels: size/M, cleaning

#387 Clean OPT code
  src/solver/optimisation/opt_construction_matrice_des_contraintes_outils.cpp
  src/solver/optimisation/opt_fonctions.h
Labels: size/M, cleaning
