Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-10, with the labels that each got.

#880 [DOC] OR-Tools build
  docs/build/2-Dependencies-install.md
Labels: size/S

#813 Document zip output feature
  .github/workflows/centos7-release.yml
  .github/workflows/centos7-system.yml
  .github/workflows/centos7.yml
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-release.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  docker/centos7-basic-requirements
  docs/CHANGELOG.md
  docs/build/2-Dependencies-install.md
  docs/reference-guide/10-command_line.md
  docs/reference-guide/13-file-format.md
  simtest.json
  src/CMakeLists.txt
  src/cmake/utils.cmake
  src/libs/antares/CMakeLists.txt
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/layerdata.cpp
  src/libs/antares/study/layerdata.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/mps.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/save.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/application.cpp
  src/solver/main.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/solver/variable/area.inc.hxx
  src/solver/variable/commons/links/links.h.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/economy/links/marginalCost.h
  src/solver/variable/economy/renewableGeneration.h
  src/solver/variable/endoflist.h
  src/solver/variable/state.h
  src/solver/variable/state.hxx
  src/solver/variable/variable.h
  src/solver/variable/variable.hxx
  src/tests/CMakeLists.txt
  src/tests/run-study-tests/check_on_results/check_mps_existence.py
  src/ui/simulator/toolbox/input/connection.cpp
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/XXL, doc

#864 Move writer creation to Study
  src/solver/application.cpp
  src/solver/main/adequacy-draft.cpp
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
Labels: size/S

#805 Use generic writer to write simulation.log
  src/libs/antares/study/importlogs.cpp
Labels: size/M

#897 Remove unused arg from function DispatchableMarginForAllAreas
  src/solver/simulation/common-dispatchable-margin.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
Labels: size/S, cleaning

#807 Use generic writer to write MPS files, criterion, interco, etc.
  src/solver/application.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/main/adequacy-draft.cpp
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
Labels: size/L

#902 Document how to run JSON tests
  docs/build/4-Tests-user.md
Labels: size/M, doc

#904 Use GIT_SHALLOW for OR-Tools's FetchContent
  src/CMakeLists.txt
Labels: size/XS

#916 Remove swap from online documentation
  docs/reference-guide/02-data_organization.md
  docs/reference-guide/03-commands.md
  docs/reference-guide/09-system_requirements.md
  docs/reference-guide/10-command_line.md
Labels: PR: waiting for review, size/S, doc

#924 Crash when many binding constraints in a study
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: bug, PR: waiting for review, size/S

#926 Fix : infinite duration run on Windows
  src/solver/variable/container.hxx
Labels: bug, PR: waiting for review, size/XS

#929 Use generic writer to write ts-numbers, refactor
  src/libs/antares/array/matrix.h
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/area.hxx
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/area/list.hxx
  src/libs/antares/study/area/store-timeseries-numbers.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/common/cluster_list.h
  src/libs/antares/study/study.h
  src/libs/antares/study/study.hxx
Labels: size/L
