Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-07, with the labels that each got.

#750 Add option to split MPS files
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: enhancement, size/M

#747 Allow batch edit for adq-patch mode
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/M, GUI, adq-patch

#758 Doc/update 8 3
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/05-output_files.md
Labels: size/S

#760 Feature/rte csr comments batch2
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
Labels: size/XL

#766 Document recent changes in the study format
  docs/reference-guide/13-file-format.md
  mkdocs.yml
Labels: size/M, doc

#767 Disable DENS output variable if adq-patch is disabled
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/application.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
Labels: bug, size/M, adq-patch

#776 Polish the doc related to the adq-patch
  docs/reference-guide/05-output_files.md
  docs/reference-guide/08-miscellaneous.md
  docs/reference-guide/13-file-format.md
  docs/reference-guide/14-adequacy-patch.md
  mkdocs.yml
Labels: size/L, doc

#782 Add VERSION attribute to CMake project
  src/CMakeLists.txt
Labels: size/XS, build

#757 Fix a few compilation warnings
  src/solver/hydro/management/management.cpp
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/tests/end-to-end/simple-study.cpp
Labels: size/S, code

#772 Fix GUI crashes in the "Local Data" panel
  src/ui/simulator/windows/xcast/xcast.hxx
Labels: bug, size/XS, GUI

#786 Beta 5 executable
  src/CMakeLists.txt
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
Labels: size/XS

#736 Adding tests about infinity on BCs RHS
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
Labels: size/S

#795 Make executables!
  src/CMakeLists.txt
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/simulation/economy.cpp
Labels: size/M
