Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-02, with the labels that each got.

#524 Include water level equations whenever hydro-pricing==accurate or heuristic==false or pumping==true
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/L

#521 Fix segfault when study folder does not exist / refactor error handling in solver's main()
  src/libs/antares/CMakeLists.txt
  src/libs/antares/constants.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/memory/memory.cpp
  src/libs/antares/memory/memory.h
  src/libs/antares/memory/swapfile.cpp
  src/libs/antares/memory/swapfile.h
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/load-options.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/CMakeLists.txt
  src/solver/application.cpp
  src/solver/application.h
  src/solver/exceptions.h
  src/solver/main.cpp
  src/solver/main.hxx
  src/solver/main/adequacy-draft.cpp
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/misc/options.cpp
  src/solver/misc/options.h
  src/solver/misc/process-priority.cpp
  src/tools/yby-aggregator/main.cpp
Labels: bug, size/XXL

#537 Simplify yearFailed[y] assignment
  src/solver/simulation/solver.hxx
Labels: size/S, cleaning, code

#538 Code cleaning
  src/solver/simulation/sim_calcul_economique.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer.hxx
Labels: size/XS, cleaning

#425 Fix weekly->daily interpolation for min/max reservoir level
  src/solver/simulation/sim_calcul_economique.cpp
Labels: bug, help wanted, size/XS

#541 Remove duplicate bool StudyLoadOptions::useOrtools
  src/libs/antares/study/load-options.h
  src/solver/misc/options.cpp
Labels: bug, size/XS

#540 container.hxx : remove old comments, use std::shared_ptr
  src/solver/variable/container.hxx
Labels: size/M, cleaning, code

#254 Add debug switch for hydro allocation
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
Labels: size/L, feature

#548 Correct hydro-pricing mode when it is wrong
  src/libs/antares/study/parameters.cpp
Labels: size/XS

#550 [UI] Fix segfault on area copy-paste
  src/libs/antares/study/action/context.cpp
  src/libs/antares/study/action/context.h
  src/libs/antares/study/action/handler/antares-study/area/allocation-hydro-post.cpp
  src/libs/antares/study/action/handler/antares-study/area/correlation-post.cpp
  src/libs/antares/study/action/handler/antares-study/area/create.cpp
  src/libs/antares/study/action/handler/antares-study/constraint/create.cpp
  src/libs/antares/study/action/handler/antares-study/constraint/offsets.cpp
  src/libs/antares/study/action/handler/antares-study/constraint/weights.cpp
  src/libs/antares/study/action/handler/antares-study/link/create.cpp
  src/libs/antares/study/action/handler/antares-study/thermal-cluster/create.cpp
  src/ui/simulator/application/main/paste-from-clipboard.cpp
  src/ui/simulator/toolbox/ext-source/handler/com.rte-france.antares.study.cpp
  src/ui/simulator/toolbox/ext-source/handler/handler.h
  src/ui/simulator/toolbox/ext-source/performer.cpp
Labels: size/L, GUI

#570 Revert "UI: Change and rename "upstream/downstream" view"
  src/ui/simulator/toolbox/input/connection.cpp
Labels: size/M

#558 Ignore disabled MC years when computing average NTC
  src/solver/simulation/common-eco-adq.cpp
Labels: size/XS

#552 Remove optImmediate from links' timeseries
  src/libs/antares/study/area/links.cpp
Labels: size/XS

#568 Fix infinite capacity bug
  src/libs/antares/study/area/links.cpp
Labels: size/XS

#572 Link upper banner : update the banner (or board) when changing of tab
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/windows/connection.cpp
  src/ui/simulator/windows/connection.h
Labels: size/L, GUI

#571 Change styles related to loop-flow
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.h
Labels: PR: waiting for review, size/M, GUI

#576 Fix bug related to short-circuit evaluation
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
Labels: size/M
