Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-11, with the labels that each got.

#933 Adequacy Patch Sequel
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
Labels: size/S, adq-patch

#898 Remove unused methods from class Parameters
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
Labels: size/S, cleaning

#739 Make sure that RC/beta are displayed in version numbers
  src/CMakeLists.txt
  src/config.h.cmake
  src/libs/antares/version.cpp
  src/solver/application.cpp
  src/ui/simulator/windows/about/aboutbox.cpp
  src/ui/simulator/windows/startupwizard.cpp
  src/ui/simulator/windows/version.cpp
Labels: enhancement, size/M, GUI

#896 Remove unused global variables
  src/solver/application.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/sim_variables_globales.cpp
Labels: size/L, cleaning, code

#935 MPS : remove calls to Study::Current::Get
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
Labels: size/M, cleaning, code, refactoring

#937 [FIX] Remove unused files src/libs/antares/files
  src/libs/antares/CMakeLists.txt
  src/libs/antares/files/files.cpp
  src/libs/antares/files/files.h
Labels: size/L, cleaning

#928 Do not export BC results by default
  .github/workflows/run-tests/action.yml
  .github/workflows/windows-release.yml
  src/libs/antares/study/constraint/constraint.h
Labels: size/S

#940 BC's marginal prices output correction
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/storage/intermediate.cpp
Labels: PR: waiting for review, size/S

#938 [CI] Upgrade deprecated actions
  .github/workflows/branchNameValidation.yml
  .github/workflows/build-userguide.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7.yml
  .github/workflows/generate-userguide-pdf/action.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  .gitignore
Labels: size/L, ci

#944 Removed dead code associated to ANTARES_USE_GLOBAL_MAXIMUM_COST
  src/libs/antares/constants.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/L

#947 Clean up gitignore
  .gitignore
Labels: size/S

#950 Remove unused var in struct CORRESPONDANCES_DES_VARIABLES
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, cleaning

#792 Add option to set link capacity to null/infinity for physical links only
  docs/reference-guide/13-file-format.md
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/links/property-links-helper.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/links/summary.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/link-property-buttons.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/XL

#923 Fix crash when exporting MPS with OR-Tools
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/utils/mps_utils.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_wrapper.h
Labels: size/M

#953 Adequacy Patch CSR Solution Update
  src/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/simulation/economy.cpp
Labels: size/S, adq-patch

#895 Remove error message printed on -h/--help
  src/analyzer/main.cpp
  src/cmake/common-settings.cmake
  src/ext/yuni/src/yuni/CMakeLists.txt
  src/ext/yuni/src/yuni/cmake/core/core.cmake
  src/ext/yuni/src/yuni/core/getopt/parser.cpp
  src/ext/yuni/src/yuni/core/getopt/parser.h
  src/solver/application.cpp
  src/tools/batchrun/main.cpp
  src/tools/cleaner/main.cpp
  src/tools/config/main.cpp
  src/tools/finder/main.cpp
  src/tools/updater/main.cpp
  src/tools/vacuum/main.cpp
  src/tools/yby-aggregator/main.cpp
  src/ui/simulator/main.cpp
Labels: size/M

#955 Adequacy-patch Update - beta 10 version
  src/CMakeLists.txt
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/M, adq-patch

#956 Remove obsolete option `include-split-exported-mps`
  docs/reference-guide/13-file-format.md
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/application.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/L

#954 Remove EconomyWeeklyOptimization::initializeProblemeHebdo
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/M, cleaning, code, adq-patch

#946 Refactor average results
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/economy/links/marginalCost.h
  src/solver/variable/economy/price.h
  src/solver/variable/economy/reservoirlevel.h
  src/solver/variable/economy/waterValue.h
  src/solver/variable/info.h
  src/solver/variable/storage/intermediate.cpp
  src/solver/variable/storage/intermediate.h
Labels: size/L

#958 Adequacy patch CSR - final
  docs/reference-guide/03-commands.md
  src/CMakeLists.txt
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/cmake/solver.cmake
  src/solver/cmake/variable.cmake
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_LHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/dtgMarginAfterCsr.h
  src/solver/variable/economy/localMatchingRuleViolations.h
  src/solver/variable/economy/spilledEnergyAfterCSR.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/application/main/options.cpp
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/cmake/windows-options.cmake
  src/ui/simulator/toolbox/components/datagrid/gridhelper.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.h
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/XXL, adq-patch

#957 Feature/xpress extract basis
  .github/workflows/centos7.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
  src/solver/application.cpp
  src/solver/cmake/simulation.cmake
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/opt_time_writer.cpp
  src/solver/simulation/opt_time_writer.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
  src/solver/simulation/solver.utils.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/optimization_statistics.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_wrapper.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/state.hxx
Labels: size/L

#967 [TEST] Activate automatic gcov report on SonarCloud
  .github/workflows/sonarcloud.yml
  sonar-project.properties
  src/cmake/CodeCoverage.cmake
  src/cmake/common-settings.cmake
Labels: size/S, tests

#960 Using clang
  src/ext/yuni/src/yuni/core/string/iterator.inc.hpp
  src/ext/yuni/src/yuni/core/system/stdint.h
  src/ui/simulator/toolbox/create.h
  src/ui/simulator/toolbox/create.hxx
Labels: size/S
