Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-04, with the labels that each got.

#625 Hydro hot start : relaxing error message in case reservoir management is OFF
  src/libs/antares/study/study.cpp
Labels: bug, size/S

#628 Use std::unique_ptr for GetOpt::Parser
  src/solver/misc/options.cpp
  src/solver/misc/options.h
Labels: size/XS

#624 Antares solver options : fix a bug on Windows
  src/libs/antares/study/study.cpp
  src/solver/application.cpp
  src/solver/misc/options.cpp
  src/solver/misc/options.h
Labels: bug, size/L

#525 Tests : activating end-to-end tests on Windows OS
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  src/tests/CMakeLists.txt
  src/tests/examples/antares_test_utils.py
  src/tests/examples/output_compare_test.py
Labels: work in progress, size/L

#637 Remove references to BUILD_not_system
  docs/build/2-Dependencies-install.md
  docs/build/3-Build.md
Labels: size/XS

#626 Scenario builder warnings too long
  src/libs/antares/study/scenario-builder/rules.cpp
Labels: enhancement, size/S

#636 Remove build option BUILD_OUTPUT_TEST
  docs/build/3-Build.md
  docs/build/4-Tests.md
  src/tests/CMakeLists.txt
Labels: size/S

#617 Do not perform quadratic opt if FLOW QUAD. is disabled
  src/solver/simulation/common-eco-adq.cpp
Labels: enhancement, size/XS

#646 RTE Comment implementation 3 (#34)
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/solver/application.cpp
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/L

#650 Fix : Wind & Solar time-series set as generated, but renewable policy is "Clusters"
  src/solver/variable/commons/solar.h
  src/solver/variable/commons/wind.h
Labels: size/M

#651 Use std::enable_shared_from_this
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/libs/antares/study/parts/thermal/prepro.h
Labels: size/M

#640 Thermal clusters TS generation management prevents parallel running
  src/solver/simulation/solver.hxx
Labels: size/XS

#652 [solver] Remove useless parentheses
  src/solver/hydro/daily/h2o_j_free.c
  src/solver/hydro/daily2/h2o2_j_free.cpp
  src/solver/hydro/monthly/h2o_m_free.c
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/solver.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: size/L, code

#597 Adequacy Patch - Local Matching Rule 15/03
  docs/reference-guide/1-reference-guide.md
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/application.cpp
  src/solver/cmake/solver.cmake
  src/solver/cmake/variable.cmake
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/domesticUnsuppliedEnergy.h
  src/ui/simulator/application/study.cpp
  src/ui/simulator/application/study.h
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/XXL, feature, adq-patch

#631 Allow +/- infinity in binding constraint RHS
  THANKS.txt
  src/libs/antares/CMakeLists.txt
  src/libs/antares/array/matrix.hxx
  src/libs/antares/string-to-double.cpp
  src/libs/antares/string-to-double.h
  src/solver/ts-generator/thermal.cpp
  src/tests/src/libs/antares/CMakeLists.txt
Labels: size/L

#144 Mode xpansion - splitting MPS files depending on simulation week
  src/libs/antares/study/mps.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/libs/antares/study/study.h
  src/solver/cmake/solver.cmake
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/ts-generator/generator.h
  src/solver/ts-generator/thermal.cpp
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/tests/examples/specific_test.py
Labels: help wanted, PR: waiting for review, size/XL

#653 Fix compilation warning related to signed/unsigned integers
  src/solver/hydro/daily/h2o_j_ajouter_bruit_au_cout.cpp
  src/solver/hydro/daily/h2o_j_donnees_optimisation.h
Labels: size/XS, code

#656 Remove dead code - interval calculation
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
Labels: size/S

#658 Invalidate link before calling setMatrix(link)
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/area/links.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
Labels: size/S

#660 Fix compilation warning in file helper
  src/tests/src/libs/antares/study/area/files-helper.cpp
Labels: size/XS

#655 Make absence of areas/<area>/adequacy_patch.ini non-fatal
  src/libs/antares/study/area/list.cpp
Labels: bug, size/XS, adq-patch
