Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-05, with the labels that each got.

#627 Avoid error messages on TS preprocessor content when thermal TS are ready made
  src/libs/antares/study/parameters.hxx
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/libs/antares/study/parts/thermal/prepro.h
Labels: bug, size/L

#563 Doc/replace docx by markdown generation
  .github/workflows/build-userguide.yml
  .github/workflows/centos7-system.yml
  .github/workflows/generate-userguide-pdf/action.yml
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
  .gitignore
  docs/pdf-doc-generation-with-sphinx/source/conf.py
  docs/pdf-doc-generation-with-sphinx/source/index.rst
  docs/ref_guides/antares-general-reference-guide.docx
  docs/ref_guides/antares-general-reference-guide.pdf
  docs/ref_guides/optimization-problems-formulation.docx
  docs/ref_guides/optimization-problems-formulation.pdf
  docs/reference-guide/01-introduction.md
  docs/reference-guide/02-data_organization.md
  docs/reference-guide/03-commands.md
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/05-output_files.md
  docs/reference-guide/06-time_series_analysis_and_generation.md
  docs/reference-guide/07-kirchhoffs_constraint_generator.md
  docs/reference-guide/08-miscellaneous.md
  docs/reference-guide/09-system_requirements.md
  docs/reference-guide/1-reference-guide.md
  docs/reference-guide/10-command_line.md
  docs/reference-guide/11-modeling.md
  docs/reference-guide/12-attribution_notices.md
  docs/reference-guide/Reduced_Allowance.png
  mkdocs.yml
  src/ui/simulator/application/main/help.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
Labels: size/XXL, doc

#661 Include version tag in release package names
  src/CMakeLists.txt
Labels: size/XS

#676 CentOS 7 : integrate OR-Tools + XPRESS
  .github/workflows/centos7-system.yml
Labels: size/M

#654 Cosmetic changes to the adequacy patch (pt. 1 - local matching rule)
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/fwd.h
  src/solver/application.cpp
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/domesticUnsuppliedEnergy.h
  src/ui/simulator/application/study.cpp
  src/ui/simulator/application/study.h
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
Labels: size/L, adq-patch

#671 H2O_M : make variable numbers explicit
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.c
Labels: size/M, code

#688 Doc/update 8 2
  docs/reference-guide/01-introduction.md
  docs/reference-guide/02-data_organization.md
  docs/reference-guide/03-commands.md
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/05-output_files.md
  docs/reference-guide/07-kirchhoffs_constraint_generator.md
  docs/reference-guide/08-miscellaneous.md
  docs/reference-guide/09-system_requirements.md
Labels: size/L

#687 Remove unused PerArea::MLN
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
Labels: cleaning, code

#546 Add output file for time measurements
  src/libs/antares/CMakeLists.txt
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/load.cpp
  src/libs/antares/timeelapsed.h
  src/libs/antares/timeelapsed/content_handler.cpp
  src/libs/antares/timeelapsed/content_handler.h
  src/libs/antares/timeelapsed/csv_writer.cpp
  src/libs/antares/timeelapsed/csv_writer.h
  src/libs/antares/timeelapsed/i_writer.h
  src/libs/antares/timeelapsed/info.h
  src/libs/antares/timeelapsed/timer.cpp
  src/libs/antares/timeelapsed/timer.h
  src/solver/application.cpp
  src/solver/application.h
  src/solver/main.cpp
  src/solver/main.h
  src/solver/main/adequacy-draft.cpp
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/variable/surveyresults/data.h
  src/solver/variable/surveyresults/surveyresults.cpp
  src/solver/variable/surveyresults/surveyresults.h
  src/tests/end-to-end/simple-study.cpp
Labels: size/XL
