Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-06, with the labels that each got.

#701 Merge tag 8.2.2
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/XS

#694 Fix segfault occuring when inter/intramodal == true and TS width are inconsistent
  src/solver/simulation/solver.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/simulation/timeseries-numbers.h
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/M

#698 Display commit-id in the solver logs, if available
  src/solver/application.cpp
Labels: enhancement, size/XS

#686 Add profit output for clusters
  src/solver/cmake/variable.cmake
  src/solver/variable/area.inc.hxx
  src/solver/variable/economy/all.h
  src/solver/variable/economy/profitByPlant.h
Labels: size/L, feature

#706 [CI] Restore unit & end-to-end tests
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#705 Fix version check of Boost in CMake files
  src/tests/CMakeLists.txt
Labels: size/S

#709 thermal cluster profit output for adequacy mode
  src/solver/variable/adequacy/all.h
Labels: size/S

#680 Fix logging of performed years
  src/solver/simulation/solver.hxx
Labels: bug, size/M

#712 Add interface class + implementations for economy weekly problem
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/L, code, adq-patch

#702 Fix segfault occurring when calling antares-solver with --version
  src/solver/application.cpp
  src/solver/application.h
Labels: bug, size/XS

#713 Update doc version 8.3
  docs/pdf-doc-generation-with-sphinx/source/conf.py
  docs/reference-guide/01-introduction.md
  docs/reference-guide/10-command_line.md
  docs/reference-guide/12-attribution_notices.md
Labels: size/S, doc

#710 Update documentation for Adequacy Patch - Local Matching Rule
  docs/reference-guide/03-commands.md
  docs/reference-guide/08-miscellaneous.md
Labels: size/M, doc

#704 Local matching rule : last remarks
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/M, adq-patch

#719 Update version 8.3, add changelog
  docs/CHANGELOG.md
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
Labels: size/M

#657 Adequacy Patch - Local matching
  .github/workflows/ubuntu-system.yml
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/application.cpp
  src/solver/cmake/solver.cmake
  src/solver/cmake/variable.cmake
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/domesticUnsuppliedEnergy.h
  src/tests/CMakeLists.txt
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/optimisation/CMakeLists.txt
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/constants.cpp
  src/ui/simulator/windows/inspector/constants.h
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/XXL, adq-patch

#721 UI - fix a bug on map layers
  src/ui/simulator/toolbox/components/map/control.cpp
Labels: bug, size/XS, GUI

#668 Remove PminDuPalierThermiquePendantUneSemaine
  src/solver/optimisation/opt_donnees_pas_de_temps_variable.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/XS, cleaning, code

#667 Remove GROSSES_VARIABLES
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/L, cleaning, code

#725 Clarify label for output column 'Profit by plant'
  src/solver/variable/economy/profitByPlant.h
Labels: enhancement, size/XS

#666 Remove SUBSTITUTION_DE_LA_VARIABLE_MPLUS
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
Labels: size/L, cleaning, code

#672 Add --list-solvers command-line argument
  src/libs/antares/study/load-options.h
  src/solver/application.cpp
  src/solver/misc/options.cpp
Labels: size/S

#735 Profit by plant : only compute average
  src/solver/variable/economy/profitByPlant.h
Labels: size/XL

#738 Fix possible loss of data if adq-patch is disabled
  src/libs/antares/study/area/list.cpp
Labels: bug, size/XS, adq-patch
