Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-03, with the labels that each got.

#562 Pressing the 'delete' opens a deletion popup for current selection
  src/ui/simulator/toolbox/components/map/component.cpp
  src/ui/simulator/toolbox/components/map/component.h
  src/ui/simulator/toolbox/components/map/control.cpp
  src/ui/simulator/toolbox/components/map/control.h
  src/ui/simulator/toolbox/components/map/controls/addtools.cpp
  src/ui/simulator/toolbox/components/map/controls/addtools.h
Labels: size/M, GUI

#585 Fix "Save as" freezing main window
  src/ui/simulator/windows/saveas.cpp
Labels: bug, linux, size/XS, GUI

#586 Linux - fix UI freeze when using "save as"
  src/ui/simulator/windows/saveas.cpp
Labels: bug, linux, size/XS, GUI

#584 UI : fix assertion failures in debug mode
  src/ui/simulator/windows/constraints-builder/constraintsbuilder.cpp
  src/ui/simulator/windows/memorystatistics/memorystatistics.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/studylogs.cpp
Labels: size/XS, GUI

#596 Restore previous results for NonRegTests
  src/libs/antares/study/parts/renewable/container.cpp
  src/libs/antares/study/parts/thermal/container.cpp
  src/solver/hydro/management/management.cpp
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/M

#575 GUI Refactoring : Share elements of link upper banner between pages
  src/ui/simulator/cmake/windows-studyparts.cmake
  src/ui/simulator/windows/connection.cpp
  src/ui/simulator/windows/connection.h
  src/ui/simulator/windows/link-property-buttons.cpp
  src/ui/simulator/windows/link-property-buttons.h
Labels: size/XXL

#600 Fix/UI linux do not check root folder
  src/ui/simulator/windows/exportmap.cpp
  src/ui/simulator/windows/saveas.cpp
Labels: linux, size/M, GUI

#595 Save NTC timeseries even if all coefficients are zero
  src/libs/antares/array/matrix.h
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/area/links.cpp
Labels: bug, size/M, GUI

#604 Add noise to the cost in the daily & monthly allocation problem
  src/solver/cmake/hydro.cmake
  src/solver/hydro/daily/Test.c
  src/solver/hydro/daily/h2o_j_ajouter_bruit_au_cout.cpp
  src/solver/hydro/daily/h2o_j_fonctions.h
  src/solver/hydro/daily/h2o_j_resoudre_le_probleme_lineaire.c
  src/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/daily2/h2o2_j_fonctions.h
  src/solver/hydro/daily2/h2o2_j_optim_costs.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/Test.c
  src/solver/hydro/monthly/h2o_m_ajouter_bruit.cpp
  src/solver/hydro/monthly/h2o_m_donnees_optimisation.h
  src/solver/hydro/monthly/h2o_m_fonctions.h
  src/solver/hydro/monthly/h2o_m_free.c
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.c
  src/solver/hydro/monthly/h2o_m_instanciation.c
  src/solver/hydro/monthly/h2o_m_optimiser_une_annee.c
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.c
  src/tests/examples/example_test.py
  src/tests/examples/output_compare_test.py
Labels: size/XXL

#607 Set 'Dataset > Resize columns to' in first position
  src/ui/simulator/toolbox/components/datagrid/modifiers.hxx
Labels: size/XS, GUI

#606 [Linux] Fix segfault occurring when an INI file does not exist
  src/libs/antares/inifile/inifile.cpp
Labels: bug, linux, size/XS, adq-patch

#621 Trigger workflow in do-not-merge-adq-patch
  src/libs/antares/array/matrix.h
  src/libs/antares/array/matrix.hxx
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/inifile/inifile.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parts/common/cluster_list.h
  src/libs/antares/study/parts/renewable/container.cpp
  src/libs/antares/study/parts/thermal/container.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/study.cpp
  src/solver/application.cpp
  src/solver/cmake/solver.cmake
  src/solver/hydro/management/management.cpp
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/renseigner_donnees_couts_demarrage.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/ui/simulator/cmake/windows-studyparts.cmake
  src/ui/simulator/toolbox/components/datagrid/modifiers.hxx
  src/ui/simulator/windows/connection.cpp
  src/ui/simulator/windows/connection.h
  src/ui/simulator/windows/constraints-builder/constraintsbuilder.cpp
  src/ui/simulator/windows/exportmap.cpp
  src/ui/simulator/windows/link-property-buttons.cpp
  src/ui/simulator/windows/link-property-buttons.h
  src/ui/simulator/windows/memorystatistics/memorystatistics.cpp
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/saveas.cpp
  src/ui/simulator/windows/studylogs.cpp
Labels: size/XXL

#622 Add noise to the cost in the daily & monthly allocation problem
  src/solver/cmake/hydro.cmake
  src/solver/hydro/daily/Test.c
  src/solver/hydro/daily/h2o_j_ajouter_bruit_au_cout.cpp
  src/solver/hydro/daily/h2o_j_fonctions.h
  src/solver/hydro/daily/h2o_j_resoudre_le_probleme_lineaire.c
  src/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/daily2/h2o2_j_fonctions.h
  src/solver/hydro/daily2/h2o2_j_optim_costs.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/Test.c
  src/solver/hydro/monthly/h2o_m_ajouter_bruit.cpp
  src/solver/hydro/monthly/h2o_m_donnees_optimisation.h
  src/solver/hydro/monthly/h2o_m_fonctions.h
  src/solver/hydro/monthly/h2o_m_free.c
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.c
  src/solver/hydro/monthly/h2o_m_instanciation.c
  src/solver/hydro/monthly/h2o_m_optimiser_une_annee.c
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.c
  src/tests/examples/example_test.py
  src/tests/examples/output_compare_test.py
Labels: bug, size/XXL
