Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-09, with the labels that each got.

#855 BC. MARG. COST: use 2 decimals for the output value
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
Labels: size/XS

#853 Fix potential segfault with many BCs, refactor
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/variable/bindConstraints.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: size/L

#852 Digest: ignore thermal, renewable clusters, binding constraints
  src/solver/variable/storage/average.h
Labels: size/XS

#833 Update issue template for bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/XS

#834 Fix e-mail address and website
  docs/reference-guide/01-introduction.md
  src/CMakeLists.txt
Labels: size/XS, doc

#832 Simplify Parameters::fixRefreshIntervals, clean headers
  src/libs/antares/study/parameters.cpp
Labels: size/M, cleaning, code

#850 Make absence of pytest or numpy fatal at configure time
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  src/cmake/utils.cmake
  src/tests/CMakeLists.txt
Labels: size/M

#861 Add Antares logo in solver logs
  src/solver/main.cpp
Labels: enhancement, size/M

#869 Output variables: remove useless methods for renewable clusters
  src/solver/variable/area.inc.hxx
  src/solver/variable/commons/links/links.h.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/economy/renewableGeneration.h
  src/solver/variable/endoflist.h
  src/solver/variable/state.h
  src/solver/variable/state.hxx
  src/solver/variable/variable.h
  src/solver/variable/variable.hxx
Labels: size/M

#866 [DEV] Refactored Layers by adding a LayerData class
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/layerdata.cpp
  src/libs/antares/study/layerdata.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/save.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
Labels: size/L, cleaning, code

#788 Remove unused "shedding strategy"
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/ui/simulator/windows/options/advanced/advanced.cpp
Labels: size/M, cleaning, code

#777 Simplify day ahead reserve condition
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
Labels: size/XS, cleaning, code

#879 Fix Windows CI
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#755 Replace "Flat" view with "By area" view + refactor
  src/ui/simulator/toolbox/input/connection.cpp
Labels: size/L, GUI

#883 Fix warning in hydro.ini loading function
  src/libs/antares/study/parts/hydro/container.cpp
Labels: size/M

#865 Windows CI : fix overlapping CMake dependencies (zlib)
  antares-deps-version.json
  src/CMakeLists.txt
Labels: size/S

#877 Forbid OR-Tools + Split MPS
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/solver/application.cpp
Labels: size/S

#809 Use generic writer for hydro debug files
  src/libs/antares/benchmarking/info_collectors.h
  src/libs/antares/exception/InitializationError.hpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/application.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/signal-handling/common.cpp
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/utils/mps_utils.cpp
  src/solver/writer/zip_writer.cpp
  src/solver/writer/zip_writer.h
Labels: size/L

#881 Use average for variable MARG. COST (links)
  src/solver/variable/economy/links/marginalCost.h
Labels: size/XS

#886 Allow more than 100 thermal clusters
  src/libs/antares/study/parts/thermal/cluster.cpp
Labels: size/XS

#887 Fix segfault occurring when loading matrices outside solver/ui
  src/libs/antares/array/matrix.cpp
Labels: bug, size/XS

#872 MPS files printing : restore print of 1st and 2nd optimization, whether split or not
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  docs/reference-guide/13-file-format.md
  src/CMakeLists.txt
  src/cmake/utils.cmake
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/mps.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/study.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/tests/CMakeLists.txt
  src/tests/run-study-tests/check_on_results/check_mps_existence.py
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/L

#863 MPS writer refactoring : defining an mps writer interface and consequences
  docs/reference-guide/13-file-format.md
  src/CMakeLists.txt
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/mps.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/study.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/tests/run-study-tests/check_on_results/check_mps_existence.py
  src/ui/simulator/windows/options/optimization/optimization.cpp
  src/ui/simulator/windows/options/optimization/optimization.h
Labels: size/XL

#875 Release 8.3.2
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  docs/CHANGELOG.md
  src/CMakeLists.txt
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/solver/application.cpp
Labels: size/M
