Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-08, with the labels that each got.

#798 Make executables beta official
  docs/reference-guide/03-commands.md
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_LHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.h
Labels: size/XXL

#796 OR-Tools : set solver-specific options for XPRESS
  src/solver/utils/ortools_utils.cpp
Labels: size/S

#740 Refactoring info collect and saving on files
  src/libs/antares/CMakeLists.txt
  src/libs/antares/array/matrix.cpp
  src/libs/antares/benchmarking.h
  src/libs/antares/benchmarking/file_content.cpp
  src/libs/antares/benchmarking/file_content.h
  src/libs/antares/benchmarking/file_writer.cpp
  src/libs/antares/benchmarking/file_writer.h
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/benchmarking/info_collectors.h
  src/libs/antares/benchmarking/timer.cpp
  src/libs/antares/benchmarking/timer.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/load.cpp
  src/libs/antares/study/save.cpp
  src/libs/antares/timeelapsed/content_handler.cpp
  src/libs/antares/timeelapsed/content_handler.h
  src/libs/antares/timeelapsed/csv_writer.cpp
  src/libs/antares/timeelapsed/csv_writer.h
  src/libs/antares/timeelapsed/i_writer.h
  src/libs/antares/timeelapsed/info.h
  src/solver/application.cpp
  src/solver/application.h
  src/solver/main.cpp
  src/solver/main/adequacy-draft.cpp
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_algorithme_de_flot.cpp
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/thermal.cpp
  src/tests/end-to-end/simple-study.cpp
Labels: size/XL

#806 Create executables newest development
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
Labels: size/S

#779 Bump to CXX 17 from CXX 11
  src/CMakeLists.txt
  src/solver/variable/state.cpp
  src/tests/src/libs/antares/study/area/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
Labels: size/XS, build

#802 Fix missing renewable columns in districts (sets of areas)
  src/solver/variable/economy/all.h
Labels: bug, size/M

#820 execution_info.ini : add OR-Tools used & solver
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/benchmarking/info_collectors.h
Labels: size/S

#793 Fix wrong number of cores + code de-duplication
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/advanced/advanced.h
Labels: bug, size/M, GUI, cleaning, code

#818 Release/8.3.1
  docs/CHANGELOG.md
  docs/reference-guide/13-file-format.md
  src/CMakeLists.txt
  vcpkg_manifest/vcpkg.json
Labels: size/M

#825 Implement latest CSR comments
  docs/CHANGELOG.md
  docs/reference-guide/03-commands.md
  docs/reference-guide/13-file-format.md
  src/CMakeLists.txt
  src/libs/antares/benchmarking/file_content.cpp
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/benchmarking/info_collectors.h
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_LHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/all.h
  src/solver/variable/state.cpp
  src/tests/src/libs/antares/study/area/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.h
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/advanced/advanced.h
  vcpkg_manifest/vcpkg.json
Labels: size/L, adq-patch

#829 Simplify tuneSolverSpecificOptions
  src/solver/utils/ortools_utils.cpp
Labels: size/XS, cleaning

#828 Restore notifications from Sonar
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: size/S

#837 Check how many remaining code smells in Sonar Cloud
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_LHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/localMatchingRuleViolations.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.h
Labels: size/L

#838 Statistics: use std::mutex / std::atomic<> to prevent concurrent writes
  src/libs/antares/benchmarking/file_content.cpp
  src/libs/antares/benchmarking/file_content.h
  src/libs/antares/benchmarking/file_writer.cpp
  src/solver/utils/optimization_statistics.h
Labels: size/L

#817 Add adequacy-patch CSR study format changes
  docs/reference-guide/13-file-format.md
Labels: size/S, doc, adq-patch

#842 Beta 7 Executables for Elia
  src/CMakeLists.txt
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.h
Labels: size/M, adq-patch

#749 Base for BC dual values
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/categories.h
Labels: size/M

#836 doc : new input and output format due to addition of BC marginal prices
  docs/reference-guide/13-file-format.md
Labels: size/S, doc

#846 Fix for beta7
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/optimisation/adequacy_patch.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
Labels: size/S, adq-patch

#847 Implementation of some remaining code smells that can be fixed in CSR branch
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_LHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
Labels: size/S, adq-patch
