Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-12, with the labels that each got.

#973 Remove useless opti flags
  src/cmake/common-settings.cmake
Labels: size/XS

#984 Fix/use ortools 9.2 rte1.7
  .github/workflows/centos7.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  docker/centos7-basic-requirements
  ortools_tag
Labels: size/M

#770 Document option --list-solvers
  docs/reference-guide/10-command_line.md
Labels: size/XS, doc

#989 [FIX] Add condition to avoid null pointer
  src/libs/antares/study/importlogs.cpp
Labels: bug, size/XS, cleaning

#992 Adequacy-patch - beta 11 version
  docs/reference-guide/14-adequacy-patch.md
Labels: size/S

#993 Adequacy-patch - beta 11 version
  docs/reference-guide/14-adequacy-patch.md
Labels: size/M

#990 Remove using namespace std from header files
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/scenario-builder/hydroLevelsData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/scBuilderUtils.cpp
  src/libs/antares/study/scenario-builder/scBuilderUtils.h
  src/libs/antares/study/variable-print-info.cpp
  src/libs/antares/study/variable-print-info.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/tests/src/libs/antares/logs/logs.h
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/cell.h
  src/ui/simulator/toolbox/components/datagrid/renderer/ts-management.h
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
Labels: size/L, cleaning, code

#999 Fix [compile error]
  src/solver/simulation/economy.h
Labels: size/XS

#983 [CI] Updated deprecated actions
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
Labels: size/S, ci

#1004 [FIX] Add var to avoid calling ortools function
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
Labels: bug, size/XS

#1005 Make logs more expressive when checking link values
  src/libs/antares/study/area/links.cpp
Labels: size/S

#986 Case insensitive option for build type
  docs/build/3-Build.md
  src/CMakeLists.txt
Labels: size/S, build

#978 [DEV] Refactored ortools_utils
  src/ext/yuni/src/yuni/core/getopt/option.h
  src/libs/antares/CMakeLists.txt
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/date/date.cpp
  src/libs/antares/study/OrtoolsSolver.cpp
  src/libs/antares/study/OrtoolsSolver.hpp
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/load-options.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/application.cpp
  src/solver/misc/options.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
  src/ui/simulator/windows/simulation/run.cpp
Labels: size/L, cleaning, code, refactoring

#1008 [FIX] Ortools utils code smell
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/load-options.h
Labels: size/XS, cleaning

#1007 [CI] Integrate ortools v9.2-rte2.0
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
Labels: size/M, ci

#1016 Use min gen modulation to compute variable "profit by plant"
  src/solver/variable/economy/profitByPlant.h
Labels: size/XS

#1015 Fix BC MARG COST values in parallel
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/state.h
Labels: size/S

#1026 Merge tag 8.2.3 into develop
  docs/CHANGELOG.md
Labels: size/XS

#1025 Merge 8.3.3 into develop
  docs/CHANGELOG.md
Labels: size/XS

#1020 Remove default implementation for hourEnd (see variable.hxx)
  src/solver/variable/adequacy-draft/ens_cn.h
  src/solver/variable/adequacy-draft/ens_is.h
  src/solver/variable/adequacy-draft/lold_cn.h
  src/solver/variable/adequacy-draft/lold_is.h
  src/solver/variable/adequacy-draft/lolp_cn.h
  src/solver/variable/adequacy-draft/lolp_cn_system.h
  src/solver/variable/adequacy-draft/lolp_is.h
  src/solver/variable/adequacy-draft/lolp_is_system.h
  src/solver/variable/adequacy-draft/maxdepth_cn.h
  src/solver/variable/adequacy-draft/maxdepth_is.h
  src/solver/variable/adequacy-draft/minmarg_cn.h
  src/solver/variable/adequacy-draft/minmarg_is.h
  src/solver/variable/adequacy/overallCost.h
  src/solver/variable/adequacy/spilledEnergy.h
  src/solver/variable/commons/hydro.h
  src/solver/variable/commons/load.h
  src/solver/variable/commons/miscGenMinusRowPSP.h
  src/solver/variable/commons/psp.h
  src/solver/variable/commons/rowBalance.h
  src/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/commons/wind.h
  src/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/economy/balance.h
  src/solver/variable/economy/co2.h
  src/solver/variable/economy/dispatchable-generation-margin.h
  src/solver/variable/economy/dispatchableGeneration.h
  src/solver/variable/economy/domesticUnsuppliedEnergy.h
  src/solver/variable/economy/hydroCost.h
  src/solver/variable/economy/hydrostorage.h
  src/solver/variable/economy/inflow.h
  src/solver/variable/economy/links/congestionFee.h
  src/solver/variable/economy/links/congestionFeeAbs.h
  src/solver/variable/economy/links/congestionProbability.h
  src/solver/variable/economy/links/flowLinear.h
  src/solver/variable/economy/links/flowLinearAbs.h
  src/solver/variable/economy/links/flowQuad.h
  src/solver/variable/economy/links/hurdleCosts.h
  src/solver/variable/economy/links/loopFlow.h
  src/solver/variable/economy/links/marginalCost.h
  src/solver/variable/economy/lold.h
  src/solver/variable/economy/lolp.h
  src/solver/variable/economy/max-mrg.h
  src/solver/variable/economy/nbOfDispatchedUnits.h
  src/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/economy/nonProportionalCost.h
  src/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/economy/operatingCost.h
  src/solver/variable/economy/overallCost.h
  src/solver/variable/economy/overflow.h
  src/solver/variable/economy/price.h
  src/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/economy/pumping.h
  src/solver/variable/economy/renewableGeneration.h
  src/solver/variable/economy/reservoirlevel.h
  src/solver/variable/economy/spilledEnergy.h
  src/solver/variable/economy/unsupliedEnergy.h
  src/solver/variable/economy/waterValue.h
Labels: size/L, cleaning, code

#1028 Fix empty CMAKE_BUILD_TYPE
  src/CMakeLists.txt
Labels: bug, size/XS, build

#1029 Remove status bar count
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/application/main/statusbar.cpp
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/datagrid/dbgrid.cpp
  src/ui/simulator/toolbox/components/datagrid/selectionoperation.h
Labels: size/XL, GUI, cleaning

#1034 Match "issue-*" in branch names
  .github/workflows/branchNameValidation.yml
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS, ci

#1037 Fix variable type
  src/solver/utils/mps_utils.cpp
Labels: size/S

#1038 Feature/mps writer minor improvements
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
Labels: size/M

#1035 Introduce missing MPS comparison tests
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/tests/CMakeLists.txt
  src/tests/mps/025_mps.txz
  src/tests/mps/conftest.py
  src/tests/mps/test_mps.py
Labels: size/M

#1039 Restore failures in GH actions
  .github/workflows/run-tests/action.yml
  simtest.json
Labels: bug, size/XS, ci

#1042 De-duplicate OPT_Export_add_variable by using `std::optional<int>`
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
Labels: size/M

#1040 Refactor : about optimization number
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
Labels: size/M, refactoring

#1032 Refactor : move current year and week from study to weekly optimization problem
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
  src/solver/utils/filename.cpp
  src/solver/utils/filename.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
Labels: size/L, refactoring

#1043 Use std::vector<bool> for yearsFilter
  src/libs/antares/study/memory-usage.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/study.cpp
  src/solver/simulation/solver.hxx
  src/ui/simulator/toolbox/components/datagrid/renderer/mc-playlist.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.cpp
Labels: size/M

#1045 Fix MPS tests on Windows
  .github/workflows/windows-vcpkg.yml
  src/tests/mps/test_mps.py
Labels: size/S
