Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2022-01, with the labels that each got.

#493 Remove callback for balance retrieval
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/M

#487 Add test studies
  src/tests/CMakeLists.txt
  src/tests/examples/output_compare_test.py
Labels: size/S

#473 Use average hourly NTC values for quadratic optimization
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/L

#503 [sonar] Use factory method for cells to fix "blocker" code smell
  src/ui/simulator/toolbox/components/datagrid/renderer/column.cpp
Labels: PR: waiting for review, size/M

#499 Scenario builder ntc : use UI runtime
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/ui-runtimeinfos.cpp
  src/libs/antares/study/ui-runtimeinfos.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-load-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-load-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renewable-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renewable-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-solar-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-solar-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-thermal-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-thermal-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-wind-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-wind-renderer.h
  src/ui/simulator/toolbox/components/map/nodes/connection.cpp
  src/ui/simulator/toolbox/components/map/tools/remover.cpp
Labels: size/L, GUI

#498 GUI - adding an NTC column in "Time-Series Management" panel
  src/ui/simulator/toolbox/components/datagrid/renderer/cell.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/cell.h
  src/ui/simulator/toolbox/components/datagrid/renderer/column.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/column.h
  src/ui/simulator/toolbox/components/datagrid/renderer/ts-management-aggregated-as-renewables.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/ts-management-clusters-as-renewables.cpp
Labels: PR: waiting for review, size/L, GUI

#502 Do not try to de-allocate global arrays if they were not allocated
  src/solver/CMakeLists.txt
  src/solver/exceptions.h
  src/solver/main.cpp
  src/solver/main.h
Labels: bug, size/M

#497 GUI : scenario builder for links NTC
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/ui-runtimeinfos.cpp
  src/libs/antares/study/ui-runtimeinfos.h
  src/ui/simulator/application/main/build/scenario-builder.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-load-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-load-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renewable-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renewable-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-solar-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-solar-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-thermal-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-thermal-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-wind-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-wind-renderer.h
  src/ui/simulator/toolbox/components/map/nodes/connection.cpp
  src/ui/simulator/toolbox/components/map/tools/remover.cpp
Labels: size/XL, GUI

#500 Remove clusterIndexMap and linksIndexMap, make Matrix<>'s move operations noexcept
  src/libs/antares/array/matrix.h
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.h
  src/libs/antares/study/scenario-builder/rules.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
Labels: question, PR: waiting for review, size/L, code

#496 GUI - links and NTC time series
  src/libs/antares/CMakeLists.txt
  src/libs/antares/memory/new_check.hxx
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/components/datagrid/component.cpp
  src/ui/simulator/toolbox/components/datagrid/component.h
  src/ui/simulator/toolbox/components/datagrid/dbgrid.cpp
  src/ui/simulator/toolbox/components/datagrid/dbgrid.h
  src/ui/simulator/toolbox/components/datagrid/renderer/column.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.h
  src/ui/simulator/windows/connection.cpp
  src/ui/simulator/windows/connection.h
  src/ui/simulator/windows/constraints-builder/constraintsbuilder.cpp
  src/ui/simulator/windows/hydro/levelsandvalues.cpp
Labels: PR: waiting for review, size/XL, GUI

#508 Add option --exclude to study cleaner
  src/libs/antares/study/cleaner.h
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/cleaner/cleaner.cpp
  src/libs/antares/study/ui-runtimeinfos.cpp
  src/tools/cleaner/main.cpp
Labels: size/M, feature

#522 Do not write debug logs after log objects have been destroyed
  src/libs/antares/study/study.cpp
Labels: bug, size/XS

#511 Add "view results" button and function
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/application/main/refresh.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/toolbox/create.h
  src/ui/simulator/toolbox/create.hxx
  src/ui/simulator/windows/message.cpp
  src/ui/simulator/windows/message.h
  src/ui/simulator/windows/message.hxx
Labels: enhancement, size/M, GUI

#527 Remove unused setjmp/CompteRendu
  src/solver/hydro/daily/h2o_j_sys.h
  src/solver/hydro/monthly/h2o_m_sys.h
  src/solver/main.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/sim_variables_globales.cpp
Labels: size/M, cleaning, code

#531 Prevent an area from having a link to itself
  src/libs/antares/study/area/links.cpp
Labels: PR: waiting for review, size/XS

#509 Help menu : add "Online documentation" item
  src/CMakeLists.txt
  src/config.h.cmake
  src/ui/simulator/application/main/help.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
Labels: size/S, GUI

#468 UI: Change and rename "upstream/downstream" view
  src/ui/simulator/toolbox/input/connection.cpp
Labels: enhancement, PR: waiting for review, size/M, GUI

#505 Remove calls to exit()
  src/libs/antares/sys/policy.cpp
  src/solver/main.cpp
  src/solver/misc/options.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/ts-generator/xcast/xcast.cpp
  src/tools/yby-aggregator/main.cpp
  src/ui/simulator/application/application.cpp
Labels: size/M
