Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-02, with the labels that each got.

#1138 Fix RPATH for solver-only asset
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
Labels: bug, size/S

#1139 Fix compilation warnings related to newly-introduced post-processing mechanism
  src/solver/optimisation/post_process_commands.cpp
Labels: size/S, cleaning, code

#1146 Remove memset for PROBLEME_HEBDO, de-couple MPS writer a bit
  src/solver/cmake/simulation.cmake
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_constants.h
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_constants.h
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/simulation.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
Labels: size/L, cleaning, code

#1149 Remove unused MPS sources & global variable
  src/solver/CMakeLists.txt
  src/solver/mps/mps_define.h
  src/solver/mps/mps_extern_global.h
  src/solver/mps/mps_global.c
Labels: size/L, cleaning, code

#1143 Remove default implementation for `hourEnd`
  src/solver/variable/economy/dtgMarginAfterCsr.h
  src/solver/variable/economy/localMatchingRuleViolations.h
  src/solver/variable/economy/spilledEnergyAfterCSR.h
Labels: size/S, cleaning, code

#1160 replaced g++11 by g++17 in common-settings.cmake
  src/cmake/common-settings.cmake
Labels: size/XS

#1141 Use dedicated structure to test if CSR was triggered for area, hour
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  src/solver/cmake/simulation.cmake
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/count_constraints_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/adequacy_patch_runtime_data.cpp
  src/solver/simulation/adequacy_patch_runtime_data.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, adq-patch

#1165 Fix missing header from CMake, fix indentation
  src/solver/cmake/solver.cmake
Labels: size/XS

#1157 Fix link path error in Kirchhoff constraint builder
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/create.cpp
  src/tests/kirchhoff-cbuilder/reference.tar.gz
Labels: bug, size/M, GUI, cleaning

#1155 Add coefficient for hurdle cost in the CSR problem
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/simulation/adequacy_patch_runtime_data.cpp
  src/solver/simulation/adequacy_patch_runtime_data.h
Labels: size/M, adq-patch

#1156 Add scale coef for hurdle costs + fix broken latex
  docs/reference-guide/05-output_files.md
  docs/reference-guide/14-adequacy-patch.md
Labels: size/S, doc

#1168 Release 8.5.0
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  docs/CHANGELOG.md
  docs/reference-guide/14-adequacy-patch.md
  src/CMakeLists.txt
Labels: size/M

#1170 Fix file format for v8.4.0
  docs/reference-guide/13-file-format.md
Labels: size/S, doc

#1057 [DEV] Ini files load encapsulation
  src/libs/antares/study/load.cpp
  src/libs/antares/study/study.h
Labels: size/L

#1178 Add a few const qualifiers
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/optimisation/post_process_commands.h
Labels: size/S, cleaning, code, adq-patch

#1154 adq patch : refactor parameters management
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/solver/application.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
Labels: size/XL, adq-patch, refactoring

#1174 Doc correction on LOLP definition
  docs/reference-guide/05-output_files.md
Labels: size/XS, doc
