Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-06, with the labels that each got.

#1327 Changelog for v8.6.0-rc7
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#1306 Performance metrics
  .gitignore
  src/tests/benchmark/benchmark.py
  src/tests/benchmark/studiesToBenchmark.json
Labels: enhancement, size/L, ci, performance

#1326 Fix empty matrices when providing sc-builder data for BCs
  src/libs/antares/study/runtime/runtime.cpp
Labels: size/XS

#1335 Simplify code a bit by adding a template specialization
  src/libs/antares/inifile/inifile.h
  src/libs/antares/inifile/inifile.hxx
  src/libs/antares/study/parts/short-term-storage/properties.cpp
Labels: size/S

#1330 Fix erroneous error message with ST storages
  src/libs/antares/study/area/list.cpp
Labels: bug, size/XS

#1331 Saving short term storage
  src/libs/antares/inifile/inifile.h
  src/libs/antares/inifile/inifile.hxx
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
Labels: size/L, feature, code, Short term storage

#1336 [sc-builder] Don't draw BC timeseries number if only one TS
  src/solver/simulation/timeseries-numbers.cpp
Labels: bug, size/S

#1346 [FIX] Change sts save order
  src/libs/antares/study/parts/short-term-storage/properties.cpp
Labels: cleaning, Short term storage

#1345 ST storage : correcting the hourly constraint on levels
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Labels: enhancement, size/S, Short term storage

#1349 INI file written manually for unserved/spilled energy
  src/libs/antares/study/area/list.cpp
Labels: size/S, cleaning

#1332 Add spread on ST storage objects
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/sim_spread_generator.cpp
  src/solver/simulation/sim_spread_generator.h
Labels: size/L

#1350 Remove group{Min,Max}Count, annuityInvestment in thermal clusters
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
Labels: size/M, cleaning

#1355 Add emergency shutdown if hydro mingen problem
  src/solver/hydro/management/management.cpp
Labels: bug, size/S, cleaning

#1354 GUI : adapt logs reading from GUI
  src/ui/simulator/toolbox/jobs/job.cpp
  src/ui/simulator/windows/studylogs.cpp
Labels: bug, size/S, GUI

#1341 Oracle Linux 8
  .github/workflows/oracle8.yml
Labels: size/L, ci

#1359 Updater : log error when loading the study fails
  src/tools/updater/main.cpp
Labels: enhancement, size/XS

#1357 Fix pmax / mingen checks, cleaning
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/max-mrg.cpp
Labels: size/M

#1329 Prepare release v8.6.0
  docs/CHANGELOG.md
  simtest.json
  src/CMakeLists.txt
Labels: size/M

#1363 Replace memalloc by new delete
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
Labels: size/XL, cleaning

#1351 Clean submodules
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  .gitmodules
  src/distrib/CMakeLists.txt.in
  src/distrib/win32/NSIS.template.in
  src/distrib/win32/examplesfiles.inc.nsh
  src/distrib/win32/uninstall-folders.inc.nsh
Labels: size/M, cleaning, ci

#1368 Feature/thermal price definition cr20 rtei
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/parts/thermal/ecoInput.hxx
  src/libs/antares/study/parts/thermal/prepro.cpp
Labels: size/M

#1369 Roll loop in correlation.cpp
  src/libs/antares/array/correlation.cpp
Labels: size/S, code quality

#1272 Thermal price definition (RTEi's -> CR20)
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/13-file-format.md
  src/libs/antares/CMakeLists.txt
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/action/handler/antares-study/area/ts-node.cpp
  src/libs/antares/study/estimate.memory-footprint.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster.hxx
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/solver/application.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/state.cpp
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalmodulation.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/constants.cpp
  src/ui/simulator/windows/inspector/constants.h
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/thermal/panel.cpp
  src/ui/simulator/windows/thermal/panel.h
Labels: size/XL, RTE-i

#1371 More precise submodule init for centos deps
  .github/workflows/centos7-system-deps-build.yml
Labels: size/XS, ci

#1373 Final reservoir level cr25 rtei dev - sonar cloud smells
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/parts/hydro/container.h
  src/libs/antares/study/scenario-builder/hydroLevelsData.cpp
  src/libs/antares/study/scenario-builder/hydroLevelsData.h
  src/solver/hydro/management/management.cpp
  src/solver/simulation/apply-scenario.cpp
  src/solver/simulation/hydro-final-reservoir-level-functions.cpp
  src/solver/simulation/hydro-final-reservoir-level-functions.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-levels-renderer.cpp
Labels: size/L

#1372 Disable store in input for Stochastic time series when not at latest version
  src/libs/antares/study/load.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.importprepro.cpp
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/ui/simulator/toolbox/components/datagrid/renderer/cell.cpp
Labels: size/M

#1377 Fix cost for short-term storage variables
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
Labels: size/S

#1378 Identify BindingConstraintsList as a repository and rename it
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.hxx
  src/libs/antares/study/fwd.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/libs/antares/study/study.h
  src/solver/simulation/BindingConstraintsTimeSeriesNumbersWriter.h
  src/solver/simulation/ITimeSeriesNumbersWriter.h
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/bindingconstraint.cpp
  src/ui/simulator/toolbox/input/bindingconstraint/bindingconstraint.cpp
Labels: size/L

#1379 Add tests about v860
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
Labels: size/S, tests

#1374 Remove cycle property for short-term storage
  docs/CHANGELOG.md
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
Labels: size/S, Short term storage

#1358 Remove binding constraintsRTI
  src/CMakeLists.txt
  src/libs/antares/CMakeLists.txt
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/study/action/context.h
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/binding_constraint/BindingConstraintStructures.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/libs/antares/study/ui-runtimeinfos.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/bindConstraints.hxx
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/ui/simulator/toolbox/components/map/manager.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/windows/inspector/data.h
  src/ui/simulator/windows/inspector/inspector.cpp
  src/ui/simulator/windows/inspector/inspector.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XL

#1383 Fix/v861
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  docs/CHANGELOG.md
  simtest.json
  src/CMakeLists.txt
Labels: size/S
