Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-03, with the labels that each got.

#1161 [CLEAN] src/solver/optimisation
  src/libs/antares/study/parts/thermal/cluster.h
  src/solver/application.cpp
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_chainage_intercos.cpp
  src/solver/optimisation/opt_constants.h
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_outils.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_pmax.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_numero_de_jour_du_pas_de_temps.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/optimisation/optim_post_process_list.cpp
  src/solver/optimisation/optim_post_process_list.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/state.cpp
Labels: size/XXL, cleaning, code

#1088 [CI] Don't generate PDF doc unless necessary
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/distrib/win32/NSIS.template.in
  src/distrib/win32/sourcefiles.inc.nsh
Labels: size/M, doc, ci

#1188 [CLEAN] Remove OUI_ANTARES NON_ANTARES
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_constants.h
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_adequation.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_constants.h
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/XL, cleaning, code

#1184 Pollutant emissions in thermal clusters
  docs/reference-guide/05-output_files.md
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/pollutant.cpp
  src/libs/antares/study/parts/thermal/pollutant.h
  src/solver/cmake/variable.cmake
  src/solver/variable/adequacy/all.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/thermalAirPollutantEmissions.h
  src/solver/variable/surveyresults/surveyresults.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermal.areasummary.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XL, feature

#1193 Use enum values as template parameters in variable.hxx
  src/solver/variable/variable.hxx
Labels: size/S, cleaning, code

#1199 Remove parameter Link Type
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/ui/simulator/windows/options/optimization/optimization.cpp
Labels: size/L, GUI, cleaning

#1180 max nb columns for print : more cleaning
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/variable-print-info.cpp
  src/libs/antares/study/variable-print-info.h
  src/solver/variable/area.inc.hxx
  src/solver/variable/bindConstraints.hxx
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/surveyresults/surveyresults.cpp
  src/solver/variable/surveyresults/surveyresults.h
  src/solver/variable/variable.hxx
  src/ui/simulator/toolbox/components/datagrid/renderer/select-variables.cpp
  src/ui/simulator/windows/options/select-output/select-output.cpp
Labels: size/L

#1204 Add missing sirius_solver dependency
  src/solver/utils/CMakeLists.txt
Labels: size/XS, build

#1208 Short term storage : hour for clusters functions
  src/solver/variable/CMakeLists.txt
  src/solver/variable/adequacy/overallCost.h
  src/solver/variable/area.h
  src/solver/variable/area.inc.hxx
  src/solver/variable/commons/join.h
  src/solver/variable/commons/links/links.h.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/container.h
  src/solver/variable/container.hxx
  src/solver/variable/economy/dispatchable-generation-margin.h
  src/solver/variable/economy/dispatchableGeneration.h
  src/solver/variable/economy/hydroCost.h
  src/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/economy/nonProportionalCost.h
  src/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/economy/operatingCost.h
  src/solver/variable/economy/overallCost.h
  src/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/economy/renewableGeneration.h
  src/solver/variable/economy/thermalAirPollutantEmissions.h
  src/solver/variable/endoflist.h
  src/solver/variable/setofareas.h
  src/solver/variable/setofareas.hxx
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/variable.h
  src/solver/variable/variable.hxx
  src/tests/run-study-tests/check_on_results/output_compare.py
Labels: size/L, feature, Short term storage

#1223 Inject simulation results into output variable writer
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/solver/variable/economy/shortTermStorage.h
  src/solver/variable/economy/shortTermStorageLevels.h
Labels: size/L, Short term storage

#1224 Fix absence of allocation for `PMinOfClusters`
  src/solver/variable/state.cpp
Labels: size/XS

#1217 ST storage output : adding ST storage output variables
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/solver/variable/CMakeLists.txt
  src/solver/variable/economy/all.h
  src/solver/variable/economy/shortTermStorage.h
  src/solver/variable/economy/shortTermStorageLevels.h
  src/solver/variable/variable.h
  src/solver/variable/variable.hxx
Labels: size/XL, Short term storage

#1201 Optimization for short term storage
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parts/short-term-storage/series.h
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/commons/links/links.hxx.inc.hxx
Labels: size/L, Short term storage

#1222 [DOC] Add I/O for pollutant in doc
  docs/reference-guide/13-file-format.md
Labels: size/XS, doc

#1158 Tune XPRESS resolution
  src/solver/utils/ortools_utils.cpp
Labels: size/S, performance

#1228 Loading Series for short term storage
  src/libs/antares/array/matrix.hxx
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.h
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/L, code, Short term storage

#1159 Max number of columns in an output file
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/variable-print-info.cpp
  src/libs/antares/study/variable-print-info.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/solver.hxx
  src/solver/variable/area.inc.hxx
  src/solver/variable/bindConstraints.hxx
  src/solver/variable/commons/links/links.h.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/container.hxx
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/endoflist.h
  src/solver/variable/surveyresults/surveyresults.cpp
  src/solver/variable/surveyresults/surveyresults.h
  src/solver/variable/variable.h
  src/solver/variable/variable.hxx
  src/ui/simulator/toolbox/components/datagrid/renderer/select-variables.cpp
  src/ui/simulator/windows/options/select-output/select-output.cpp
Labels: enhancement, size/XL, cleaning

#1233 [CI] Add separate doc gen to build steps in centos
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  src/distrib/win32/NSIS.template.in
  src/distrib/win32/sourcefiles.inc.nsh
  src/distrib/win32/uninstall-folders.inc.nsh
  src/ui/simulator/application/main/help.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
Labels: size/M, ci

#1237 Use `shared_ptr` instead of raw pointer
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, Short term storage, code quality

#1240 Use HOURS_PER_YEAR from antares/constants.h
  src/libs/antares/study/parts/short-term-storage/series.cpp
Labels: size/S, Short term storage, code quality

#1231 8.6.0-rc1
  .github/workflows/build-userguide.yml
  .github/workflows/generate-userguide-pdf/action.yml
  .github/workflows/windows-release.yml
  docs/CHANGELOG.md
  docs/pdf-doc-generation-with-sphinx/create_pdf_doc.sh
  docs/pdf-doc-generation-with-sphinx/source/conf.py
  sonar-project.properties
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/tests/CMakeLists.txt
Labels: size/L

#1242 Code smells for short term storage
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.h
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/commons/links/links.h.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/endoflist.h
Labels: size/M, cleaning, Short term storage

#1236 Unit testing for short term storage loading
  src/libs/antares/array/array1d.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.h
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
Labels: size/L, tests, Short term storage
