Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-11, with the labels that each got.

#1735 Remove obsolete scripts
  src/cmake_clean.sh
  src/script_compilation
Labels: size/S, cleaning

#1738 Silence compile warning for unused function args
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/economy.cpp
Labels: size/S, cleaning

#1740 CR23 Modification : Unit tests refactoring
  src/tests/src/libs/antares/study/parts/hydro/CMakeLists.txt
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-series.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydroreader-class.cpp
Labels: size/M, refactoring, RTE-i

#1716 Add check in unfeasible analyzer: unit tests
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/solver/infeasible-problem-analysis/constraint-slack-analysis.h
  src/solver/infeasible-problem-analysis/unfeasibility-analysis.h
  src/solver/infeasible-problem-analysis/unfeasible-pb-analyzer.h
  src/solver/infeasible-problem-analysis/variables-bounds-consistency.h
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/L

#1717 print solver logs
  docs/CHANGELOG.md
  docs/reference-guide/10-command_line.md
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/load-options.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/misc/options.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
Labels: size/M

#1730 Refactor numspace use in hydro solver
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/simulation.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
Labels: size/L, code quality

#1747 Mismatch print
  src/libs/antares/study/parameters.cpp
Labels: size/XS

#1736 Use ccache in windows CI
  .github/workflows/windows-vcpkg.yml
  src/cmake/common-settings.cmake
Labels: size/S

#1744 Fix oraclelinux minizip build + actually run zip unit tests
  .github/workflows/oracle8.yml
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/concurrency/CMakeLists.txt
  src/tests/src/libs/antares/writer/CMakeLists.txt
Labels: size/XS

#1694 Document build for debian 12, Ubuntu 22.04 and Ubuntu 23.04
  docs/build/1-Development-requirements.md
  docs/build/2-Dependencies-install.md
  docs/build/3-Build.md
  docs/build/5-Installer-creation.md
  docs/build/continuous-integration.md
  src/CMakeLists.txt
Labels: doc, build

#1755 Avoid unnecessary copy in profitByPlant.h
  src/solver/variable/economy/profitByPlant.h
Labels: size/XS, code quality

#1757 Allow yearJob to be non-copyable
  src/libs/antares/concurrency/include/antares/concurrency/concurrency.h
  src/solver/simulation/solver.hxx
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
Labels: size/M

#1763 Remove helper class PairOfIntegers
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/parts/hydro/pair-of-integers.cpp
  src/libs/antares/study/parts/hydro/pair-of-integers.h
  src/libs/antares/study/parts/hydro/series.cpp
Labels: size/M

#1750 HydroMaxReader class refactor
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.h
  src/tests/src/libs/antares/study/parts/hydro/test-hydroreader-class.cpp
Labels: size/M

#1768 Fix a few compilation warnings emitted by g++-13
  src/ext/yuni/src/yuni/thread/thread.cpp
  src/libs/antares/object/object.h
  src/libs/antares/object/object.hxx
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
Labels: size/XS, code quality

#1776 Fix clang warnings
  src/ext/yuni/src/yuni/core/logs/handler/file.hxx
  src/ext/yuni/src/yuni/core/logs/handler/stdcout.h
  src/ext/yuni/src/yuni/core/nullable/extension.hxx
  src/ext/yuni/src/yuni/core/nullable/nullable.hxx
  src/libs/antares/array/antares/array/matrix-to-buffer.h
  src/libs/antares/array/antares/array/matrix.hxx
  src/libs/antares/benchmarking/include/antares/benchmarking/DurationCollector.h
  src/libs/antares/object/intrusive-reference.hxx
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.h
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.h
  src/solver/application.h
  src/solver/constraints-builder/grid.hxx
  src/solver/simulation/BindingConstraintsTimeSeriesNumbersWriter.h
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.h
  src/solver/simulation/solver.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/utils/mps_utils.h
  src/solver/utils/name_translator.h
  src/solver/utils/named_problem.cpp
  src/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/endoflist.h
  src/solver/variable/info.h
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
  src/ui/common/component/frame/local-frame.h
  src/ui/simulator/toolbox/components/button/button.h
Labels: size/L

#1767 Fix output variable profit
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/profitByPlant.h
Labels: bug, size/XS

#1569 Named MPS - fix duplicated "ranged" binding constraints
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/binding_constraint/BindingConstraintLoader.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
Labels: bug, size/S

#1769 Allow absence of group attribute for binding constraints
  src/libs/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/binding_constraint/BindingConstraintLoader.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintSaver.cpp
Labels: size/S

#1779 Release/8.8.x
  docs/CHANGELOG.md
  docs/pdf-doc-generation-with-sphinx/source/conf.py
  docs/reference-guide/13-file-format.md
  sonar-project.properties
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
Labels: size/L

#1721 Refactor link series
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/economy/links/congestionProbability.h
  src/ui/action/handler/antares-study/link/ntc.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
Labels: size/L, cleaning, code quality

#1778 Take variable status (integer/continuous) into account for MILP
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
Labels: bug, size/M

#1783 Fix E2E tests, add valid-870 to usual E2E tests
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
Labels: size/S

#1797 Remove Yuni::Atomic
  src/libs/antares/object/object.h
  src/libs/antares/study/progression/progression.h
  src/libs/fswalker/fswalker.cpp
  src/libs/fswalker/job.h
  src/tools/vacuum/io.cpp
  src/tools/vacuum/io.h
  src/tools/yby-aggregator/job.cpp
  src/tools/yby-aggregator/output.h
  src/tools/yby-aggregator/progress.cpp
  src/tools/yby-aggregator/progress.h
  src/ui/common/lock.cpp
  src/ui/simulator/application/main/logs.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/toolbox/execute/execute.cpp
  src/ui/simulator/toolbox/ext-source/performer.h
  src/ui/simulator/toolbox/jobs/job.h
  src/ui/simulator/windows/output/panel/area-link.cpp
  src/ui/simulator/windows/output/panel/panel.cpp
  src/ui/simulator/windows/output/panel/panel.h
Labels: size/M, cleaning
