Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-07, with the labels that each got.

#1318 Use std::vectory instead of malloc in solver allocation
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/count_constraints_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.h
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_constants.h
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_pmax.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
  src/solver/variable/adequacy/overallCost.h
  src/solver/variable/economy/balance.h
  src/solver/variable/economy/inflow.h
  src/solver/variable/economy/links/congestionFee.h
  src/solver/variable/economy/links/congestionFeeAbs.h
  src/solver/variable/economy/links/congestionProbability.h
  src/solver/variable/economy/links/flowLinear.h
  src/solver/variable/economy/links/flowLinearAbs.h
  src/solver/variable/economy/links/hurdleCosts.h
  src/solver/variable/economy/links/marginalCost.h
  src/solver/variable/economy/max-mrg.cpp
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/XXL, cleaning, code quality, hot

#1362 Document recently added output variables
  docs/reference-guide/15-output-variables.md
Labels: size/S, doc

#1392 Fixing test valid-v860/tests-ST-storage
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
Labels: bug, size/XS, tests, ci

#1396 [DOC] Fix typo for inflows.txt file
  docs/reference-guide/13-file-format.md
Labels: size/XS, doc

#1397 Remove data panels for binding constraints, display message instead
  src/ui/simulator/windows/bindingconstraint/bindingconstraint.cpp
  src/ui/simulator/windows/bindingconstraint/bindingconstraint.h
Labels: size/L, GUI

#1365 BC scenarisation : Refactor end to end tests
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/solver/misc/options.h
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/CMakeLists.txt
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/tests/src/libs/antares/study/constraint/CMakeLists.txt
Labels: size/XL, code quality

#1393 Memory allocation, use std::vector
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/application.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/sim_structure_probleme_adequation.h
  src/solver/simulation/sim_variables_globales.cpp
  src/solver/simulation/simulation.h
  src/solver/variable/commons/hydro.h
  src/solver/variable/commons/load.h
  src/solver/variable/commons/solar.h
  src/solver/variable/commons/wind.h
  src/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/economy/links/flowQuad.h
  src/solver/variable/state.hxx
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/utils/utils.cpp
Labels: size/L, cleaning, code quality

#1411 Update version number & changelog for 8.7.0-beta1
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#1414 Set beta=2, update changelog
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/XS

#1417 Fix MPS differences related to int/unsigned surprises
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
Labels: size/S

#1419 Prepare v8.7.0-beta3
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#1420 Run tests nightly (Ubuntu only for now)
  .github/workflows/ubuntu.yml
Labels: size/S, ci

#1404 implement --mps-export option
  src/libs/antares/study/parameters.cpp
Labels: size/XS

#1421 Fix build for Oracle Linux 8, build on push
  .github/workflows/oracle8.yml
  docker/oraclelinux
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
Labels: size/M

#1410 Array, logs jit and correlation in makefile
  src/ext/yuni/src/yuni/core/fwd.h
  src/libs/antares/CMakeLists.txt
  src/libs/antares/array/CMakeLists.txt
  src/libs/antares/array/matrix.cpp
  src/libs/antares/array/matrix.hxx
  src/libs/antares/correlation/CMakeLists.txt
  src/libs/antares/correlation/correlation.cpp
  src/libs/antares/correlation/correlation.h
  src/libs/antares/correlation/correlation.hxx
  src/libs/antares/jit/CMakeLists.txt
  src/libs/antares/jit/jit.h
  src/libs/antares/jit/jit.hxx
  src/libs/antares/logs/CMakeLists.txt
  src/libs/antares/logs/logs.cpp
  src/libs/antares/study/load.cpp
  src/libs/antares/study/save.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/ts-generator/xcast/studydata.h
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/solver/optimisation/CMakeLists.txt
  src/tools/config/CMakeLists.txt
  src/tools/vacuum/CMakeLists.txt
  src/ui/simulator/CMakeLists.txt
  src/ui/simulator/windows/correlation/correlation.cpp
Labels: size/L

#1409 Named MPS: factorize variable & constraint namers
  src/solver/optimisation/opt_rename_problem.cpp
  src/solver/optimisation/opt_rename_problem.h
Labels: size/L, code quality

#1412 reducing code smells
  src/libs/antares/study/binding_constraint/BindingConstraintLoader.cpp
  src/solver/simulation/sim_spread_generator.h
Labels: size/XS, code quality

#1426 Add cluster name for 6 constraints associated to unit-commitment = accurate
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_rename_problem.cpp
  src/solver/optimisation/opt_rename_problem.h
Labels: enhancement, size/L

#1402 Memory allocation, use std::vector
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
Labels: size/L, cleaning, code quality

#1438 Oracle assets have proper name
  .github/workflows/oracle8.yml
  docker/oraclelinux
Labels: size/S

#1443 Fix size for assign / resize
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
Labels: bug, size/M

#1445 Avoid copies using `std::move` in `BindingConstraintsRepository::enabled`
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
Labels: size/XS

#1448 Use local index for thermal cluster instead of global one
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
Labels: bug, size/S

#1440 Remove two useless static functions
  src/solver/utils/ortools_utils.cpp
Labels: size/M, cleaning

#1441 Fix segfault, add skipped to enabled constraints
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
Labels: bug, size/XS

#1433 Update antares-deps tag in .gitmodules
  .gitmodules
Labels: size/XS

#1442 Don't build tools (study-updater, etc.) by default
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  src/CMakeLists.txt
  src/tests/CMakeLists.txt
Labels: size/S, build

#1450 Clarify logs & code in case of "failed year"
  src/solver/simulation/solver.hxx
Labels: size/S, code quality

#1453 Prepare 8.7.0-rc1
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/M

#1452 Improve clarity for constraints that should be used
  src/libs/antares/benchmarking/info_collectors.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/binding_constraint/BindingConstraint.hxx
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.hxx
  src/libs/antares/study/runtime/runtime.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/bc.memory-estimation.inc.hxx
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
Labels: size/L

#1455 Fix possible values for ST storage groups
  docs/reference-guide/13-file-format.md
Labels: size/XS, doc

#1456 Fix error when fetching Antares_test submodule
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .gitmodules
Labels: size/XS, ci

#1462 Fix invalid study after update to v8.7.0 - Add default group to existing BCs
  src/libs/antares/study/binding_constraint/BindingConstraintLoader.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintSaver.cpp
Labels: size/XS

#1432 Memory allocation for ProblemeAResoudre, use std::vector
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.h
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_outils.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
Labels: size/L, cleaning, code quality

#1468 Memory leaks
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/ts-generator/xcast/xcast.cpp
Labels: size/S, cleaning, code quality
