Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-01, with the labels that each got.

#922 [TEST] Remove free functions for areas' mem allocation
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/ui/simulator/application/main/constraintsbuilder.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/toolbox/ext-source/handler/com.rte-france.antares.study.cpp
Labels: work in progress, size/L, tests, refactoring

#892 No or empty generaldata.ini
  src/libs/antares/study/memory-usage.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/study.cpp
  src/solver/simulation/solver.hxx
  src/tests/end-to-end/simple-study.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/mc-playlist.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renderer-base.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/L

#1047 Remove unused `ContrainteDeReserveJMoins1ParZone`, `NumeroDeVariableDefaillanceEnReserve`
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/L, cleaning

#1050 Fix build for Kirchhoff constraint builder
  src/tools/kirchhoff-cbuilder/main.cpp
Labels: size/XS

#669 Fix memory leaks
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/libs/antares/study/parts/thermal/prepro.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/utils/ortools_utils.cpp
Labels: size/M, code

#1049 Extract code related to spilled energy bounds
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Labels: size/L, cleaning, code

#1046 Restore area-1-1.txt, interco-1-1.txt, variables-Y-W.txt
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_optimisation_lineaire.cpp
Labels: size/L

#1048 Remove dead code associated to debug
  src/solver/simulation/solver.hxx
Labels: size/M, cleaning, code

#1054 Simplify code for adq patch (Local matching)
  src/libs/antares/study/fwd.h
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
Labels: size/L, cleaning, code, adq-patch

#976 [CI] Generating a solver asset/artifact
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M

#1044 Fix output overwrite when using zip output
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/study/load.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/application.cpp
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/output-folder/CMakeLists.txt
  src/tests/src/libs/antares/study/output-folder/study.cpp
Labels: size/L

#1011 [UI] Allow more than 100 thermal clusters
  src/ui/simulator/windows/inspector/property.cluster.update.cpp
Labels: size/S, GUI

#1030 Refactor export structure
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/cmake/solver.cmake
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_period_string_generator_base.h
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.hxx
  src/solver/utils/filename.cpp
  src/solver/utils/filename.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/solver/utils/opt_period_string_generator.cpp
  src/solver/utils/opt_period_string_generator.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
  src/tests/CMakeLists.txt
  src/tests/mps/025_mps-day.txz
  src/tests/mps/025_mps-week.txz
  src/tests/mps/025_mps.txz
  src/tests/mps/conftest.py
  src/tests/mps/test_mps.py
  src/ui/simulator/windows/options/optimization/optimization.cpp
Labels: size/XL, refactoring

#1063 Fix broken build after merge
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Labels: size/XS

#1080 Fix solver artifact name
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS, ci

#1064 Release 8.4.2
  docs/CHANGELOG.md
  sonar-project.properties
  src/CMakeLists.txt
Labels: size/M

#1056 Use BOOST_CHECK_EQUAL to check equality
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/M, tests, adq-patch

#962 Adequacy patch refactoring
  docs/reference-guide/03-commands.md
  src/CMakeLists.txt
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
Labels: size/L, adq-patch

#964 Refactor adq patch (part 2)
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/container.h
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-dispatchable-margin.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/simulation.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
Labels: size/L, adq-patch

#968 Adequacy patch : refactor economy (weekly optimization)
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch.cpp
  src/solver/optimisation/adequacy_patch.h
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/L, adq-patch

#1092 [FIX] Remove src/libs/antares/study/equipments/equipments.h/hxx
  src/libs/antares/study/equipments/equipments.h
  src/libs/antares/study/equipments/equipments.hxx
  src/libs/antares/study/study.h
Labels: size/XL, cleaning

#1094 Concatenate namespaces for adq patch
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adq_patch_curtailment_sharing.h
  src/solver/simulation/adequacy.cpp
  src/solver/variable/economy/all.h
  src/solver/variable/economy/dtgMarginAfterCsr.h
  src/solver/variable/economy/spilledEnergyAfterCSR.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
Labels: size/M, cleaning

#1096 Check for incompatible hurdle cost options
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/solver/application.cpp
Labels: size/S, adq-patch

#1097 Add RTE banner in files
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adq_patch_local_matching.cpp
  src/solver/optimisation/adq_patch_local_matching.h
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/csr_quadratic_problem.h
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/optimisation/opt_period_string_generator_base.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/opt_time_writer.cpp
  src/solver/simulation/opt_time_writer.h
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/adequacy-patch-area-grid.h
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-areas.h
Labels: size/L, cleaning, adq-patch

#1090 Fix duplicate TS numbers for thermal clusters
  src/libs/antares/study/parts/common/cluster_list.cpp
Labels: bug, size/XS

#1100 [FIX] Adequacy code smells
  src/libs/antares/study/parameters.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adq_patch_local_matching.cpp
  src/solver/optimisation/adq_patch_local_matching.h
  src/solver/optimisation/csr_quadratic_problem.cpp
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/dtgMarginAfterCsr.h
  src/solver/variable/economy/spilledEnergyAfterCSR.h
Labels: size/L, cleaning, adq-patch

#1095 [CSR] Clarify implicit var convention
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/hourly_csr_problem.h
Labels: size/M, adq-patch

#1098 Pass hour instead of hourlyCsrProblem
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/opt_fonctions.h
Labels: size/S, cleaning, adq-patch

#1102 adq patch : move calculation of LMR violations from CSR source file to adq patch weekly problem
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/economy.cpp
Labels: size/L, adq-patch, refactoring

#1103 Move var declaration to right scope
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/csr_quadratic_problem.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
Labels: size/L, cleaning, adq-patch

#1107 Fix infinite loop, possible other bug
  src/solver/optimisation/csr_quadratic_problem.cpp
Labels: bug, size/M, adq-patch

#1099 Preparatory refactor to use own instance of PROBLEME_A_RESOUDRE
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.h
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/optimisation/opt_fonctions.h
Labels: size/L, adq-patch

#1108 UpperCamelCase for some classes, move sources to adequacy_patch_csr
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.h
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/adq_patch_local_matching.cpp
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, cleaning, adq-patch

#1111 Remove `OPT_*_CSR` functions
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/optimisation/opt_fonctions.h
Labels: size/XL, cleaning, code, adq-patch

#1112 Fix regression related to while loop and unitialized quadratic costs
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
Labels: bug, size/M, adq-patch

#1113 Fix a few more code smells
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/hourly_csr_problem.h
  src/ui/simulator/windows/options/optimization/optimization.cpp
Labels: size/M

#697 Hydraulic patch
  src/solver/hydro/management/daily.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: enhancement, size/L

#1109 Refactor optimization post process
  src/solver/cmake/simulation.cmake
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adq_patch_post_process_list.cpp
  src/solver/optimisation/adq_patch_post_process_list.h
  src/solver/optimisation/optim_post_process_list.cpp
  src/solver/optimisation/optim_post_process_list.h
  src/solver/optimisation/post_process_commands.cpp
  src/solver/optimisation/post_process_commands.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/base_post_process.cpp
  src/solver/simulation/base_post_process.h
  src/solver/simulation/common-dispatchable-margin.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
Labels: size/XL, adq-patch, refactoring

#1124 [FIX] Changed ProblemeHebdo to problemeHebdo
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adequacy_patch_csr/count_constraints_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/count_constraints_variables.h
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adq_patch_local_matching.cpp
  src/solver/optimisation/adq_patch_local_matching.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_chainage_intercos.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_pmax.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_numero_de_jour_du_pas_de_temps.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
Labels: size/XXL, cleaning, adq-patch

#1118 Move CSR from adq patch to post process cmd
  src/solver/optimisation/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/adq_patch_post_process_list.cpp
  src/solver/optimisation/adq_patch_post_process_list.h
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/post_process_commands.cpp
  src/solver/optimisation/post_process_commands.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/economy.cpp
Labels: size/L, adq-patch, refactoring

#1122 Update SimTest
  simtest.json
Labels: size/XS

#1125 [FIX] Add local_matching subdir
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/S, cleaning, adq-patch

#1126 Change Var to var
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/hourly_csr_problem.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
Labels: size/XXL, cleaning, adq-patch

#1128 Fix/move csr to post process cmd
  src/solver/simulation/base_post_process.cpp
  src/solver/simulation/base_post_process.h
Labels: size/XS

#1130 Release 8.5.0
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  docs/CHANGELOG.md
  docs/reference-guide/13-file-format.md
  sonar-project.properties
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  vcpkg_manifest/vcpkg.json
Labels: size/M

#1137 Move files related to ADQ patch to appropriate directory
  src/solver/cmake/solver.cmake
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/base_post_process.cpp
Labels: size/S, adq-patch
