Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-10, with the labels that each got.

#1651 Remove manual alloc and update code standards in hydro/daily2
  src/solver/hydro/daily/h2o_j_donnees_optimisation.h
  src/solver/hydro/daily/h2o_j_instanciation.cpp
  src/solver/hydro/daily/h2o_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/daily2/h2o2_j_apply_costs.cpp
  src/solver/hydro/daily2/h2o2_j_construire_les_contraintes.cpp
  src/solver/hydro/daily2/h2o2_j_construire_les_variables.cpp
  src/solver/hydro/daily2/h2o2_j_donnees_mensuelles.h
  src/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/daily2/h2o2_j_fonctions.h
  src/solver/hydro/daily2/h2o2_j_free.cpp
  src/solver/hydro/daily2/h2o2_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily2/h2o2_j_initialiser_les_second_membre.cpp
  src/solver/hydro/daily2/h2o2_j_instanciation.cpp
  src/solver/hydro/daily2/h2o2_j_optimiser_un_mois.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/monthly/h2o_m_donnees_optimisation.h
  src/solver/hydro/monthly/h2o_m_instanciation.cpp
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.cpp
Labels: size/XXL, cleaning, code quality

#1667 Remove code duplication in src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.cpp
Labels: size/XS, cleaning, code quality

#1659 Remove RenouvelableParPalier from global variable
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/area/scratchpad.h
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/parts/load/series.cpp
  src/libs/antares/study/parts/load/series.h
  src/libs/antares/study/parts/renewable/cluster.cpp
  src/libs/antares/study/parts/renewable/cluster.h
  src/libs/antares/study/parts/solar/series.cpp
  src/libs/antares/study/parts/solar/series.h
  src/libs/antares/study/parts/wind/series.cpp
  src/libs/antares/study/parts/wind/series.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/sim_variables_globales.cpp
  src/solver/variable/commons/hydro.h
  src/solver/variable/commons/load.h
  src/solver/variable/commons/solar.h
  src/solver/variable/commons/wind.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/economy/renewableGeneration.h
Labels: size/L

#1672 Fix wrong year number in logs upon failed year
  src/solver/simulation/solver.hxx
Labels: bug, size/XS

#1656 Fix - checkHourlyMinGeneration - HydroManagement function
  src/solver/hydro/management/management.cpp
Labels: size/XS, RTE-i

#1674 [Win] Increase file size limit when reading file
  src/ext/yuni/src/yuni/io/file/file.h
Labels: size/XS

#1676 Use `std::unique_ptr::operator->` rather than `std::unique_ptr::get` & raw pointers
  src/analyzer/atsp/correlations.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
Labels: size/M

#1650 Create Doxygen documentation
  .github/workflows/doxygen.yml
  README.md
  docs/Doxyfile
Labels: size/XXL

#1679 De-templatize `HydroManagement::prepareNetDemand`
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
Labels: size/S, cleaning

#1683 disable ghpages for pr
  .github/workflows/doxygen.yml
Labels: size/XS

#1680 Fix/test 50 windows
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnits.cpp
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnits.h
  src/solver/optimisation/constraints/MinDownTime.cpp
  src/solver/optimisation/constraints/MinDownTime.h
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.cpp
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.h
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStop.cpp
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStop.h
  src/solver/optimisation/constraints/PMaxDispatchableGeneration.cpp
  src/solver/optimisation/constraints/PMaxDispatchableGeneration.h
  src/solver/optimisation/constraints/PMinDispatchableGeneration.cpp
  src/solver/optimisation/constraints/PMinDispatchableGeneration.h
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
Labels: size/M

#1687 New log msg when solver not found in or-tools
  src/solver/utils/ortools_utils.cpp
  src/tests/run-study-tests/test_unfeasible_problem.py
Labels: enhancement, size/S

#1684 Add & use IntoUTF8ArgsTranslator::convert
  src/analyzer/main.cpp
  src/libs/antares/args/args_to_utf8.cpp
  src/libs/antares/args/include/antares/args/args_to_utf8.h
  src/solver/main.cpp
  src/tools/batchrun/main.cpp
  src/tools/cleaner/main.cpp
  src/tools/config/main.cpp
  src/tools/finder/main.cpp
  src/tools/updater/main.cpp
  src/tools/vacuum/main.cpp
  src/tools/yby-aggregator/main.cpp
Labels: size/M, refactoring

#1686 Use generic class for load series
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/store-timeseries-numbers.cpp
  src/libs/antares/study/parts/load/container.cpp
  src/libs/antares/study/parts/load/container.h
  src/libs/antares/study/parts/load/series.cpp
  src/libs/antares/study/parts/load/series.h
  src/libs/antares/study/parts/load/series.hxx
  src/libs/antares/study/parts/parts.h
  src/libs/antares/study/scenario-builder/LoadTSNumberData.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.importprepro.cpp
  src/solver/hydro/management/management.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/xcast/predicate.hxx
  src/solver/ts-generator/xcast/xcast.cpp
  src/solver/variable/commons/load.h
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/ui/action/handler/antares-study/area/timeseries.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
Labels: size/L, refactoring

#1678 Remove dependency to UI, use RAII to handle resources
  src/analyzer/CMakeLists.txt
  src/analyzer/main.cpp
  src/libs/antares/CMakeLists.txt
  src/libs/antares/args/CMakeLists.txt
  src/libs/antares/args/args_to_utf8.cpp
  src/libs/antares/args/include/antares/args/args_to_utf8.h
  src/solver/CMakeLists.txt
  src/solver/main.cpp
  src/tools/batchrun/CMakeLists.txt
  src/tools/batchrun/main.cpp
  src/tools/cleaner/CMakeLists.txt
  src/tools/cleaner/main.cpp
  src/tools/config/CMakeLists.txt
  src/tools/config/main.cpp
  src/tools/finder/CMakeLists.txt
  src/tools/finder/main.cpp
  src/tools/updater/CMakeLists.txt
  src/tools/updater/main.cpp
  src/tools/vacuum/CMakeLists.txt
  src/tools/vacuum/main.cpp
  src/tools/yby-aggregator/CMakeLists.txt
  src/tools/yby-aggregator/main.cpp
  src/ui/common/winmain.hxx
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/main.cpp
Labels: size/L, code quality

#1692 Add build instructions for Debian 12 & Ubuntu 23.04
  docs/build/1-Development-requirements.md
  docs/build/2-Dependencies-install.md
  docs/build/3-Build.md
  docs/build/5-Installer-creation.md
  src/CMakeLists.txt
Labels: size/M, doc, build

#1695 Add area name for rare error case
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
Labels: bug, size/XS

#1685 Fixes swallowed exceptions in computation thread
  src/libs/antares/CMakeLists.txt
  src/libs/antares/concurrency/CMakeLists.txt
  src/libs/antares/concurrency/concurrency.cpp
  src/libs/antares/concurrency/include/antares/concurrency/concurrency.h
  src/libs/antares/writer/CMakeLists.txt
  src/libs/antares/writer/antares/writer/i_writer.h
  src/libs/antares/writer/ensure_queue_started.cpp
  src/libs/antares/writer/immediate_file_writer.cpp
  src/libs/antares/writer/private/immediate_file_writer.h
  src/libs/antares/writer/private/zip_writer.h
  src/libs/antares/writer/private/zip_writer.hxx
  src/libs/antares/writer/zip_writer.cpp
  src/solver/application.cpp
  src/solver/application.h
  src/solver/main/CMakeLists.txt
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/solver.hxx
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/concurrency/CMakeLists.txt
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/writer/CMakeLists.txt
  src/tests/src/libs/antares/writer/test_zip_writer.cpp
Labels: bug, size/XL

#1699 Fix regression on cluster renaming, add unit tests
  src/libs/antares/study/study.cpp
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/libs/antares/test_utils.cpp
Labels: size/L

#1702 Fix segfault encountered when importing logs
  src/solver/application.cpp
Labels: bug, size/M

#1696 Use minizip-ng 4.0.1 (from 3.0.7)
  src/CMakeLists.txt
  src/libs/antares/writer/zip_writer.cpp
  src/tests/src/libs/antares/writer/test_zip_writer.cpp
Labels: size/XS

#670 Feature/optimization discrete variables
  docs/reference-guide/13-file-format.md
  src/libs/antares/checks/antares/checks/checkLoadedInputData.h
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/antares/exception/LoadingError.hpp
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/application.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/mps_utils.cpp
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
  src/solver/variable/state.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/advanced/advanced.h
Labels: size/L, feature

#1693 Refactor thermal & renewable series
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/common/cluster.cpp
  src/libs/antares/study/parts/common/cluster.h
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/common/cluster_list.h
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/parts/load/container.h
  src/libs/antares/study/parts/renewable/cluster.cpp
  src/libs/antares/study/parts/renewable/cluster.h
  src/libs/antares/study/parts/series/include/antares/series/series.h
  src/libs/antares/study/parts/series/series.cpp
  src/libs/antares/study/parts/solar/container.h
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/parts/wind/container.h
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/libs/antares/study/study.h
  src/solver/hydro/management/management.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/thermal.cpp
  src/solver/ts-generator/xcast/predicate.hxx
  src/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/state.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/ui/action/handler/antares-study/area/timeseries.cpp
  src/ui/action/handler/antares-study/area/ts-node.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
Labels: size/XL, refactoring

#1706 [DEV] Use a ref for TSNumbers
  src/libs/antares/study/parts/common/cluster.cpp
  src/libs/antares/study/parts/common/cluster.h
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/parts/load/container.cpp
  src/libs/antares/study/parts/load/container.h
  src/libs/antares/study/parts/series/include/antares/series/series.h
  src/libs/antares/study/parts/series/series.cpp
  src/libs/antares/study/parts/solar/container.cpp
  src/libs/antares/study/parts/solar/container.h
  src/libs/antares/study/parts/wind/container.cpp
  src/libs/antares/study/parts/wind/container.h
Labels: size/S, refactoring

#1710 CI Upgrade python to 3.12
  .github/workflows/windows-vcpkg.yml
Labels: bug, size/XS, ci

#1712 Make hydro ts count a private member
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/hydro.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/ui/action/handler/antares-study/area/timeseries.cpp
Labels: size/M, code quality

#1705 Refactor hydro series
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/parts/common/cluster.cpp
  src/libs/antares/study/parts/common/cluster.h
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/parts/hydro/series.hxx
  src/libs/antares/study/parts/load/container.cpp
  src/libs/antares/study/parts/load/container.h
  src/libs/antares/study/parts/series/include/antares/series/series.h
  src/libs/antares/study/parts/series/series.cpp
  src/libs/antares/study/parts/solar/container.cpp
  src/libs/antares/study/parts/solar/container.h
  src/libs/antares/study/parts/wind/container.cpp
  src/libs/antares/study/parts/wind/container.h
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/hydro.cpp
  src/solver/variable/commons/hydro.h
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/ui/action/handler/antares-study/area/timeseries.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
Labels: size/L, refactoring

#1713 Unit tests for timeseries
  src/libs/antares/study/parts/series/include/antares/series/series.h
  src/libs/antares/study/parts/series/series.cpp
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/series/CMakeLists.txt
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
Labels: size/L, tests

#1714 Remove global var NumeroChroniquesTireesParGroup
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/sim_variables_globales.cpp
Labels: size/M, cleaning, code quality

#1720 Add antares web to README
  README.md
Labels: size/XS, doc

#1707 Refactor hydro max power TS consistency
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.h
  src/libs/antares/study/parts/hydro/pair-of-integers.cpp
  src/libs/antares/study/parts/hydro/pair-of-integers.h
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/hydro.cpp
  src/tests/run-study-tests/test_unfeasible_problem.py
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-series.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/ui/action/handler/antares-study/area/timeseries.cpp
Labels: size/XL, RTE-i

#1726 Reset hydro storage correctly
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/parts/hydro/series.cpp
Labels: bug, size/S

#1728 update form develop and simplifications on CR 23
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/parts/hydro/series.cpp
Labels: size/M

#1729 Simplification on CR23: ResizeTS function
  src/libs/antares/series/series.cpp
  src/libs/antares/study/parts/hydro/series.cpp
Labels: size/M
