Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-08, with the labels that each got.

#1473 Replace empty destructors with default ones
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/src/libs/antares/array/matrix-bypass-load.h
  src/tests/src/libs/antares/logs/logs.h
  src/ui/simulator/toolbox/components/datagrid/renderer/geographic-trimming-grid.h
  src/ui/simulator/toolbox/components/notebook/mapnotebook.h
Labels: size/M, cleaning

#1471 Use std::vector instread of MemAlloc/MemFree, clean up
  src/libs/antares/CMakeLists.txt
  src/libs/antares/paths/list.cpp
  src/libs/antares/study/cleaner/cleaner.cpp
  src/libs/antares/study/header.cpp
  src/libs/antares/sys/mem-wrapper.c
  src/libs/antares/sys/mem-wrapper.h
  src/solver/memory/mem.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/solver.hxx
Labels: size/L, cleaning, code quality

#1422 Improve unit tests for CR20
  src/libs/antares/CMakeLists.txt
  src/libs/antares/checks/checkApplication.h
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/checks/checkLoadedInputData.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/list.hxx
  src/libs/antares/study/area/ui.cpp
  src/libs/antares/study/area/ui.h
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/parts/thermal/ecoInput.h
  src/solver/application.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/CMakeLists.txt
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalmodulation.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XL

#1482 Only develop and schedule jobs for Centos and Oracle CI
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
Labels: size/S, ci

#1481 Remove `ReserveHoraireJMoins1Ref`
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/S

#1475 Variables with a ref suffix
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_pmax.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/L, cleaning, code quality

#1483 Add tests for Windows CI when job is scheduled
  .github/workflows/windows-vcpkg.yml
Labels: size/M, ci

#1486 fix(tests): enforce better unit test isolation
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
Labels: size/L, tests

#1465 Objects in CmakeFiles
  src/libs/antares/CMakeLists.txt
  src/libs/antares/object/CMakeLists.txt
Labels: size/M

#1494 Remove Study::Get from SIM, pass as function argument instead
  src/solver/application.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/simulation.h
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
Labels: size/M

#1492 Remove use of study singleton in optimization module
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_export_structure.h
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_optimisation_hebdo.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/optimisation/weekly_optimization.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/utils/mps_utils.cpp
  src/solver/utils/mps_utils.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
Labels: size/L, cleaning

#1490 Remove std::shared_ptr around FinalLevelInflowsModifier
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/container.h
  src/libs/antares/study/parts/hydro/finallevelinflowsmodifyer.cpp
  src/libs/antares/study/parts/hydro/finallevelinflowsmodifyer.h
  src/solver/hydro/management/management.cpp
  src/solver/simulation/hydro-final-reservoir-level-functions.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
Labels: size/L, code quality

#1497 Remove possibly useless `ValeursDeNTCRef`
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, cleaning, code quality

#1499 Feature/maxgen maxpump cr23 - improvements
  src/libs/antares/study/action/handler/antares-study/area/timeseries.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
Labels: size/L

#1489 Refactor ProblemeHebdo allocation
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.h
Labels: size/L, cleaning, code quality

#1498 Removed Ref variables for hydro
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, cleaning

#1495 Remove unused headers in optimization module
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_chainage_intercos.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_outils.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_numero_de_jour_du_pas_de_temps.cpp
  src/solver/optimisation/opt_optimisation_hebdo.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
Labels: size/L

#1480 Binding constraint RHS chronicles : fixes asked by Paul P
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.h
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/solver/simulation/timeseries-numbers.cpp
Labels: bug, size/S

#1504 Simplify BindingConstraintGroupRepository::buildFrom
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.h
Labels: size/S

#1501 Removed SecondMembreDeLaContrainteCouplanteRef
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, cleaning

#1502 Removed CoutHoraireDeProductionDuPalierThermiqueRef
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/S, cleaning

#1388 Group of constraints
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.hxx
  src/libs/antares/study/load.cpp
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/simulation/BindingConstraintsTimeSeriesNumbersWriter.h
  src/solver/simulation/ITimeSeriesNumbersWriter.h
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/tests/src/libs/antares/study/constraint/CMakeLists.txt
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/XL

#1509 Remove more usage of study singleton
  src/solver/aleatoire/alea_fonctions.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/cbuilder.h
  src/solver/infeasible-problem-analysis/problem.cpp
  src/solver/infeasible-problem-analysis/problem.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/solver.hxx
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
  src/solver/utils/ortools_wrapper.h
Labels: size/M

#1398 Split ts numbers data classes in different files
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.h
  src/libs/antares/study/scenario-builder/HydroTSNumberData.cpp
  src/libs/antares/study/scenario-builder/HydroTSNumberData.h
  src/libs/antares/study/scenario-builder/LoadTSNumberData.cpp
  src/libs/antares/study/scenario-builder/LoadTSNumberData.h
  src/libs/antares/study/scenario-builder/NTCTSNumberData.cpp
  src/libs/antares/study/scenario-builder/NTCTSNumberData.h
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.cpp
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.h
  src/libs/antares/study/scenario-builder/SolarTSNumberData.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.h
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.h
  src/libs/antares/study/scenario-builder/WindTSNumberData.cpp
  src/libs/antares/study/scenario-builder/WindTSNumberData.h
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/solarTSNumberData.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
Labels: size/XXL

#1505 Replace remaining vector of pointers by plain vector
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/simulation.h
Labels: size/L

#1466 Bindings constraints scenario : handling last remarks
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/action/handler/antares-study/constraint/create.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.h
  src/libs/antares/study/binding_constraint/BindingConstraintTimeSeriesNumbers.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintTimeSeriesNumbers.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/scenario-builder/rules.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/solver.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/simulation/timeseries-numbers.h
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: enhancement, size/L, refactoring

#1517 Remove barely-used `ThermalCluster::productionCost` temporary
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/solver/variable/state.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
Labels: size/M, cleaning, code quality

#1513 Remove study singleton in application signal handlers
  src/solver/application.cpp
  src/solver/main.cpp
  src/solver/signal-handling/common.cpp
  src/solver/signal-handling/common.h
  src/solver/signal-handling/linux.cpp
  src/solver/signal-handling/public.h
  src/solver/signal-handling/windows.cpp
Labels: size/M

#1518 Write full command-line instead of solver location in logs
  src/libs/antares/resources/resources.cpp
  src/libs/antares/resources/resources.h
  src/solver/CMakeLists.txt
  src/solver/application.cpp
  src/solver/main.cpp
  src/solver/misc/write-command-line.cpp
  src/solver/misc/write-command-line.h
Labels: enhancement, size/M

#1523 Remove platform-specific headers
  src/solver/main.cpp
Labels: size/XS, cleaning, code quality

#1525 Automatically include yuni include directory in dependents
  src/ext/yuni/src/CMakeLists.txt
  src/ext/yuni/src/yuni/cmake/core/core.cmake
  src/libs/antares/CMakeLists.txt
  src/libs/antares/array/CMakeLists.txt
  src/libs/antares/correlation/CMakeLists.txt
  src/libs/antares/inifile/CMakeLists.txt
  src/libs/antares/io/CMakeLists.txt
  src/libs/antares/jit/CMakeLists.txt
  src/libs/antares/logs/CMakeLists.txt
  src/libs/antares/object/CMakeLists.txt
  src/libs/fswalker/CMakeLists.txt
  src/tests/src/libs/antares/CMakeLists.txt
Labels: size/M

#1514 Update SonarCloud to Java 17
  .github/workflows/sonarcloud.yml
Labels: size/M, ci

#1526 Prepare v8.7.0-rc2
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/M

#1519 Remove use of current study singleton in emergency exit
  src/libs/antares/CMakeLists.txt
  src/libs/antares/emergency.h
  src/libs/antares/exception/InitializationError.hpp
  src/libs/antares/fatal-error.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/study.extra.cpp
  src/libs/antares/study/study.h
  src/libs/antares/sys/policy.cpp
  src/libs/antares/sys/policy.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/application.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/main.cpp
  src/solver/misc/options.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_optimisation_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/solver.hxx
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/thermal.cpp
  src/solver/ts-generator/xcast/gamma-euler.cpp
  src/solver/ts-generator/xcast/gamma-inc.cpp
  src/solver/ts-generator/xcast/xcast.cpp
  src/solver/utils/mps_utils.cpp
  src/solver/utils/ortools_utils.cpp
  src/tools/yby-aggregator/main.cpp
  src/ui/simulator/application/application.cpp
Labels: size/XL

#1530 Schedule deps compile instead of develop merge
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/ubuntu-system-deps-build.yml
Labels: size/S, ci

#1528 Remove shared_ptr for OptPeriodStringGenerator
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/utils/filename.cpp
  src/solver/utils/filename.h
Labels: size/S, cleaning

#1506 Remove tmpnam from tests
  src/tests/src/CMakeLists.txt
  src/tests/src/libs/antares/study/constraint/CMakeLists.txt
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/utils/CMakeLists.txt
  src/tests/src/utils/utils.cpp
  src/tests/src/utils/utils.h
Labels: size/M, cleaning, tests

#1537 Remove unused function `getFilenameWithExtension`
  src/solver/utils/filename.cpp
  src/solver/utils/filename.h
Labels: size/S, cleaning

#1544 Remove dead code yuni-docmake
  src/ext/yuni/src/tools/CMakeLists.txt
  src/ext/yuni/src/tools/yuni-docmake/CMakeLists.txt
  src/ext/yuni/src/tools/yuni-docmake/dox2article/compound.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/compound.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/compound.hxx
  src/ext/yuni/src/tools/yuni-docmake/dox2article/indexes.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/indexes.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/job-compound-explorer.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/job-compound-explorer.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/job-compound-writer.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/job-compound-writer.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/job.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/job.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/main.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/options.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/options.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/read-index.cpp
  src/ext/yuni/src/tools/yuni-docmake/dox2article/read-index.h
  src/ext/yuni/src/tools/yuni-docmake/dox2article/toolbox.h
  src/ext/yuni/src/tools/yuni-docmake/logs.cpp
  src/ext/yuni/src/tools/yuni-docmake/logs.h
  src/ext/yuni/src/tools/yuni-docmake/make/article.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/article.h
  src/ext/yuni/src/tools/yuni-docmake/make/dictionary.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/dictionary.h
  src/ext/yuni/src/tools/yuni-docmake/make/index-db.sql
  src/ext/yuni/src/tools/yuni-docmake/make/indexes.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/indexes.h
  src/ext/yuni/src/tools/yuni-docmake/make/job-writer.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/job-writer.h
  src/ext/yuni/src/tools/yuni-docmake/make/job.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/job.h
  src/ext/yuni/src/tools/yuni-docmake/make/main.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/program-find-all-source-files.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/program.cpp
  src/ext/yuni/src/tools/yuni-docmake/make/program.h
  src/ext/yuni/src/tools/yuni-docmake/make/webpage.html
  src/ext/yuni/src/tools/yuni-docmake/www.libyuni.org.profile
Labels: size/XXL

#1553 Clarify string -> enum convesion for thermal cluster groups
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
Labels: size/L, code quality

#1549 Remove dynamique allocation
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M

#1556 Remove useless Area's data member : enabled
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
Labels: size/S, code quality

#1546 First step for yuni string removal: tools and application to cluster name
  src/CMakeLists.txt
  src/ext/yuni/src/yuni/core/string/string.h
  src/ext/yuni/src/yuni/core/string/string.hxx
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/fwd.h
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/renewable/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/libs/antares/utils.cpp
  src/libs/antares/utils.h
  src/libs/antares/utils.hxx
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/test_utils.cpp
  src/ui/simulator/toolbox/ext-source/handler/build-context.h
  src/ui/simulator/toolbox/ext-source/handler/com.rte-france.antares.study.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/windows/inspector/inspector.cpp
  src/ui/simulator/windows/inspector/property.cluster.update.cpp
  src/ui/simulator/windows/output/fwd.h
Labels: size/L

#1551 ACR CMake
  docs/Architecture_Decision_Records/CMake_design_choice.md
Labels: size/M

#1533 Remove goto in OPT_AppelDuSimplexe
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/M, cleaning, code quality

#1560 Fix boost tests
  .github/workflows/oracle8.yml
  src/tests/end-to-end/binding_constraints/CMakeLists.txt
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/CMakeLists.txt
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/CMakeLists.txt
  src/tests/src/libs/antares/array/tests-matrix-load.cpp
  src/tests/src/libs/antares/array/tests-matrix-save.cpp
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/M

#1570 Improve error logs for sc-builder
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/HydroTSNumberData.cpp
  src/libs/antares/study/scenario-builder/NTCTSNumberData.cpp
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.cpp
  src/libs/antares/study/scenario-builder/SolarTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/libs/antares/study/scenario-builder/WindTSNumberData.cpp
Labels: enhancement, size/S

#1567 Prevent segfault during simulation, check bounds of scenario builder …
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/HydroTSNumberData.cpp
  src/libs/antares/study/scenario-builder/NTCTSNumberData.cpp
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.cpp
  src/libs/antares/study/scenario-builder/SolarTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/libs/antares/study/scenario-builder/WindTSNumberData.cpp
  src/libs/antares/study/scenario-builder/applyToMatrix.hxx
  src/solver/simulation/apply-scenario.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
Labels: size/M

#1543 Use int32_t and uint32_t in PROBLEME_HEBDO
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, code quality

#1561 Remove sys as direct dependency of antares-core
  src/analyzer/CMakeLists.txt
  src/analyzer/main.cpp
  src/libs/antares/CMakeLists.txt
  src/libs/antares/date/CMakeLists.txt
  src/libs/antares/logs/CMakeLists.txt
  src/libs/antares/logs/antares/logs/hostinfo.h
  src/libs/antares/logs/hostinfo.cpp
  src/solver/CMakeLists.txt
  src/solver/application.cpp
  src/tools/cleaner/CMakeLists.txt
  src/tools/config/CMakeLists.txt
  src/tools/config/main.cpp
  src/tools/kirchhoff-cbuilder/CMakeLists.txt
  src/tools/kirchhoff-cbuilder/main.cpp
  src/tools/updater/CMakeLists.txt
  src/tools/yby-aggregator/CMakeLists.txt
  src/tools/yby-aggregator/main.cpp
  src/ui/simulator/application/application.cpp
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/cmake/windows-options.cmake
  src/ui/simulator/main.cpp
Labels: size/M, build

#1573 Fix annoying error log about correlation matrixes in tests
  src/libs/antares/study/action/handler/antares-study/area/create.cpp
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/ui/simulator/toolbox/components/map/nodes/node.cpp
Labels: enhancement, size/M, tests

#1579 Use reference instead of raw pointers
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/XS, code quality

#1577 Compile warnings for uint32_t
  src/solver/hydro/daily/h2o_j_ajouter_bruit_au_cout.cpp
  src/solver/hydro/daily/h2o_j_donnees_optimisation.h
  src/solver/hydro/daily/h2o_j_free.c
  src/solver/hydro/daily2/h2o2_j_optimiser_un_mois.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/count_constraints_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_chainage_intercos.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_quadratique.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_export_structure.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_second_membre_couts_demarrage.cpp
  src/solver/optimisation/opt_init_contraintes_hydrauliques.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/L, cleaning

#1554 Remove dynamic alloc of PROBLEME_HEBDO
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/optimization_statistics.h
Labels: size/L, cleaning, code quality

#1584 Segfault ortools
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/M

#1585 Remove unused variable
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/XS

#1558 CMake Memory and Sys
  src/analyzer/CMakeLists.txt
  src/analyzer/main.cpp
  src/libs/antares/CMakeLists.txt
  src/libs/antares/array/CMakeLists.txt
  src/libs/antares/array/antares/array/matrix.h
  src/libs/antares/benchmarking/CMakeLists.txt
  src/libs/antares/checks/CMakeLists.txt
  src/libs/antares/correlation/CMakeLists.txt
  src/libs/antares/date/CMakeLists.txt
  src/libs/antares/inifile/CMakeLists.txt
  src/libs/antares/logs/CMakeLists.txt
  src/libs/antares/logs/antares/logs/hostinfo.h
  src/libs/antares/logs/hostinfo.cpp
  src/libs/antares/memory/CMakeLists.txt
  src/libs/antares/memory/include/antares/memory/memory.h
  src/libs/antares/memory/include/antares/memory/memory.hxx
  src/libs/antares/memory/include/antares/memory/new_check.hxx
  src/libs/antares/memory/memory.cpp
  src/libs/antares/sys/CMakeLists.txt
  src/libs/antares/sys/appdata.cpp
  src/libs/antares/sys/include/antares/sys/appdata.h
  src/libs/antares/sys/include/antares/sys/hostname.hxx
  src/libs/antares/sys/include/antares/sys/policy.h
  src/libs/antares/sys/policy.cpp
  src/solver/CMakeLists.txt
  src/solver/application.cpp
  src/tests/src/libs/antares/CMakeLists.txt
  src/tools/cleaner/CMakeLists.txt
  src/tools/config/CMakeLists.txt
  src/tools/config/main.cpp
  src/tools/kirchhoff-cbuilder/CMakeLists.txt
  src/tools/kirchhoff-cbuilder/main.cpp
  src/tools/updater/CMakeLists.txt
  src/tools/yby-aggregator/CMakeLists.txt
  src/tools/yby-aggregator/main.cpp
  src/ui/simulator/application/application.cpp
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/cmake/windows-options.cmake
  src/ui/simulator/main.cpp
Labels: size/L

#1590 Fix oracle 8 compilation issue
  src/libs/antares/memory/CMakeLists.txt
Labels: size/S

#1595 Remove duplicate header
  src/libs/antares/study/area/area.h
Labels: size/XS, cleaning

#1596 Document the usage of XPRESS
  docs/reference-guide/16-xpress.md
Labels: size/M, doc
