Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-05, with the labels that each got.

#1269 Remove pointer on `std::vector`s
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/optimisation/adequacy_patch_csr/construct_problem_constraints_RHS.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/economy/STStorageWithdrawalByCluster.h
  src/solver/variable/economy/links/congestionFee.h
  src/solver/variable/economy/links/congestionFeeAbs.h
  src/solver/variable/economy/max-mrg.cpp
  src/solver/variable/economy/shortTermStorage.h
  src/solver/variable/state.hxx
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, Short term storage, code quality

#1167 Bump OR-Tools 9.2 -> 9.5, fix random compilation errors in Windows
  .github/workflows/centos7.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
  src/ui/simulator/windows/simulation/run.cpp
Labels: size/S

#1281 Load STS data only if version >= 860
  src/libs/antares/study/area/list.cpp
Labels: size/XS, Short term storage

#1280 Make the initial level a dimensionless quantity, multiply by capacity
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Labels: size/XS, Short term storage

#1267 Fix indices in modeler
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/S, Short term storage

#1218 Add I/O changes for BC RHS scenarization (v8.6)
  docs/reference-guide/13-file-format.md
Labels: size/M, doc

#1283 Add output variables for short-term storage in adequacy mode
  src/solver/variable/adequacy/all.h
  src/solver/variable/economy/all.h
Labels: size/L, Short term storage

#1286 [FIX] InitialLevel < 1
  src/libs/antares/study/parts/short-term-storage/properties.cpp
Labels: size/XS, Short term storage

#1285 Revert weekly checks
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/load.cpp
Labels: size/M, Short term storage

#1287 [CI] Centos deps compilation: cmake version
  .github/workflows/centos7-system-deps-build.yml
Labels: size/S, ci

#1153 Refactor `checkMinStablePower`
  src/libs/antares/study/parts/renewable/container.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/container.cpp
  src/libs/antares/study/parts/thermal/container.h
  src/solver/application.cpp
Labels: size/M

#1293 Write ROR & STORAGE in TS-Generator (store in output)
  src/solver/ts-generator/hydro.cpp
Labels: size/S

#1288 Fix version check for mingen
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/solver/hydro/management/management.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/ts-generator/hydro.cpp
Labels: size/M

#1273 Minimal hydro generation (RTEi's -> CR22)
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/action/handler/antares-study/area/timeseries.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/solver/hydro/CMakeLists.txt
  src/solver/hydro/daily/h2o_j_donnees_mensuelles.h
  src/solver/hydro/daily/h2o_j_free.c
  src/solver/hydro/daily/h2o_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily/h2o_j_instanciation.c
  src/solver/hydro/daily2/h2o2_j_donnees_mensuelles.h
  src/solver/hydro/daily2/h2o2_j_free.cpp
  src/solver/hydro/daily2/h2o2_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily2/h2o2_j_instanciation.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/h2o_m_donnees_annuelles.h
  src/solver/hydro/monthly/h2o_m_free.c
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.c
  src/solver/hydro/monthly/h2o_m_instanciation.c
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
  src/ui/simulator/windows/hydro/series.cpp
Labels: size/L, RTE-i

#1296 RC++, upate changelog
  docs/CHANGELOG.md
  docs/reference-guide/01-introduction.md
  src/CMakeLists.txt
Labels: size/M

#1297 Thermal price definition (RTEi's -> CR20) comment implementation - refactoring
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/action/handler/antares-study/area/ts-node.cpp
  src/libs/antares/study/estimate.memory-footprint.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/solver/application.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.cpp
  src/ui/simulator/windows/inspector/frame.cpp
Labels: size/L

#1265 [CLEAN] Remove unused var from ThermalCluster
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/variable/area.inc.hxx
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/tests/end-to-end/simple-study.cpp
Labels: size/L, cleaning

#1299 Remove parameters.hxx, fix Parameters::memoryUsage
  src/libs/antares/CMakeLists.txt
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/parameters.hxx
Labels: size/M, cleaning, code

#1301 [CLEAN] Fix a few compilation warnings (int -> uint)
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_numero_de_jour_du_pas_de_temps.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/optimisation/opt_verification_presence_reserve_jmoins1.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/simulation.h
Labels: size/M, cleaning

#1298 Move RHS scenarization to v8.7.0
  docs/reference-guide/13-file-format.md
Labels: size/S, doc

#1307 Add precisions for mingen
  docs/reference-guide/13-file-format.md
Labels: size/XS, doc

#1309 Simplify if/else
  src/solver/optimisation/opt_optimisation_lineaire.cpp
Labels: size/S, code quality

#1311 modify-doc-for-v8.6-output-format
  docs/reference-guide/13-file-format.md
Labels: size/XS

#1308 hydro min power : correction
  src/solver/hydro/management/management.cpp
Labels: size/M

#1302 Fix memory errors detected by valfgrind
  src/solver/hydro/management/daily.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
Labels: bug, size/S, cleaning

#1313 8.6.0-rc6
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#1314 Valgrind memory in adequacy
  src/solver/simulation/adequacy.cpp
Labels: size/XS, code quality

#1303 Use ISO8601 for date format in the logs
  src/ext/yuni/src/yuni/core/logs/decorators/time.cpp
  src/ext/yuni/src/yuni/core/logs/decorators/time.h
Labels: size/M, code
