Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-09, with the labels that each got.

#1610 Reduce use of study in helper functions
  src/libs/antares/study/area/links.cpp
Labels: size/M

#1600 Architecture Decision Record for Study breakdown
  docs/Architecture_Decision_Records/2023-08-29_study_class_breakdown.md
Labels: size/M

#1613 Add short options for MPS generation, force generation if named MPS requested
  docs/reference-guide/10-command_line.md
  src/libs/antares/study/parameters.cpp
  src/solver/misc/options.cpp
Labels: size/S

#1611 Add interface for problem naming
  src/solver/utils/CMakeLists.txt
  src/solver/utils/mps_utils.cpp
  src/solver/utils/name_translator.cpp
  src/solver/utils/name_translator.h
  src/solver/utils/named_problem.h
Labels: size/L

#1586 Remove deps to core
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/checks/CMakeLists.txt
  src/libs/antares/date/antares/date/date.h
  src/libs/antares/date/date.cpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/writer/CMakeLists.txt
  src/libs/antares/writer/antares/writer/writer_factory.h
  src/solver/optimisation/CMakeLists.txt
Labels: size/M

#1616 Move economic thermal costs input files into "series" directory
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/cluster_list.h
Labels: enhancement, size/L

#1619 Release/8.7.0
  docs/CHANGELOG.md
  docs/reference-guide/13-file-format.md
  src/CMakeLists.txt
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/cluster_list.h
Labels: size/L

#1621 Provide reference to `Benchmarking::IDurationCollector`, not pointer
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/libs/antares/writer/antares/writer/writer_factory.h
  src/libs/antares/writer/private/zip_writer.h
  src/libs/antares/writer/writer_factory.cpp
  src/libs/antares/writer/zip_writer.cpp
  src/solver/application.cpp
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/tests/end-to-end/utils/utils.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
Labels: size/M, code quality

#1609 Remove liblib* CMake targets
  src/analyzer/CMakeLists.txt
  src/libs/antares/CMakeLists.txt
  src/libs/antares/checks/CMakeLists.txt
  src/libs/fswalker/CMakeLists.txt
  src/solver/CMakeLists.txt
  src/solver/aleatoire/CMakeLists.txt
  src/solver/constraints-builder/CMakeLists.txt
  src/solver/hydro/CMakeLists.txt
  src/solver/main/CMakeLists.txt
  src/solver/optimisation/CMakeLists.txt
  src/solver/simulation/CMakeLists.txt
  src/solver/ts-generator/CMakeLists.txt
  src/solver/utils/CMakeLists.txt
  src/solver/variable/CMakeLists.txt
  src/tests/end-to-end/binding_constraints/CMakeLists.txt
  src/tests/end-to-end/simple_study/CMakeLists.txt
  src/tests/end-to-end/utils/CMakeLists.txt
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/study/area/CMakeLists.txt
  src/tests/src/libs/antares/study/output-folder/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/CMakeLists.txt
  src/tests/src/solver/optimisation/CMakeLists.txt
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tools/batchrun/CMakeLists.txt
  src/tools/cleaner/CMakeLists.txt
  src/tools/config/CMakeLists.txt
  src/tools/finder/CMakeLists.txt
  src/tools/kirchhoff-cbuilder/CMakeLists.txt
  src/tools/updater/CMakeLists.txt
  src/tools/vacuum/CMakeLists.txt
  src/tools/yby-aggregator/CMakeLists.txt
  src/ui/common/CMakeLists.txt
  src/ui/simulator/CMakeLists.txt
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/cmake/components-button.cmake
  src/ui/simulator/cmake/components-htmllistbox.cmake
  src/ui/simulator/cmake/components-map.cmake
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/cmake/copy-paste.cmake
  src/ui/simulator/cmake/inputs.cmake
  src/ui/simulator/cmake/jobs.cmake
  src/ui/simulator/cmake/messages.cmake
  src/ui/simulator/cmake/resources.cmake
  src/ui/simulator/cmake/toolbox-spotlight.cmake
  src/ui/simulator/cmake/windows-calendar.cmake
  src/ui/simulator/cmake/windows-inspector.cmake
  src/ui/simulator/cmake/windows-options.cmake
  src/ui/simulator/cmake/windows-output.cmake
  src/ui/simulator/cmake/windows-startupwizard.cmake
  src/ui/simulator/cmake/windows-studyparts.cmake
  src/ui/simulator/cmake/wxcore.cmake
Labels: size/L, build

#1618 Remove global var NumeroChroniquesTireesParPays
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/aleatoire/alea_fonctions.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/simulation/solver.hxx
Labels: size/M, refactoring, code quality

#1527 Fix unfeasible problem analyzer
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/problem.cpp
  src/solver/infeasible-problem-analysis/problem.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_rename_problem.h
  src/solver/utils/CMakeLists.txt
  src/solver/utils/mps_utils.cpp
  src/solver/utils/name_translator.cpp
  src/solver/utils/name_translator.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_utils.h
Labels: size/L

#1623 Clean up parameters.cpp
  src/libs/antares/study/parameters.cpp
Labels: size/S, cleaning

#1625 Remove unused `BindingConstraintsRepository::eachActive`
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.hxx
Labels: size/S, cleaning

#1629 Remove remaining fixed-size ints from Yuni
  src/ext/yuni/src/yuni/core/color/rgb.h
  src/ext/yuni/src/yuni/core/getopt/option.h
  src/ext/yuni/src/yuni/core/static/types.h
  src/ext/yuni/src/yuni/core/system/stdint.h
  src/ext/yuni/src/yuni/io/file/stream.h
  src/ext/yuni/src/yuni/io/file/stream.hxx
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/ui/simulator/windows/output/panel/area-link.cpp
Labels: size/M

#1594 Move thermal noises to class Simulation
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/libs/antares/study/study.cpp
  src/solver/aleatoire/alea_fonctions.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/daily2/h2o2_j_optim_costs.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/base_weekly_optimization.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/simulation.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/ts-generator/thermal.cpp
  src/solver/variable/economy/max-mrg.cpp
  src/solver/variable/economy/max-mrg.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/XXL, code quality

#1639 Add advice for developers
  docs/build/0-INSTALL.md
  docs/build/6-dev-advice.md
Labels: size/M, doc

#1638 Add warning logs for non-existent output variable
  src/libs/antares/study/parameters.cpp
Labels: size/XS

#1381 Refactor hydro pmin checks
  src/solver/hydro/management/management.cpp
Labels: size/L, refactoring

#1642 Remove most uses of `IResultWriter::Ptr`, use ref instead
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/area/store-timeseries-numbers.cpp
  src/libs/antares/study/area/store-timeseries-numbers.h
  src/libs/antares/study/area/store-timeseries-numbers.hxx
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/common/cluster_list.h
  src/libs/antares/study/progression/progression.cpp
  src/libs/antares/study/progression/progression.h
  src/libs/antares/study/simulation.cpp
  src/libs/antares/study/simulation.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.hxx
  src/solver/application.cpp
  src/solver/application.h
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
  src/solver/simulation/BindingConstraintsTimeSeriesNumbersWriter.h
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/opt_time_writer.cpp
  src/solver/simulation/opt_time_writer.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/simulation/solver.utils.h
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/generator.h
  src/solver/ts-generator/generator.hxx
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/thermal.cpp
  src/solver/ts-generator/xcast/xcast.cpp
  src/solver/ts-generator/xcast/xcast.h
  src/solver/variable/container.h
  src/solver/variable/container.hxx
  src/solver/variable/surveyresults/data.h
  src/solver/variable/surveyresults/reportbuilder.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
  src/solver/variable/surveyresults/surveyresults.h
Labels: size/L

#1646 Fix number of links in deprecated output file digest.txt
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: size/XS

#1633 New "cash-flow" variable for ST storage
  src/solver/variable/CMakeLists.txt
  src/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/economy/all.h
Labels: size/L, Short term storage

#1607 Refactor constraint building
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/constraints/AreaBalance.cpp
  src/solver/optimisation/constraints/AreaBalance.h
  src/solver/optimisation/constraints/AreaHydroLevel.cpp
  src/solver/optimisation/constraints/AreaHydroLevel.h
  src/solver/optimisation/constraints/BindingConstraintDay.cpp
  src/solver/optimisation/constraints/BindingConstraintDay.h
  src/solver/optimisation/constraints/BindingConstraintHour.cpp
  src/solver/optimisation/constraints/BindingConstraintHour.h
  src/solver/optimisation/constraints/BindingConstraintWeek.cpp
  src/solver/optimisation/constraints/BindingConstraintWeek.h
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnits.cpp
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnits.h
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/constraints/FictitiousLoad.cpp
  src/solver/optimisation/constraints/FictitiousLoad.h
  src/solver/optimisation/constraints/FinalStockEquivalent.cpp
  src/solver/optimisation/constraints/FinalStockEquivalent.h
  src/solver/optimisation/constraints/FinalStockExpression.cpp
  src/solver/optimisation/constraints/FinalStockExpression.h
  src/solver/optimisation/constraints/FlowDissociation.cpp
  src/solver/optimisation/constraints/FlowDissociation.h
  src/solver/optimisation/constraints/HydroPower.cpp
  src/solver/optimisation/constraints/HydroPower.h
  src/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationMaxDown.cpp
  src/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationMaxDown.h
  src/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationMaxUp.cpp
  src/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationMaxUp.h
  src/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationSum.cpp
  src/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationSum.h
  src/solver/optimisation/constraints/MaxHydroPower.cpp
  src/solver/optimisation/constraints/MaxHydroPower.h
  src/solver/optimisation/constraints/MaxPumping.cpp
  src/solver/optimisation/constraints/MaxPumping.h
  src/solver/optimisation/constraints/MinDownTime.cpp
  src/solver/optimisation/constraints/MinDownTime.h
  src/solver/optimisation/constraints/MinHydroPower.cpp
  src/solver/optimisation/constraints/MinHydroPower.h
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.cpp
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.h
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStop.cpp
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStop.h
  src/solver/optimisation/constraints/PMaxDispatchableGeneration.cpp
  src/solver/optimisation/constraints/PMaxDispatchableGeneration.h
  src/solver/optimisation/constraints/PMinDispatchableGeneration.cpp
  src/solver/optimisation/constraints/PMinDispatchableGeneration.h
  src/solver/optimisation/constraints/ShortTermStorageLevel.cpp
  src/solver/optimisation/constraints/ShortTermStorageLevel.h
  src/solver/optimisation/opt_construction_contraintes_couts_demarrage.cpp
  src/solver/optimisation/opt_construction_matrice_des_contraintes_cas_lineaire.cpp
  src/solver/optimisation/opt_rename_problem.h
Labels: size/XXL

#1626 Remove malloc in src/solver/hydro/
  src/solver/hydro/CMakeLists.txt
  src/solver/hydro/daily/h2o_j_construire_les_contraintes.cpp
  src/solver/hydro/daily/h2o_j_construire_les_variables.cpp
  src/solver/hydro/daily/h2o_j_donnees_optimisation.h
  src/solver/hydro/daily/h2o_j_fonctions.h
  src/solver/hydro/daily/h2o_j_free.cpp
  src/solver/hydro/daily/h2o_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily/h2o_j_initialiser_les_second_membre.cpp
  src/solver/hydro/daily/h2o_j_instanciation.cpp
  src/solver/hydro/daily/h2o_j_lisser_les_sur_turbines.cpp
  src/solver/hydro/daily/h2o_j_optimiser_un_mois.cpp
  src/solver/hydro/daily/h2o_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/daily/h2o_j_sys.h
  src/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/h2o_m_ajouter_bruit.cpp
  src/solver/hydro/monthly/h2o_m_construire_les_contraintes.cpp
  src/solver/hydro/monthly/h2o_m_construire_les_variables.cpp
  src/solver/hydro/monthly/h2o_m_donnees_annuelles.h
  src/solver/hydro/monthly/h2o_m_donnees_optimisation.h
  src/solver/hydro/monthly/h2o_m_fonctions.h
  src/solver/hydro/monthly/h2o_m_free.cpp
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/monthly/h2o_m_initialiser_les_second_membre.cpp
  src/solver/hydro/monthly/h2o_m_instanciation.cpp
  src/solver/hydro/monthly/h2o_m_optimiser_une_annee.cpp
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/monthly/h2o_m_sys.h
Labels: size/XXL, cleaning, code quality

#1652 remove print in ConstraintNamer
  src/solver/optimisation/opt_rename_problem.h
Labels: size/XS

#1649 Move `resultWriter` out of class `Study`
  src/libs/antares/study/importlogs.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/libs/antares/study/study.hxx
  src/libs/antares/writer/antares/writer/i_writer.h
  src/libs/antares/writer/immediate_file_writer.cpp
  src/solver/application.cpp
  src/solver/application.h
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/simulation/timeseries-numbers.h
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/ui/simulator/application/application.cpp
Labels: size/L, cleaning, code quality

#1654 Update README.md
  README.md
Labels: size/XS

#1632 Use 50% as a default value for ST-storage property initiallevel
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M

#1564 Update Final reservoir level implementation - cr25
  src/libs/antares/study/parts/hydro/finallevelinflowsmodifyer.cpp
  src/libs/antares/study/parts/hydro/finallevelinflowsmodifyer.h
  src/solver/simulation/hydro-final-reservoir-level-functions.cpp
  src/tests/src/solver/simulation/test-hydro-final-reservoir-level-functions.cpp
Labels: size/S, RTE-i

#1644 Add getValue for thermal clusters, remove State::timeSeriesIndex
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/parts/common/series.cpp
  src/libs/antares/study/parts/common/series.h
  src/libs/antares/study/parts/common/series.hxx
  src/libs/antares/study/parts/renewable/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/solver/aleatoire/alea_tirage_au_sort_chroniques.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_structure_donnees.h
  src/solver/simulation/solver.hxx
  src/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/economy/renewableGeneration.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/state.hxx
Labels: size/L, refactoring

#1660 Introduce & use DataSeriesCommon::getAvailablePowerYearly
  src/libs/antares/study/parts/common/series.cpp
  src/libs/antares/study/parts/common/series.h
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/ts-generator/thermal.cpp
  src/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/state.cpp
Labels: size/M
