Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-12, with the labels that each got.

#1784 Small refactoring CR23
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
Labels: size/S, RTE-i, 👀 Take a deeper dive

#1804 Remove sts container
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/container.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/economy/STStorageWithdrawalByCluster.h
  src/solver/variable/economy/shortTermStorage.h
  src/solver/variable/info.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
Labels: size/M, cleaning, code quality

#1771 Normalize simulation mode Expansion, fix logs
  src/libs/antares/CMakeLists.txt
  src/libs/antares/constants.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/antares/exception/LoadingError.hpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/fwd.h
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/load-options.h
  src/libs/antares/study/output.cpp
  src/libs/antares/study/output.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/libs/antares/xpansion.h
  src/solver/application.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/commons/rowBalance.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/state.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/ui/simulator/application/main/refresh.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/constants.cpp
  src/ui/simulator/windows/inspector/constants.h
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/output/panel/area-link.cpp
  src/ui/simulator/windows/output/provider/outputs.cpp
  src/ui/simulator/windows/simulation/run.cpp
Labels: bug, enhancement, size/L

#1799 Enable cpp20
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu.yml
  src/CMakeLists.txt
  src/cmake/common-settings.cmake
  src/ext/yuni/src/yuni/CMakeLists.txt
  src/ext/yuni/src/yuni/core/string/operators.hxx
  src/tests/src/libs/antares/study/test_study.cpp
  src/ui/common/component/spotlight/listbox-panel.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/layers.cpp
  src/ui/simulator/windows/bindingconstraint/edit.cpp
  src/ui/simulator/windows/correlation/datasources.hxx
  src/ui/simulator/windows/hydro/dailypower.cpp
  src/ui/simulator/windows/hydro/management.cpp
Labels: size/L, 👀 Take a deeper dive

#1818 Fix YML for CentOS7 & OL8
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
Labels: size/XS, 🚨 Don't Merge

#1820 Refactor update time
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/opt_time_writer.cpp
  src/solver/simulation/opt_time_writer.h
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver_utils.cpp
Labels: size/M, 🍉 Safe to Merge

#1789 Write update times
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/opt_time_writer.cpp
  src/solver/simulation/opt_time_writer.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/solver.h
  src/solver/simulation/solver.hxx
  src/solver/simulation/solver_utils.cpp
  src/solver/simulation/solver_utils.h
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/state.hxx
Labels: size/L, 👀 Take a deeper dive

#1815 reshape constraint construction
  src/solver/optimisation/ProblemMatrixEssential.h
  src/solver/optimisation/constraints/AbstractStartUpCostsGroup.h
  src/solver/optimisation/constraints/AreaHydroLevelGroup.cpp
  src/solver/optimisation/constraints/AreaHydroLevelGroup.h
  src/solver/optimisation/constraints/BindingConstraintDayGroup.cpp
  src/solver/optimisation/constraints/BindingConstraintDayGroup.h
  src/solver/optimisation/constraints/BindingConstraintWeekGroup.cpp
  src/solver/optimisation/constraints/BindingConstraintWeekGroup.h
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnitsGroup.cpp
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnitsGroup.h
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/constraints/ConstraintGroup.h
  src/solver/optimisation/constraints/ExchangeBalanceGroup.cpp
  src/solver/optimisation/constraints/ExchangeBalanceGroup.h
  src/solver/optimisation/constraints/FinalStockGroup.cpp
  src/solver/optimisation/constraints/FinalStockGroup.h
  src/solver/optimisation/constraints/Group1.cpp
  src/solver/optimisation/constraints/Group1.h
  src/solver/optimisation/constraints/HydraulicSmoothingGroup.cpp
  src/solver/optimisation/constraints/HydraulicSmoothingGroup.h
  src/solver/optimisation/constraints/HydroPowerGroup.cpp
  src/solver/optimisation/constraints/HydroPowerGroup.h
  src/solver/optimisation/constraints/MaxPumpingGroup.cpp
  src/solver/optimisation/constraints/MaxPumpingGroup.h
  src/solver/optimisation/constraints/MinDownTimeGroup.cpp
  src/solver/optimisation/constraints/MinDownTimeGroup.h
  src/solver/optimisation/constraints/MinMaxHydroPowerGroup.cpp
  src/solver/optimisation/constraints/MinMaxHydroPowerGroup.h
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTimeGroup.cpp
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTimeGroup.h
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStopGroup.cpp
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStopGroup.h
  src/solver/optimisation/constraints/PMinMaxDispatchableGenerationGroup.cpp
  src/solver/optimisation/constraints/PMinMaxDispatchableGenerationGroup.h
Labels: size/L, 👀 Take a deeper dive

#1824 Small code improvement in solver_utils.cpp
  src/solver/simulation/solver_utils.cpp
Labels: size/M, cleaning, code quality, 🍉 Safe to Merge

#1827 Fix pmax contribution
  src/solver/optimisation/constraints/PMaxDispatchableGeneration.cpp
  src/solver/optimisation/constraints/PMinDispatchableGeneration.cpp
Labels: size/S

#1828 Remove yuni volatile warning
  src/ext/yuni/src/yuni/core/atomic/int.hxx
Labels: size/XS, cleaning

#1830 Adapt C++ 20 for win
  src/libs/antares/sys/policy.cpp
  src/tools/yby-aggregator/job.cpp
  src/ui/simulator/windows/inspector/inspector.cpp
  src/ui/simulator/windows/output/spotlight-provider.cpp
Labels: size/S, build

#1831 Adapt C++ 20 for win 2 : overlook of a detail
  src/libs/antares/sys/policy.cpp
Labels: size/XS

#1807 Add `enabled` property for ST storage objects, fix bug related to saving ST objects
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/economy/STStorageWithdrawalByCluster.h
  src/solver/variable/economy/shortTermStorage.h
  src/solver/variable/info.h
  src/tests/src/libs/antares/study/short-term-storage-input/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: size/L, 👀 Take a deeper dive

#1834 Fix 2 build warnings
  src/solver/optimisation/LinearProblemMatrixStartUpCosts.cpp
  src/solver/optimisation/constraints/AbstractStartUpCostsGroup.cpp
  src/solver/optimisation/constraints/AbstractStartUpCostsGroup.h
Labels: size/S

#1813 Refactor common ClusterList class
  src/libs/antares/InfoCollection/StudyInfoCollector.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/parts/common/cluster.cpp
  src/libs/antares/study/parts/common/cluster.h
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/common/cluster_list.h
  src/libs/antares/study/parts/renewable/cluster_list.cpp
  src/libs/antares/study/parts/renewable/cluster_list.h
  src/libs/antares/study/parts/renewable/container.cpp
  src/libs/antares/study/parts/renewable/container.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/cluster_list.h
  src/libs/antares/study/parts/thermal/container.cpp
  src/libs/antares/study/parts/thermal/container.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/sys/policy.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/economy/renewableGeneration.h
  src/solver/variable/info.h
  src/solver/variable/surveyresults/reportbuilder.hxx
  src/tools/yby-aggregator/job.cpp
  src/ui/action/handler/antares-study/area/create.cpp
  src/ui/action/handler/antares-study/thermal-cluster/create.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermal.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-renewable-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-thermal-renderer.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster-order.cpp
  src/ui/simulator/toolbox/components/map/manager.cpp
  src/ui/simulator/toolbox/input/renewable-cluster.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/inspector.cpp
  src/ui/simulator/windows/output/spotlight-provider.cpp
Labels: PR: waiting for correction, size/XXL, cleaning, code quality, 👀 Take a deeper dive

#1835 Fix flawed concurrency test (concurrent write on non-atomic int)
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
Labels: bug, size/XS, tests

#1833 Merge branch release/8.8.x into develop (changelog, version number)
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/M

#1838 Use `type*` for pointers instead of `auto&`, add `const` qualifier
  src/solver/utils/ortools_utils.cpp
Labels: size/S

#1839 Add `enabled` property to ST storage objects, fix bug in save
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
  src/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/economy/STStorageWithdrawalByCluster.h
  src/solver/variable/economy/shortTermStorage.h
  src/tests/src/libs/antares/study/short-term-storage-input/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: size/L

#1840 Add tests for MILP using CBC
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
  src/tests/CMakeLists.txt
Labels: size/S

#1795 Runvcpkg + runcmake+presets
  .github/workflows/runvcpkg-runcmake.yml
  src/vcpkg.json
Labels: size/M

#1842 Feature/python exe path
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#1848 Use SimTest v8.8.0
  simtest.json
Labels: size/XS

#1847 Use modern style for loops, avoid int cast
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.hxx
Labels: size/S

#1792 Add dark mode switch for Doxygen online documentation
  .github/workflows/doxygen.yml
  docs/Doxyfile
  docs/antares-simulator-doxygen.patch
Labels: size/M, doc

#1836 Fix compile warnings on Linux with g++>=10
  src/ext/yuni/src/yuni/core/tree/n/treeN.hxx
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintLoader.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/parts/common/cluster_list.h
  src/solver/infeasible-problem-analysis/report.h
  src/solver/infeasible-problem-analysis/unfeasibility-analysis.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/ui/simulator/application/study.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/bindingconstraint/data.cpp
Labels: size/M

#1796 Minor code fixes, cleaning
  src/ext/yuni/src/tools/yuni-config/program.cpp
  src/ext/yuni/src/yuni/cmake/parser/importer.cpp
  src/ext/yuni/src/yuni/io/filename-manipulation.cpp
  src/ext/yuni/src/yuni/io/filename-manipulation.h
  src/libs/antares/exception/antares/exception/InitializationError.hpp
  src/libs/antares/resources/resources.cpp
  src/libs/antares/sys/include/antares/sys/policy.h
  src/libs/antares/sys/policy.cpp
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/tools/batchrun/main.cpp
  src/ui/simulator/application/application.cpp
  src/ui/simulator/toolbox/components/datagrid/component.cpp
  src/ui/simulator/windows/studylogs.cpp
Labels: size/L, cleaning, code quality

#1725 [CI] Add sirius lib to PATH
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  src/tests/end-to-end/binding_constraints/CMakeLists.txt
  src/tests/end-to-end/simple_study/CMakeLists.txt
  src/tests/src/solver/infeasible-problem-analysis/CMakeLists.txt
Labels: size/S

#1806 Remove Study::gotFatalError, throw exceptions instead
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/antares/exception/LoadingError.hpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.h
  src/solver/application/application.cpp
Labels: size/M

#1851 Fail if OR-Tools solver is not found
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/antares/exception/LoadingError.hpp
  src/solver/application/application.cpp
  src/solver/misc/options.cpp
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/solver/utils/ortools_utils.cpp
Labels: enhancement, size/M

#1846 Remove `mutable` keyword from `PROBLEME_HEBDO`
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
  src/solver/optimisation/opt_calcul_des_pmin_MUT_MDT.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_pmin.cpp
  src/solver/optimisation/opt_init_minmax_groupes_couts_demarrage.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
Labels: size/M, cleaning, code quality

#1850 Add precision about `enabled` field in ST storage
  docs/reference-guide/13-file-format.md
Labels: size/XS, doc

#1852 Add possibility to release without running any tests
  .github/workflows/new_release.yml
  .github/workflows/ubuntu.yml
Labels: size/M

#1855 Use `std::unordered_map` for tmpDataByArea_ (hydro ventilation)
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
Labels: size/M, code quality

#1856 Fix workflows/new_release.yml
  .github/workflows/new_release.yml
Labels: size/XS, ci

#1857 Circumvent runner bug where input type is lost
  .github/workflows/new_release.yml
  .github/workflows/ubuntu.yml
Labels: size/XS

#1859 Publish assets as part of the `build` job to get access to environment variables
  .github/workflows/ubuntu.yml
Labels: size/S
