Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2023-04, with the labels that each got.

#1244 [CLEAN] Remove ThermalCluster::coupling
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster_list.cpp
Labels: size/L, cleaning

#1230 Refactor thermal state
  src/solver/variable/adequacy/overallCost.h
  src/solver/variable/area.inc.hxx
  src/solver/variable/commons/links/links.h.inc.hxx
  src/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/economy/dispatchableGeneration.h
  src/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/economy/shortTermStorage.h
  src/solver/variable/economy/shortTermStorageLevels.h
  src/solver/variable/economy/thermalAirPollutantEmissions.h
  src/solver/variable/endoflist.h
  src/solver/variable/setofareas.h
  src/solver/variable/setofareas.hxx
  src/solver/variable/state.cpp
  src/solver/variable/state.h
  src/solver/variable/variable.h
  src/solver/variable/variable.hxx
Labels: size/L, cleaning

#1246 Validation of inputs for sts
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.h
Labels: size/L, code, Short term storage

#1220 Document I/O format changes related to short-term storage
  .githooks/pre-commit
  docs/reference-guide/13-file-format.md
Labels: size/M, doc, Short term storage

#1195 Refactor CBuilder::Update()
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/grid.hxx
Labels: size/L, cleaning, refactoring

#1243 Fix/remove old versions
  .github/workflows/ubuntu.yml
  src/analyzer/atsp/load.cpp
  src/analyzer/atsp/misc.cpp
  src/libs/antares/array/correlation.cpp
  src/libs/antares/array/correlation.h
  src/libs/antares/array/correlation.hxx
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/links.h
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/cleaner/cleaner.cpp
  src/libs/antares/study/constraint/constraint.cpp
  src/libs/antares/study/constraint/constraint.h
  src/libs/antares/study/correlation-updater.hxx
  src/libs/antares/study/finder/finder.cpp
  src/libs/antares/study/header.cpp
  src/libs/antares/study/load.cpp
  src/libs/antares/study/output.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/prepro.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/load/prepro.cpp
  src/libs/antares/study/parts/load/prepro.h
  src/libs/antares/study/parts/solar/prepro.cpp
  src/libs/antares/study/parts/solar/prepro.h
  src/libs/antares/study/parts/solar/series.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/libs/antares/study/parts/wind/prepro.cpp
  src/libs/antares/study/parts/wind/prepro.h
  src/libs/antares/study/scenario-builder/sets.cpp
  src/libs/antares/study/study.h
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/libs/antares/study/xcast/xcast.cpp
  src/libs/antares/study/xcast/xcast.h
  src/libs/antares/utils.h
  src/libs/antares/utils.hxx
  src/solver/variable/state.cpp
  src/tools/cleaner/main.cpp
  src/tools/kirchhoff-cbuilder/main.cpp
  src/tools/updater/main.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/windows/output/job.cpp
  src/ui/simulator/windows/output/panel/area-link.cpp
Labels: size/XXL, cleaning

#1249 Introduce weekly checks after loading the calendar
  src/libs/antares/constants.cpp
  src/libs/antares/constants.h
  src/libs/antares/date/date.cpp
  src/libs/antares/date/date.h
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/load.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/economy.cpp
Labels: size/M

#1253 ST storage : fix a bug on adq-patch tests due to a previous merge
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/XS, adq-patch, ci

#1252 Scratchpad: remove unused data members, functions
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/area/scratchpad.h
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_optimisation_hebdo.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
Labels: size/L, cleaning, code

#1254 Remove deprecated structures for calendar
  src/libs/antares/date/date.cpp
  src/libs/antares/date/date.h
  src/libs/antares/study/runtime/runtime.cpp
  src/solver/variable/storage/intermediate.cpp
Labels: size/L, cleaning

#1257 Clean up `runtime.h/runtime.cpp`
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/runtime/runtime.h
Labels: size/M, cleaning

#1255 Fix checks for inflows/cycles
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input.cpp
Labels: size/M, Short term storage

#1264 Fix bound on unsupplied energy when local matching is disabled
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Labels: size/XS, adq-patch

#1266 Scratchpad refactoring
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/area/scratchpad.h
  src/libs/antares/study/runtime/runtime.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/max-mrg.cpp
  src/solver/variable/state.h
  src/solver/variable/state.hxx
Labels: size/M, cleaning

#1247 Make LMR optional with new option
  docs/reference-guide/13-file-format.md
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/solver/application.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, adq-patch

#1270 Temporary PR to transfer RTEi-CR20 branch from RTEi repo to RTE repo
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/13-file-format.md
  src/libs/antares/CMakeLists.txt
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/LoadingError.hpp
  src/libs/antares/study/action/handler/antares-study/area/ts-node.cpp
  src/libs/antares/study/estimate.memory-footprint.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster.hxx
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/parts/thermal/ecoInput.hxx
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/solver/application.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/economy/profitByPlant.h
  src/solver/variable/state.cpp
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalmodulation.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/constants.cpp
  src/ui/simulator/windows/inspector/constants.h
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/frame.h
  src/ui/simulator/windows/inspector/property.update.cpp
  src/ui/simulator/windows/thermal/panel.cpp
  src/ui/simulator/windows/thermal/panel.h
Labels: size/XL

#1271 Temporary PR to transfer RTEi-CR22 branch from RTEi repo to RTE repo
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/action/handler/antares-study/area/timeseries.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/solver/hydro/CMakeLists.txt
  src/solver/hydro/daily/h2o_j_donnees_mensuelles.h
  src/solver/hydro/daily/h2o_j_free.c
  src/solver/hydro/daily/h2o_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily/h2o_j_instanciation.c
  src/solver/hydro/daily2/h2o2_j_donnees_mensuelles.h
  src/solver/hydro/daily2/h2o2_j_free.cpp
  src/solver/hydro/daily2/h2o2_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily2/h2o2_j_instanciation.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/h2o_m_donnees_annuelles.h
  src/solver/hydro/monthly/h2o_m_free.c
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.c
  src/solver/hydro/monthly/h2o_m_instanciation.c
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/ts-generator/hydro.cpp
  src/solver/variable/commons/hydro.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
  src/ui/simulator/windows/hydro/series.cpp
Labels: size/XL

#1274 Fix test issues
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
Labels: size/XS

#1275 skip mingen in sim_calc_economique if <8.6v
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/S, RTE-i

#1276 CR22 Minimum Hydro Gen
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/solver/hydro/daily/h2o_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/daily2/h2o2_j_donnees_mensuelles.h
  src/solver/hydro/daily2/h2o2_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.c
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/commons/hydro.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
  src/ui/simulator/windows/hydro/series.cpp
Labels: size/L, RTE-i

#1278 CR22 Minimum Hydro Gen
  src/solver/hydro/daily/h2o_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/ui/simulator/windows/hydro/series.cpp
Labels: size/M, RTE-i

#1279 Thermal price definition code smells
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster.hxx
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/parts/thermal/ecoInput.hxx
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/solver/application.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/timeseries.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/M, RTE-i
