Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-08, with the labels that each got.

#2298 Use std::unique_ptr
  src/solver/expressions/include/antares/solver/expressions/Add.h
  src/solver/expressions/include/antares/solver/expressions/Negate.h
  src/solver/expressions/main.cpp
Labels: size/S

#2291 Remove spurious assert(false), fix debug binaries
  src/solver/variable/include/antares/solver/variable/endoflist.h
Labels: size/XS

#2304 Fix reset order
  src/solver/simulation/include/antares/solver/simulation/solver_utils.h
Labels: bug, size/XS

#2309 use unique ptr
  src/solver/expressions/include/antares/solver/expressions/memory-registry.hxx
Labels: size/M

#2310 fix links
  README.md
Labels: size/M

#2312 update AUTHORS.txt
  AUTHORS.txt
Labels: size/S

#2313 Create visitors & nodes subdirectories
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/NegationNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/AddNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ComponentNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ExpressionsNodes.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Leaf.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NegationNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Node.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NodesForwardDeclaration.h
  src/solver/expressions/include/antares/solver/expressions/nodes/PortFieldNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CloneVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvalVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/PrintVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/Visitor.h
  src/solver/expressions/main.cpp
  src/solver/expressions/nodes/AddNode.cpp
  src/solver/expressions/nodes/ComponentNode.cpp
  src/solver/expressions/nodes/NegationNode.cpp
  src/solver/expressions/nodes/PortFieldNode.cpp
  src/solver/expressions/visitors/CloneVisitor.cpp
  src/solver/expressions/visitors/EvalVisitor.cpp
  src/solver/expressions/visitors/PrintVisitor.cpp
Labels: size/L

#2314 Add tests for expression visitors
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/main.cpp
  src/solver/expressions/visitors/PrintVisitor.cpp
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2319 Add VariableNode properly
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/nodes/ExpressionsNodes.h
  src/solver/expressions/include/antares/solver/expressions/nodes/LiteralNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NodesForwardDeclaration.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ParameterNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/VariableNode.h
Labels: size/M

#2320 Force color output in cmake
  src/cmake/common-settings.cmake
Labels: size/XS

#2322 Fix Windows Debug version crash
  src/solver/simulation/include/antares/solver/simulation/solver_utils.h
Labels: size/XS

#2315 Free up space for SonarCloud job
  .github/workflows/sonarcloud.yml
Labels: size/S, ci

#2323 Fix build
  src/solver/expressions/include/antares/solver/expressions/nodes/ExpressionsNodes.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NodesForwardDeclaration.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CloneVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvalVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/PrintVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/Visitor.h
  src/solver/expressions/visitors/CloneVisitor.cpp
  src/solver/expressions/visitors/EvalVisitor.cpp
  src/solver/expressions/visitors/PrintVisitor.cpp
  src/solver/hydro/management/HydroInputsChecker.cpp
Labels: size/M

#2324 Shorter lock for mutex
  src/solver/expressions/include/antares/solver/expressions/Registry.hxx
Labels: size/XS

#2302 Short term storage costs [ANT-1854]
  src/libs/antares/study/include/antares/study/parts/short-term-storage/series.h
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/include/antares/solver/simulation/sim_spread_generator.h
  src/solver/simulation/sim_spread_generator.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: enhancement, size/L, Short term storage

#2326 Lighten code for LinearOperations
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearStatus.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearVisitor.h
  src/solver/expressions/visitors/LinearStatus.cpp
  src/solver/expressions/visitors/LinearVisitor.cpp
Labels: size/L

#2328 Fix build warnings & errors
  src/solver/expressions/include/antares/solver/expressions/nodes/PortFieldNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearStatus.h
  src/solver/expressions/nodes/BinaryNode.cpp
  src/solver/expressions/nodes/UnaryNode.cpp
Labels: size/S

#2325 linear visitor
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearStatus.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearVisitor.h
  src/solver/expressions/nodes/BinaryNode.cpp
  src/solver/expressions/nodes/UnaryNode.cpp
  src/solver/expressions/visitors/LinearVisitor.cpp
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2332 Move tryFunction out of class
  src/solver/expressions/include/antares/solver/expressions/nodes/NodeVisitor.h
Labels: size/M

#2334 avoid to break constness && dynamic cast
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/XS

#2331 Expressions : remove class ParentNode
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/nodes/BinaryNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ParentNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/UnaryNode.h
  src/solver/expressions/nodes/BinaryNode.cpp
  src/solver/expressions/nodes/UnaryNode.cpp
  src/solver/expressions/visitors/CloneVisitor.cpp
  src/solver/expressions/visitors/EvalVisitor.cpp
  src/solver/expressions/visitors/LinearityVisitor.cpp
  src/solver/expressions/visitors/PrintVisitor.cpp
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2336 Update simtest version, 9.2.0c
  simtest.json
Labels: size/XS

#2034 Fix/rhs hydro power constraint
  docs/user-guide/solver/06-hydro-heuristics.md
  src/solver/hydro/management/daily.cpp
Labels: size/M

#2338 Use const char** for argv, remove function `prepareArgs`
  src/analyzer/main.cpp
  src/ext/yuni/src/yuni/core/getopt/parser.cpp
  src/ext/yuni/src/yuni/core/getopt/parser.h
  src/libs/antares/args/args_to_utf8.cpp
  src/libs/antares/args/include/antares/args/args_to_utf8.h
  src/libs/antares/file-tree-study-loader/FileTreeStudyLoader.cpp
  src/libs/antares/resources/include/antares/resources/resources.h
  src/libs/antares/resources/resources.cpp
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/solver/main.cpp
  src/solver/misc/include/antares/solver/misc/write-command-line.h
  src/solver/misc/write-command-line.cpp
  src/tools/batchrun/main.cpp
  src/tools/config/main.cpp
  src/tools/finder/main.cpp
  src/tools/kirchhoff-cbuilder/kirchhoff-cbuilder.h
  src/tools/kirchhoff-cbuilder/main.cpp
  src/tools/ts-generator/include/antares/tools/ts-generator/tsGenerationOptions.h
  src/tools/ts-generator/main.cpp
  src/tools/ts-generator/tsGenerationOptions.cpp
  src/tools/updater/main.cpp
  src/tools/vacuum/main.cpp
  src/tools/yby-aggregator/main.cpp
  src/ui/simulator/application/application.cpp
  src/ui/simulator/main.cpp
Labels: size/L, cleaning, code quality

#2337 Enable parallel run for API
  src/libs/antares/file-tree-study-loader/FileTreeStudyLoader.cpp
Labels: size/XS

#2342 Add comparison visitor, using variadic template arguments
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/nodes/ComponentNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/PortFieldNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CompareVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
  src/solver/expressions/nodes/ComponentNode.cpp
  src/solver/expressions/nodes/PortFieldNode.cpp
  src/solver/expressions/visitors/CompareVisitor.cpp
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2343 Use enum class & free functions for `LinearStatus`, add unit tests
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearStatus.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearityVisitor.h
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2348 Remove useless ;, macro definition
  src/libs/antares/InfoCollection/include/antares/infoCollection/StudyInfoCollector.h
  src/libs/antares/locator/locator.cpp
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/libs/antares/array/matrix-bypass-load.h
Labels: size/M, code

#2333 Substitution from context visitor
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/SubstitutionVisitor.h
  src/solver/expressions/visitors/SubstitutionVisitor.cpp
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2350 Revert "Fix/rhs hydro power constraint (#2034)"
  docs/user-guide/solver/06-hydro-heuristics.md
  src/solver/hydro/management/daily.cpp
Labels: size/M

#2346 Fix various compilation warnings
  src/libs/antares/benchmarking/DurationCollector.cpp
  src/libs/antares/utils/utils.cpp
  src/libs/antares/writer/zip_writer.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/src/libs/antares/writer/test_writer.cpp
Labels: size/S

#2349 enum case
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndex.h
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndexVisitor.h
  src/solver/expressions/visitors/LinearityVisitor.cpp
  src/solver/expressions/visitors/TimeIndexVisitor.cpp
  src/tests/src/solver/expressions/test_expressions.cpp
Labels: size/L

#2352 Split expression-lib tests
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/expressions/test_CloneVisitor.cpp
  src/tests/src/solver/expressions/test_CompareVisitor.cpp
  src/tests/src/solver/expressions/test_LinearVisitor.cpp
  src/tests/src/solver/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/solver/expressions/test_SubstitutionVisitor.cpp
  src/tests/src/solver/expressions/test_TimeIndexVisitor.cpp
  src/tests/src/solver/expressions/test_expressions.cpp
  src/tests/src/solver/expressions/test_main.cpp
Labels: size/XXL

#2351 Fix LinearVisitor behavior for comparison nodes, add tests
  src/solver/expressions/include/antares/solver/expressions/visitors/CloneVisitor.h
  src/solver/expressions/visitors/CloneVisitor.cpp
  src/solver/expressions/visitors/LinearityVisitor.cpp
  src/tests/src/solver/expressions/test_LinearVisitor.cpp
Labels: size/L

#2353 Add tests with slightly larger trees
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/expressions/test_DeepWideTrees.cpp
Labels: size/M

#2355 Remove unused headers
  src/tests/src/solver/expressions/test_CloneVisitor.cpp
  src/tests/src/solver/expressions/test_CompareVisitor.cpp
  src/tests/src/solver/expressions/test_DeepWideTrees.cpp
  src/tests/src/solver/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/solver/expressions/test_SubstitutionVisitor.cpp
Labels: size/XS

#2357 Increase test coverage for TimeIndexVisitor
  src/tests/src/solver/expressions/test_TimeIndexVisitor.cpp
Labels: size/M

#2356 Fix operator for boost data
  src/tests/src/solver/expressions/test_LinearVisitor.cpp
Labels: size/XS

#2274 Remove duplication in simulation run
  src/api/API.cpp
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/adequacy_mode.cpp
  src/solver/simulation/economy_mode.cpp
  src/solver/simulation/include/antares/solver/simulation/economy_mode.h
  src/solver/simulation/include/antares/solver/simulation/simulation-run.h
  src/solver/simulation/simulation-run.cpp
Labels: size/L

#2279 Districts : simplifying the code
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/sets.cpp
  src/libs/antares/study/include/antares/study/sets.h
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/study.cpp
  src/solver/variable/include/antares/solver/variable/setofareas.h
Labels: size/XL

#2340 Fix clang++ warning about typeid
  src/solver/infeasible-problem-analysis/report.cpp
Labels: size/XS, code, build

#2344 Disable CMAKE_COLOR_DIAGNOSTICS
  src/cmake/common-settings.cmake
Labels: size/XS

#2359 Use default operator==
  src/solver/expressions/include/antares/solver/expressions/nodes/ComponentNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Node.h
  src/solver/expressions/include/antares/solver/expressions/nodes/PortFieldNode.h
  src/solver/expressions/nodes/ComponentNode.cpp
  src/solver/expressions/nodes/PortFieldNode.cpp
Labels: size/S

#2361 doxygen doc for expression lib
  src/solver/expressions/include/antares/solver/expressions/nodes/BinaryNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ComparisonNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ComponentNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/DivisionNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/EqualNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/GreaterThanOrEqualNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Leaf.h
  src/solver/expressions/include/antares/solver/expressions/nodes/LessThanOrEqualNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/LiteralNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/MultiplicationNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NegationNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Node.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ParameterNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/PortFieldNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/SubtractionNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/UnaryNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/VariableNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CloneVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CompareVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvalVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvaluationContext.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearStatus.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearityVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/PrintVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/SubstitutionVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndex.h
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndexVisitor.h
Labels: size/L, doc

#2363 Remove manually allocated memory
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/include/antares/study/parts/load/container.h
  src/libs/antares/study/include/antares/study/parts/solar/container.h
  src/libs/antares/study/include/antares/study/parts/wind/container.h
  src/libs/antares/study/include/antares/study/progression/progression.h
  src/libs/antares/study/include/antares/study/progression/progression.hxx
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/load/container.cpp
  src/libs/antares/study/parts/solar/container.cpp
  src/libs/antares/study/parts/wind/container.cpp
  src/libs/antares/study/study.cpp
  src/solver/ts-generator/generator.cpp
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/xcast/studydata.h
  src/solver/ts-generator/xcast/studydata.cpp
  src/solver/ts-generator/xcast/xcast.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/hydroprepro.cpp
Labels: size/L, cleaning

#2366 Simplify recursion for deepAddTree function
  src/tests/src/solver/expressions/test_DeepWideTrees.cpp
Labels: size/S, tests

#2362 optimize trytype loop
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
Labels: size/M
