Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-11, with the labels that each got.

#2481 Fix study not found on windows when using simulator API
  src/libs/antares/file-tree-study-loader/FileTreeStudyLoader.cpp
  src/libs/antares/file-tree-study-loader/include/antares/file-tree-study-loader/FileTreeStudyLoader.h
Labels: size/XS

#2479 Migration doc : move final hydro level from v8.7.0 to v9.2.0
  docs/user-guide/04-migration-guides.md
Labels: size/XS

#2469 Don't apply reverse spinning if the cluster is no force gen [ANT-2293]
  src/libs/antares/study/parts/thermal/cluster.cpp
Labels: bug, size/M

#2484 Fix path for ts-numbers in output dir
  src/libs/antares/study/parts/common/cluster_list.cpp
Labels: bug, size/XS

#2485 Remove unused function in opt
  src/solver/optimisation/include/antares/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
Labels: size/S, cleaning

#2466 8.8 solver parameters [ANT-2280]
  docs/CHANGELOG.md
  docs/reference-guide/10-command_line.md
  src/libs/antares/CMakeLists.txt
  src/libs/antares/InfoCollection/StudyInfoCollector.cpp
  src/libs/antares/checks/antares/checks/checkLoadedInputData.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/antares/exception/LoadingError.hpp
  src/libs/antares/optimization-options/CMakeLists.txt
  src/libs/antares/optimization-options/include/antares/optimization-options/options.h
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/load-options.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/solver/CMakeLists.txt
  src/solver/application/application.cpp
  src/solver/misc/include/antares/solver/misc/options.h
  src/solver/misc/options.cpp
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/utils/CMakeLists.txt
  src/solver/utils/include/antares/solver/utils/named_problem.h
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/solver/utils/include/antares/solver/utils/ortools_wrapper.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/ortools_utils.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tools/batchrun/main.cpp
Labels: size/XL

#2468 8.8: Don't apply reverse spinning if the cluster is no force gen [ANT-2293]
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/test_study.cpp
Labels: bug, size/M

#2488 Fix documentation for hydro heuristic
  docs/user-guide/solver/06-hydro-heuristics.md
Labels: size/M

#2487 Few improvements to solver specific options handling
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/checks/include/antares/checks/checkLoadedInputData.h
  src/libs/antares/exception/CMakeLists.txt
  src/libs/antares/exception/LoadingError.cpp
  src/solver/application/application.cpp
  src/solver/misc/options.cpp
  src/tools/batchrun/main.cpp
Labels: size/M, code quality

#2465 Changelog 9.2
  docs/developer-guide/CHANGELOG.md
Labels: size/L, doc

#2483 Unit test for reverse calculation
  src/tests/src/libs/antares/study/test_study.cpp
Labels: size/M, tests

#2493 magic
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
  src/solver/expressions/visitors/NodeVisitor.cpp
Labels: size/M

#2475 Fix build errors caused by conflicts between windows.h and antlr4-runtime.h
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/AstDOTStyleVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
  src/solver/expressions/visitors/EvalVisitor.cpp
  src/solver/expressions/visitors/NodeVisitor.cpp
Labels: size/M

#2482 [skip ci] Migration doc : move hydro level from v8.7.0 to v9.2.0
  docs/user-guide/04-migration-guides.md
Labels: size/XS, doc

#2494 Polish changelog for v9.2
  docs/developer-guide/CHANGELOG.md
Labels: size/XS, doc

#2438 Place CSR after hydro remix [ANT-2070]
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
Labels: size/S

#2486 9.2.0-rc5
  docs/developer-guide/CHANGELOG.md
  sonar-project.properties
  src/CMakeLists.txt
  src/vcpkg.json
Labels: size/L

#2501 Don't pass a registry to ModelConverter::convert
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/NodeRegistry.cpp
  src/solver/expressions/include/antares/solver/expressions/NodeRegistry.h
  src/solver/expressions/include/antares/solver/expressions/Registry.hxx
  src/solver/modelConverter/convertorVisitor.cpp
  src/solver/modelConverter/include/antares/solver/modelConverter/convertorVisitor.h
  src/solver/modelConverter/include/antares/solver/modelConverter/modelConverter.h
  src/solver/modelConverter/modelConverter.cpp
  src/study/system-model/CMakeLists.txt
  src/study/system-model/include/antares/study/system-model/constraint.h
  src/study/system-model/include/antares/study/system-model/expression.h
  src/study/system-model/include/antares/study/system-model/library.h
  src/study/system-model/include/antares/study/system-model/model.h
  src/study/system-model/include/antares/study/system-model/variable.h
  src/study/system-model/library.cpp
  src/study/system-model/model.cpp
  src/tests/src/solver/modelParser/testConvertorVisitor.cpp
  src/tests/src/solver/modelParser/testModelTranslator.cpp
  src/tests/src/solver/modelParser/test_full.cpp
Labels: size/L

#2500 New System model (2.2) [ANT-2208]
  src/study/system-model/CMakeLists.txt
  src/study/system-model/component.cpp
  src/study/system-model/include/antares/study/system-model/component.h
  src/study/system-model/include/antares/study/system-model/system.h
  src/study/system-model/system.cpp
  src/tests/src/CMakeLists.txt
  src/tests/src/study/CMakeLists.txt
  src/tests/src/study/system-model/CMakeLists.txt
  src/tests/src/study/system-model/test_component.cpp
  src/tests/src/study/system-model/test_main.cpp
  src/tests/src/study/system-model/test_system.cpp
  src/tests/src/utils/unit_test_utils.h
Labels: size/XL

#2503 Use thread-safe version of localtime
  src/libs/antares/utils/utils.cpp
Labels: size/S

#2491 [ANT-2300] Short-term storage: penalty for storage control, injection and withdrawal flow gradient
  docs/user-guide/04-migration-guides.md
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/series.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/constraints/Group1.cpp
  src/solver/optimisation/constraints/ShortTermStorageCostVariation.cpp
  src/solver/optimisation/constraints/ShortTermStorageCostVariationInjectionBackward.cpp
  src/solver/optimisation/constraints/ShortTermStorageCostVariationInjectionForward.cpp
  src/solver/optimisation/constraints/ShortTermStorageCostVariationWithdrawalBackward.cpp
  src/solver/optimisation/constraints/ShortTermStorageCostVariationWithdrawalForward.cpp
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/include/antares/solver/optimisation/constraints/Group1.h
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ShortTermStorageCostVariation.h
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ShortTermStorageLevel.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_rename_problem.h
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/optimisation/opt_rename_problem.cpp
  src/solver/optimisation/variables/VariableManagement.cpp
  src/solver/optimisation/variables/VariableManagement.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: size/XXL

#2505 Fix build after the removal of bool OptimizationOptions::ortoolsUsed
  src/tests/src/api_internal/test_api.cpp
Labels: size/XS, build

#2508 Fix timestamp = 0 in file info.antares-output (ANT-2494)
  src/libs/antares/study/study.cpp
Labels: size/XS
