Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-12, with the labels that each got.

#2515 Rename thread_number -> numSpace for consistency
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.h
  src/solver/optimisation/include/antares/solver/optimisation/optim_post_process_list.h
  src/solver/optimisation/include/antares/solver/optimisation/post_process_commands.h
  src/solver/optimisation/optim_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/base_post_process.cpp
  src/solver/simulation/include/antares/solver/simulation/base_post_process.h
Labels: size/M

#2517 Fix variable bounds for 1st week in the year
  src/solver/optimisation/LegacyFiller.cpp
Labels: size/S

#2516 Segfault when there's more districts than areas [ANT-2452]
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: bug, size/XS

#2518 Fix uninitialized CSR variables [ANT-2496]
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/solver/optimisation/post_process_commands.cpp
Labels: size/M, 8.8

#2520 9.2 rc 6
  src/CMakeLists.txt
Labels: size/XS

#2521 Bump simtest to 9.2f
  simtest.json
Labels: size/XS

#2510 Fix/centos build (#2509)
  .github/workflows/centos7.yml
  docker/AntaresDeps
  docker/Dockerfile
Labels: size/L, build

#2522 Fix cost for ST storage
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
Labels: size/S

#2523 Fix launch studies with empty solver
  src/ui/simulator/application/study.cpp
Labels: bug, size/XS, GUI

#2524 Default solver in GUI
  src/ui/simulator/windows/simulation/run.cpp
Labels: bug, size/XS, GUI

#2525 Fix function `ThermalCluster::getMarketBidCost` [ANT-2527]
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
Labels: size/M

#2514 Add compatibility parameter for hydro pmax I/O [ANT-2278]
  simtest.json
  src/CMakeLists.txt
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/include/antares/study/parts/hydro/series.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
Labels: size/L

#2528 Fix build for CentOS7/OL8
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearConstraintVisitor.h
Labels: size/XS

#2534 Add a warning if sts group property is empty [ANT-2026]
  src/libs/antares/study/parts/short-term-storage/properties.cpp
Labels: bug, size/XS

#2533 Use sirius-solver@antares-integration-v1.6
  src/ports/sirius-solver/portfile.cmake
Labels: size/XS

#2537 Fix find cluster logic
  src/libs/antares/study/parts/short-term-storage/container.cpp
Labels: size/S

#2536 Remove getMemberFunction, use factory pattern
  src/solver/optimisation/constraints/ShortTermStorageCumulation.cpp
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ShortTermStorageCumulation.h
Labels: size/L, code quality

#2542 Remove getErrorMessage, use dedicated struct
  src/libs/antares/study/include/antares/study/parts/short-term-storage/AdditionalConstraint.h
  src/libs/antares/study/parts/short-term-storage/AdditionalConstraint.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
Labels: size/M

#2539 Modeler 2.5a: Add parameters and YAML parser
  src/CMakeLists.txt
  src/libs/antares/io/CMakeLists.txt
  src/libs/antares/io/include/antares/io/file.h
  src/solver/modelParser/CMakeLists.txt
  src/solver/modeler/CMakeLists.txt
  src/solver/modeler/parameters/CMakeLists.txt
  src/solver/modeler/parameters/encoder.hxx
  src/solver/modeler/parameters/include/antares/solver/modeler/parameters/modelerParameters.h
  src/solver/modeler/parameters/include/antares/solver/modeler/parameters/parseModelerParameters.h
  src/solver/modeler/parameters/parseModelerParameters.cpp
  src/solver/systemParser/CMakeLists.txt
  src/tests/src/libs/antares/yaml-parser/CMakeLists.txt
  src/tests/src/solver/modeler/CMakeLists.txt
  src/tests/src/solver/modeler/parameters/CMakeLists.txt
  src/tests/src/solver/modeler/parameters/testParametersParsing.cpp
Labels: size/L, Modeleur

#2538 Activate long tests on branch release/8.8.x
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#2543 Fix segfault caused by invalid index [ANT-2582]
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.cpp
Labels: bug, size/XS

#2544 Fix segfault caused by invalid index [ANT-2582]
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.cpp
Labels: bug, size/XS, 8.8

#2545 Add and use add_boost_test CMake helper function
  src/tests/end-to-end/binding_constraints/CMakeLists.txt
  src/tests/end-to-end/simple_study/CMakeLists.txt
  src/tests/macros.cmake
  src/tests/src/api_internal/CMakeLists.txt
  src/tests/src/api_lib/CMakeLists.txt
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/antlr4-interface/CMakeLists.txt
  src/tests/src/libs/antares/benchmarking/CMakeLists.txt
  src/tests/src/libs/antares/concurrency/CMakeLists.txt
  src/tests/src/libs/antares/inifile/CMakeLists.txt
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/area/CMakeLists.txt
  src/tests/src/libs/antares/study/constraint/CMakeLists.txt
  src/tests/src/libs/antares/study/output-folder/CMakeLists.txt
  src/tests/src/libs/antares/study/parameters/CMakeLists.txt
  src/tests/src/libs/antares/study/parts/hydro/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
  src/tests/src/libs/antares/study/series/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/CMakeLists.txt
  src/tests/src/libs/antares/study/thermal-price-definition/CMakeLists.txt
  src/tests/src/libs/antares/writer/CMakeLists.txt
  src/tests/src/libs/antares/yaml-parser/CMakeLists.txt
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/tests/src/solver/lps/CMakeLists.txt
  src/tests/src/solver/modelParser/CMakeLists.txt
  src/tests/src/solver/modeler/api/CMakeLists.txt
  src/tests/src/solver/modeler/parameters/CMakeLists.txt
  src/tests/src/solver/optim-model-filler/CMakeLists.txt
  src/tests/src/solver/optimisation/adequacy_patch/CMakeLists.txt
  src/tests/src/solver/optimisation/name-translator/CMakeLists.txt
  src/tests/src/solver/optimisation/translator/CMakeLists.txt
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/utils/CMakeLists.txt
  src/tests/src/study/system-model/CMakeLists.txt
Labels: size/XXL

#2547 rc 8
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
  src/CMakeLists.txt
Labels: size/S
