Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-01, with the labels that each got.

#1841 Add tests on short-term storage/thermal cluster/renewable cluster removal
  src/tests/src/libs/antares/study/test_study.cpp
Labels: tests

#1863 Remove YUNI_STATIC_ASSERT
  src/libs/antares/study/sets.hxx
  src/libs/antares/study/version.cpp
Labels: size/S, cleaning, code quality

#1865 Use dedicated URL path for Doxygen, instead of root
  .github/workflows/doxygen.yml
  README.md
Labels: size/XS

#1867 Fix HTML generation for readthedocs
  readthedocs.yml
Labels: size/XS

#1868 updating python version for readthedocs
  readthedocs.yml
Labels: size/XS

#1860 Fix new release GH workflow
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/L

#1752 Simplify TS numbers drawings, fix bug related to refresh & local thermal generation
  src/libs/antares/constants.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/area.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.h
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/hydro/series.h
  src/libs/antares/study/parts/solar/container.cpp
  src/solver/simulation/solver.hxx
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/simulation/timeseries-numbers.h
  src/solver/ts-generator/CMakeLists.txt
  src/solver/ts-generator/generator.cpp
  src/solver/ts-generator/generator.h
  src/solver/ts-generator/generator.hxx
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/thermal.cpp
  src/solver/ts-generator/xcast/core.cpp
  src/solver/ts-generator/xcast/gamma-euler.cpp
  src/solver/ts-generator/xcast/gamma-inc.cpp
  src/solver/ts-generator/xcast/math.cpp
  src/solver/ts-generator/xcast/math.hxx
  src/solver/ts-generator/xcast/predicate.hxx
  src/solver/ts-generator/xcast/studydata.cpp
  src/solver/ts-generator/xcast/studydata.h
  src/solver/ts-generator/xcast/studydata.hxx
  src/solver/ts-generator/xcast/xcast.cpp
  src/solver/ts-generator/xcast/xcast.h
  src/solver/ts-generator/xcast/xcast.hxx
  src/solver/variable/economy/max-mrg.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/XL, refactoring, code quality, 🚨 Don't Merge

#1871 Release notes for v8.8.1
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/M

#1870 Clean src/libs
  src/libs/antares/CMakeLists.txt
  src/libs/antares/Enum.hxx
  src/libs/antares/net/net.h
  src/libs/antares/net/request.h
  src/libs/antares/object/CMakeLists.txt
  src/libs/antares/object/intrusive-reference.h
  src/libs/antares/object/intrusive-reference.hxx
  src/libs/antares/object/object.h
  src/libs/antares/object/object.hxx
  src/libs/antares/stdcxx/CMakeLists.txt
  src/libs/antares/stdcxx/class_name.cpp
  src/libs/antares/stdcxx/demangle.cpp
  src/libs/antares/stdcxx/include/antares/stdcxx/class_name.h
  src/libs/antares/stdcxx/include/antares/stdcxx/demangle.hpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/study.h
  src/ui/action/CMakeLists.txt
Labels: size/XL, cleaning

#1872 Use SimTest 8.8.1
  simtest.json
Labels: size/XS

#1876 Fix segfault caused by uninitialized `cluster.series.timeseriesNumbers`
  src/libs/antares/study/parts/common/cluster_list.cpp
Labels: bug, size/XS

#1878 [CI] Don't use runner.name as a key for ubuntu's ccache
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M, ci

#1873 Bump OR-Tools (fix crash with XPRESS)
  docs/build/3-Build.md
  ortools_tag
  src/CMakeLists.txt
Labels: bug, size/XS

#1877 Add changelog info for 8.8.1, 8.8.2
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S, doc

#1879 Use Release|Debug instead of release|debug for `CMAKE_BUILD_TYPE`
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  src/CMakeLists.txt
  src/cmake/common-settings.cmake
  src/cmake/utils.cmake
  src/ext/yuni/src/cmake/common-settings.cmake
  src/ext/yuni/src/cmake/target.cmake
Labels: size/M, ci

#1885 Bump SimTest -> v8.8.2
  simtest.json
Labels: size/XS, tests

#1880 Fix a few compilation warnings
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/parts/hydro/container.cpp
Labels: size/S, code, code quality

#1883 Install gh at start of workflows for CentOS 7 & OracleLinux 8
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
Labels: size/M, ci

#1881 Use reference for variable `NbTermesContraintesPourLesCoutsDeDemarrage`
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.h
  src/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnits.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/constraints/MinDownTime.cpp
  src/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.cpp
  src/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStop.cpp
  src/solver/optimisation/constraints/PMaxDispatchableGeneration.cpp
  src/solver/optimisation/constraints/PMinDispatchableGeneration.cpp
  src/solver/optimisation/constraints/constraint_builder_utils.cpp
  src/solver/optimisation/constraints/constraint_builder_utils.h
Labels: size/M

#1887 Use std::shared_ptr instead of indices for active binding constraints in results
  src/libs/antares/InfoCollection/StudyInfoCollector.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/runtime/runtime.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/bindConstraints.hxx
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
Labels: size/L, code quality

#1888 Upload windows exe in release
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
Labels: bug, size/L, ci

#1749 Scratchpad numspace
  src/libs/antares/study/area/area.h
  src/libs/antares/study/area/list.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/management.h
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/adequacy.h
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-eco-adq.h
  src/solver/simulation/economy.cpp
  src/solver/simulation/economy.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/simulation.h
  src/solver/simulation/solver.hxx
Labels: size/L, cleaning, code quality

#1892 Add changelog for solver-logs
  docs/CHANGELOG.md
  docs/reference-guide/13-file-format.md
Labels: size/XS, doc

#1889 For ST storage, set initial level at t=0 instead of t=167
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
Labels: bug, size/M

#1891 Add STS level constraint to suspect list for infeasible problem analysis
  src/solver/infeasible-problem-analysis/constraint-slack-analysis.h
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/constraint.h
  src/solver/infeasible-problem-analysis/report.cpp
Labels: enhancement, size/M

#1897 Add changelog for v8.8.3
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#1900 Revert fix for STS initial level & version 8.8.3
  docs/CHANGELOG.md
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
Labels: size/S

#1902 Fix invalid index causing segfault in `test-study` test
  src/tests/src/libs/antares/study/test_study.cpp
Labels: bug, size/XS, tests

#1893 Use precompiled OR-TOOLS for Oracle Linux 8 CI
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/oracle8.yml
Labels: size/M, ci
