Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-07, with the labels that each got.

#2216 install gh from rpm
  .github/workflows/centos7.yml
Labels: size/XS

#2203 Harmonize time constants
  src/libs/antares/date/date.cpp
  src/libs/antares/include/antares/antares/constants.h
  src/libs/antares/study/area/scratchpad.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/hydro.cpp
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/categories.h
  src/solver/variable/include/antares/solver/variable/constants.h
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageWithdrawalByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/links/congestionProbability.h
  src/solver/variable/include/antares/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/include/antares/solver/variable/info.h
  src/solver/variable/include/antares/solver/variable/print.h
  src/solver/variable/include/antares/solver/variable/state.h
  src/solver/variable/include/antares/solver/variable/storage/average.h
  src/solver/variable/include/antares/solver/variable/storage/averagedata.h
  src/solver/variable/include/antares/solver/variable/storage/intermediate.h
  src/solver/variable/include/antares/solver/variable/storage/intermediate.hxx
  src/solver/variable/include/antares/solver/variable/storage/minmax-data.h
  src/solver/variable/include/antares/solver/variable/storage/minmax.h
  src/solver/variable/include/antares/solver/variable/storage/raw.h
  src/solver/variable/include/antares/solver/variable/storage/rawdata.h
  src/solver/variable/include/antares/solver/variable/storage/stdDeviation.h
  src/solver/variable/include/antares/solver/variable/variable.h
  src/solver/variable/state.cpp
  src/solver/variable/storage/averagedata.cpp
  src/solver/variable/storage/intermediate.cpp
  src/solver/variable/storage/rawdata.cpp
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: size/XL, code quality

#2218 Fix a few newly-introduced code smells
  src/solver/hydro/include/antares/solver/hydro/management/management.h
  src/solver/hydro/management/PrepareInflows.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/ts-generator/availability.cpp
Labels: size/S, code quality

#2221 Complete hydro logs
  src/solver/hydro/management/HydroInputsChecker.cpp
Labels: size/S

#2204 Collect hydro validation errors
  src/libs/antares/study/CMakeLists.txt
  src/solver/hydro/CMakeLists.txt
  src/solver/hydro/include/antares/solver/hydro/management/HydroErrorsCollector.h
  src/solver/hydro/include/antares/solver/hydro/management/HydroInputsChecker.h
  src/solver/hydro/include/antares/solver/hydro/management/finalLevelValidator.h
  src/solver/hydro/include/antares/solver/hydro/management/hydro-final-reservoir-level-functions.h
  src/solver/hydro/management/HydroErrorsCollector.cpp
  src/solver/hydro/management/HydroInputsChecker.cpp
  src/solver/hydro/management/finalLevelValidator.cpp
  src/solver/hydro/management/hydro-final-reservoir-level-functions.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/tests/src/solver/simulation/test-hydro-final-reservoir-level-functions.cpp
Labels: size/L

#2215 Remove actions dependencies using node js 16
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M, ci, code quality

#2228 Move TS number print
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
Labels: size/XS

#2225 Infeability analyzer : renaming
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/report.h
  src/solver/infeasible-problem-analysis/report.cpp
Labels: size/M

#2230 Always run clang-format on PR
  .github/workflows/clang-format.yml
Labels: size/XS

#2229 Add changelog for minor versions
  docs/developer-guide/CHANGELOG.md
Labels: size/S

#2233 Fix compile, add boost header in CMakelists
  src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/solver/infeasible-problem-analysis/constraint.cpp
Labels: bug, size/XS, build

#2202 TS generator : refactor thermal part
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/tools/ts-generator/include/antares/tools/ts-generator/tsGenerationOptions.h
  src/tools/ts-generator/linksTSgenerator.cpp
  src/tools/ts-generator/main.cpp
  src/tools/ts-generator/tsGenerationOptions.cpp
Labels: size/L

#2223 STS: Withdrawal efficiency [ANT-1862]
  docs/user-guide/04-migration-guides.md
  docs/user-guide/solver/02-inputs.md
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/solver/optimisation/constraints/ShortTermStorageLevel.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: enhancement, size/L, Short term storage

#2227 Infeasibility analyzer : HydroPower constraint
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint-slack-analysis.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint.h
  src/solver/infeasible-problem-analysis/report.cpp
Labels: size/S

#2237 Compilation warnings
  src/solver/hydro/management/finalLevelValidator.cpp
  src/solver/optimisation/HebdoProblemToLpsTranslator.cpp
Labels: size/S, code quality

#2240 Version 9.2
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
Labels: size/XS

#2246 Fix sonarcloud job
  .github/workflows/sonarcloud.yml
Labels: bug, size/XS, ci

#2235 Adequacy Patch regression [ANT-1845]
  src/solver/optimisation/post_process_commands.cpp
Labels: bug, size/XS, adq-patch, to-backport

#2247 9.2 rc 1
  src/CMakeLists.txt
Labels: size/XS

#2248 Keep using node js 16 on centos CI
  .github/workflows/centos7.yml
Labels: bug, size/XS, ci

#2231 Infeasibility more cleaning
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/report.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/L

#2171 Link TS generation : splitting into multiple files
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/solver/application/application.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/tools/ts-generator/CMakeLists.txt
  src/tools/ts-generator/include/antares/tools/ts-generator/linksTSgenerator.h
  src/tools/ts-generator/include/antares/tools/ts-generator/tsGenerationOptions.h
  src/tools/ts-generator/linksTSgenerator.cpp
  src/tools/ts-generator/main.cpp
  src/tools/ts-generator/tsGenerationOptions.cpp
Labels: size/XXL, code quality

#2241 Add tests in CI for version 9.2
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
Labels: size/M, tests, ci

#2253 Rename test-platform to os for windows CI
  .github/workflows/windows-vcpkg.yml
Labels: size/M, ci, code quality

#2257 Fix Sonar issues on #2232
  src/solver/infeasible-problem-analysis/constraint-slack-analysis.cpp
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/report.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/watched-constraints.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/solver/infeasible-problem-analysis/watched-constraints.cpp
Labels: size/M

#2258 Fix bug hydro heuristic with mingen (ANT-1825)
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/XS, to-backport

#2256 Minor fixes, use std::unique_ptr, add safety
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/watched-constraints.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/solver/infeasible-problem-analysis/watched-constraints.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/M

#2259 Make RunTimeInfos static instead of dynamic
  src/api/API.cpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/runtime/runtime.h
  src/libs/antares/study/include/antares/study/runtime/runtime.hxx
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.importprepro.cpp
  src/solver/application/ScenarioBuilderOwner.cpp
  src/solver/application/application.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.hxx
  src/solver/variable/include/antares/solver/variable/adequacy/overallCost.h
  src/solver/variable/include/antares/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/include/antares/solver/variable/economy/links/flowQuad.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnits.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/nonProportionalCost.h
  src/solver/variable/include/antares/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/operatingCost.h
  src/solver/variable/include/antares/solver/variable/economy/overallCost.h
  src/solver/variable/include/antares/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/endoflist.h
  src/solver/variable/state.cpp
  src/solver/variable/storage/averagedata.cpp
  src/solver/variable/storage/intermediate.cpp
  src/solver/variable/storage/rawdata.cpp
  src/solver/variable/surveyresults/surveyresults.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/L

#2264 Use std::type_index
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/watched-constraints.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/solver/infeasible-problem-analysis/watched-constraints.cpp
Labels: size/M

#2232 Infeasibility anaylsis : make it more changeable
  src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/solver/infeasible-problem-analysis/constraint-slack-analysis.cpp
  src/solver/infeasible-problem-analysis/constraint.cpp
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint-slack-analysis.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/report.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/watched-constraints.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/solver/infeasible-problem-analysis/watched-constraints.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/XL

#2254 Remove manual dynamic memory usage
  src/api/API.cpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/progression/progression.h
  src/libs/antares/study/include/antares/study/runtime/runtime.h
  src/libs/antares/study/include/antares/study/runtime/runtime.hxx
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/progression/progression.cpp
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.importprepro.cpp
  src/solver/application/ScenarioBuilderOwner.cpp
  src/solver/application/application.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/include/antares/solver/simulation/solver_utils.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.hxx
  src/solver/variable/include/antares/solver/variable/adequacy/overallCost.h
  src/solver/variable/include/antares/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/include/antares/solver/variable/economy/links/flowQuad.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnits.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/nonProportionalCost.h
  src/solver/variable/include/antares/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/operatingCost.h
  src/solver/variable/include/antares/solver/variable/economy/overallCost.h
  src/solver/variable/include/antares/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/storage/average.h
  src/solver/variable/include/antares/solver/variable/storage/averagedata.h
  src/solver/variable/include/antares/solver/variable/storage/raw.h
  src/solver/variable/include/antares/solver/variable/storage/rawdata.h
  src/solver/variable/state.cpp
  src/solver/variable/storage/averagedata.cpp
  src/solver/variable/storage/intermediate.cpp
  src/solver/variable/storage/rawdata.cpp
  src/solver/variable/surveyresults/surveyresults.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tools/ts-generator/linksTSgenerator.cpp
Labels: size/XL, code quality

#2262 Release 8.8.7
  src/CMakeLists.txt
  src/solver/optimisation/post_process_commands.cpp
  src/tools/batchrun/main.cpp
Labels: size/L

#2270 Remove manual dynamic allocations in Xcast
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/solver/misc/include/antares/solver/misc/cholesky.hxx
  src/solver/ts-generator/include/antares/solver/ts-generator/xcast/xcast.h
  src/solver/ts-generator/xcast/core.cpp
  src/solver/ts-generator/xcast/xcast.cpp
Labels: size/L, code quality

#2275 Remove dynamic allocations
  src/libs/antares/correlation/correlation.cpp
  src/libs/antares/correlation/include/antares/correlation/correlation.h
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/xcast/studydata.cpp
  src/ui/simulator/windows/correlation/correlation.cpp
Labels: size/L

#2249 Infeasibility analyzer : improve unit tests
  src/solver/infeasible-problem-analysis/constraint-slack-analysis.cpp
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/constraint-slack-analysis.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/report.h
  src/solver/infeasible-problem-analysis/report.cpp
  src/solver/infeasible-problem-analysis/watched-constraints.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/L

#2268 Remove useless forward declaration
  src/libs/antares/logs/include/antares/logs/logs.h
Labels: size/S, cleaning

#2278 Fix potential access violation
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/include/antares/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/load.cpp
Labels: size/L

#2277 Use OR-Tools v9.10
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
  src/CMakeLists.txt
Labels: size/S

#2282 Try using devtoolset-11 on CentOS7 to fix build
  .github/workflows/centos7.yml
Labels: size/XS

#2281 Fix Sonar warning: use compile_commands.json
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: size/XS

#2283 Add short-term storage doc for optim model
  docs/user-guide/solver/05-model.md
Labels: size/M

#2273 Remove dynamic manually allocated memory
  src/analyzer/atsp/correlations.cpp
  src/libs/antares/correlation/correlation.cpp
  src/libs/antares/correlation/include/antares/correlation/correlation.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/include/antares/study/sets.h
  src/libs/antares/study/include/antares/study/sets.hxx
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/include/antares/study/study.hxx
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.extra.cpp
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/include/antares/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/load.cpp
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/xcast/studydata.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.cpp
  src/ui/simulator/windows/correlation/correlation.cpp
Labels: size/XL, code quality

#2280 Add short test to coverage analysis
  .github/workflows/sonarcloud.yml
  src/tests/run-study-tests/actions_on_study/study_run.py
Labels: size/S

#2267 Add unit tests to see coverage increase
  src/libs/antares/study/study.cpp
  src/tests/src/libs/antares/study/test_study.cpp
Labels: size/S, tests

#2285 Feature/test name translator
  src/tests/src/solver/optimisation/CMakeLists.txt
  src/tests/src/solver/optimisation/name-translator/CMakeLists.txt
  src/tests/src/solver/optimisation/name-translator/test_name_translator.cpp
Labels: size/L

#2284 Use a formula for the number of cores used
  docs/developer-guide/CHANGELOG.md
  docs/user-guide/solver/optional-features/multi-threading.md
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/study.cpp
  src/tests/src/libs/antares/study/test_study.cpp
Labels: size/L, code quality

#2265 Run all tests even if one of them fails
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M

#2287 Add missing changelog for v8.8.7
  docs/developer-guide/CHANGELOG.md
Labels: size/XS, doc
