Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-06, with the labels that each got.

#2145 Remove extra caching vcpkg
  .github/workflows/ubuntu.yml
Labels: size/XL

#2144 Use constexpr instead of enum to eliminate warnings
  src/solver/variable/include/antares/solver/variable/constants.h
Labels: size/S

#2146 Fix changelog for v9.1.0
  docs/developer-guide/CHANGELOG.md
Labels: size/M

#2143 Remove state from hydro ventilation
  src/solver/hydro/include/antares/solver/hydro/management/management.h
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
Labels: size/M

#2040 Hydro final levels (CR 25) : corrections and cleaning
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/include/antares/study/parts/hydro/finalLevelValidator.h
  src/libs/antares/study/include/antares/study/parts/hydro/finallevelinflowsmodifyer.h
  src/libs/antares/study/include/antares/study/parts/parts.h
  src/libs/antares/study/include/antares/study/scenario-builder/hydroLevelsData.h
  src/libs/antares/study/include/antares/study/scenario-builder/rules.h
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/finalLevelValidator.cpp
  src/libs/antares/study/parts/hydro/finallevelinflowsmodifyer.cpp
  src/libs/antares/study/scenario-builder/hydroLevelsData.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/simulation/hydro-final-reservoir-level-functions.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/test-hydro-final-reservoir-level-functions.cpp
Labels: size/XL

#2151 Add `/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` to fix segfault
  src/cmake/common-settings.cmake
Labels: size/XS

#2147 Remove unused arrays & variables from `RESULTATS_HORAIRES`
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
Labels: size/M, cleaning

#2148 Use sirius-solver@antares-integration-v1.5
  src/ports/sirius-solver/portfile.cmake
  src/ports/sirius-solver/vcpkg.json
  src/vcpkg.json
Labels: size/XS

#2156 Add precision on `playlist_year +/-` properties (generaldata.ini)
  docs/user-guide/solver/04-parameters.md
Labels: size/XS, doc

#2157 Use templated pointer-to-members instead of lambda-functions
  src/libs/antares/study/parts/hydro/container.cpp
Labels: size/L

#2159 Run all hydro checks outside simulation's loop
  src/solver/hydro/include/antares/solver/hydro/management/HydroInputsChecker.h
  src/solver/hydro/management/HydroInputsChecker.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
Labels: size/L

#2141 Add I/O & doc for CurtailmentSharing::recomputeDTGMRG [ANT-1809]
  docs/user-guide/04-migration-guides.md
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: size/XS

#2128 Parallel years cleaning : few removal of "numspace"
  src/solver/hydro/include/antares/solver/hydro/management/management.h
  src/solver/hydro/management/management.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/simulation.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/M

#2131 Remove hydro hotstart
  docs/user-guide/solver/04-parameters.md
  docs/user-guide/solver/06-hydro-heuristics.md
  docs/user-guide/solver/09-appendix.md
  simtest.json
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/include/antares/study/fwd.h
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/study.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/include/antares/solver/simulation/solver.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
  src/ui/simulator/windows/options/advanced/advanced.cpp
  src/ui/simulator/windows/options/advanced/advanced.h
Labels: size/L, cleaning

#2149 Move data validation to specialized functions [ANT-1213]
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/include/antares/study/parts/hydro/prepro.h
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.cpp
  src/libs/antares/study/parts/hydro/prepro.cpp
Labels: size/XL, code quality

#2172 Use local struct to capture multiple `IniFile::Section*`
  src/libs/antares/study/parts/hydro/container.cpp
Labels: size/M

#2170 Capture explicit var for lambdas
  src/libs/antares/inifile/inifile.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/filter.cpp
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/hydro/allocation.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/sets.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.importprepro.cpp
  src/libs/antares/study/xcast/xcast.cpp
  src/libs/antares/sys/policy.cpp
  src/solver/application/application.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/ts-generator/generator.cpp
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/xcast/xcast.cpp
  src/solver/variable/include/antares/solver/variable/area.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
Labels: size/XL, cleaning, code quality

#2173 Thermal validation and loading
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster_list.h
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
Labels: size/L

#2176 Fixing hydro debug
  src/solver/hydro/management/daily.cpp
Labels: size/XS

#2175 Separation of loading and validation for renewables clusters [ANT-1213]
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parts/renewable/cluster_list.h
  src/libs/antares/study/parts/renewable/cluster_list.cpp
Labels: size/M, code quality

#1986 Add ts-generation for links [ANT-1084]
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  docs/user-guide/04-migration-guides.md
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/fwd.h
  src/libs/antares/study/include/antares/study/load-options.h
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/parameters.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/tools/ts-generator/main.cpp
Labels: enhancement, size/L

#2177 Separation of loading and validation for parameters [ANT-1213]
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/parameters.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
Labels: size/L, code quality

#2180 Fix condition for disabling "store in input"
  src/libs/antares/study/load.cpp
Labels: size/XS, to-backport

#2183 Fix initialization order warnings
  src/libs/antares/study/area/area.cpp
Labels: size/S, code quality

#2184 Remove temporary MSVC flag used to mitigate runner issue
  src/cmake/common-settings.cmake
Labels: size/XS

#2186 Remove 200ms wait necessary for the GUI
  src/solver/main.cpp
Labels: size/XS, cleaning

#2190 clean code
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/include/antares/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_construction_matrice_des_contraintes_outils.cpp
Labels: size/M

#2191 rm undefined OPT_FreeOptimizationData(PROBLEME_ANTARES_A_RESOUDRE* Pr…
  src/solver/optimisation/include/antares/solver/optimisation/opt_fonctions.h
Labels: size/XS

#2179 Separation of loading and validation for header [ANT-1213]
  src/libs/antares/study/header.cpp
  src/libs/antares/study/include/antares/study/header.h
Labels: size/S, code quality

#2192 Small refactor on hydro final checks
  src/solver/application/ScenarioBuilderOwner.cpp
  src/solver/hydro/include/antares/solver/hydro/management/HydroInputsChecker.h
  src/solver/hydro/management/HydroInputsChecker.cpp
  src/solver/simulation/hydro-final-reservoir-level-functions.cpp
  src/solver/simulation/include/antares/solver/simulation/hydro-final-reservoir-level-functions.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/tests/src/solver/simulation/test-hydro-final-reservoir-level-functions.cpp
Labels: size/M

#2198 Check formatting as part of the CI (workflow only)
  .github/workflows/clang-format.yml
Labels: size/M

#2199 Remove some compile warnings
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/finalLevelValidator.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
Labels: size/M, build, code quality

#2187 Remove Antares::Memory::Array
  src/libs/antares/array/include/antares/array/matrix.h
  src/libs/antares/array/include/antares/array/matrix.hxx
  src/libs/antares/memory/include/antares/memory/memory.h
  src/libs/antares/memory/include/antares/memory/memory.hxx
  src/solver/variable/include/antares/solver/variable/storage/minmax-data.h
  src/solver/variable/include/antares/solver/variable/storage/minmax.h
  src/solver/variable/include/antares/solver/variable/storage/minmax.hxx
  src/solver/variable/storage/minmax-data.cpp
Labels: size/L, cleaning, code quality

#2168 Simplify functions prepareClustersInMustRunMode
  src/libs/antares/study/include/antares/study/area/scratchpad.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
Labels: size/L

#2206 add develop to sonar branch
  .github/workflows/sonarcloud.yml
Labels: size/XS

#2207 Fix/sonar
  .github/workflows/sonarcloud.yml
Labels: size/XS

#2205 Improve error message for ts-generation arg parsing
  src/libs/antares/utils/utils.cpp
Labels: size/XS

#2155 Remove TS links from solver
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/fwd.h
  src/libs/antares/study/include/antares/study/load-options.h
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/parameters.cpp
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/tools/ts-generator/main.cpp
Labels: size/XL, code quality

#2200 TS : generator : make it work for thermal
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/tools/ts-generator/main.cpp
Labels: size/M

#2132 Perform hydro checks prior to the simulation [ANT-1720]
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/runtime/runtime.cpp
  src/solver/application/CMakeLists.txt
  src/solver/application/ScenarioBuilderOwner.cpp
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/ScenarioBuilderOwner.h
  src/solver/application/include/antares/application/application.h
  src/solver/hydro/CMakeLists.txt
  src/solver/hydro/include/antares/solver/hydro/management/HydroInputsChecker.h
  src/solver/hydro/include/antares/solver/hydro/management/MinGenerationScaling.h
  src/solver/hydro/include/antares/solver/hydro/management/PrepareInflows.h
  src/solver/hydro/include/antares/solver/hydro/management/hydro-final-reservoir-level-functions.h
  src/solver/hydro/include/antares/solver/hydro/management/management.h
  src/solver/hydro/management/HydroInputsChecker.cpp
  src/solver/hydro/management/MinGenerationScaling.cpp
  src/solver/hydro/management/PrepareInflows.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/hydro-final-reservoir-level-functions.cpp
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/hydro-final-reservoir-level-functions.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/CMakeLists.txt
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/test-hydro-final-reservoir-level-functions.cpp
Labels: size/XXL

#2210 Remove unused CMake option BUILD_MINIZIP
  src/CMakeLists.txt
Labels: size/XS, build
