Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-05, with the labels that each got.

#2065 Graphviz presets
  src/CMakeGraphVizOptions.cmake
Labels: size/XS

#2074 Use `std::clamp` for sc-builder's hydro levels
  src/libs/antares/study/scenario-builder/scBuilderUtils.cpp
Labels: size/S

#2076 Bump upload-artifact to v4, use unique names for artifacts
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#2082 IO Statistics : use `std::atomic` instead of `std::mutex`
  src/libs/antares/io/statistics.cpp
Labels: size/M

#2083 Remove dependency of `Antares::logs` to `antares-core`, move "log purger" to UI
  src/libs/antares/include/antares/antares/constants.h
  src/libs/antares/logs/CMakeLists.txt
  src/libs/antares/logs/include/antares/logs/logs.h
  src/libs/antares/sys/CMakeLists.txt
  src/libs/fswalker/CMakeLists.txt
  src/ui/simulator/application/application.cpp
  src/ui/simulator/application/log_cleaner.cpp
  src/ui/simulator/application/log_cleaner.h
  src/ui/simulator/cmake/application.cmake
Labels: size/S

#2048 Doc/add thermal heuristic
  docs/optimisation/01-modeling.md
  docs/optimisation/02-thermal-heuristic.md
  docs/optimisation/Antares_Process.png
  docs/optimisation/Random_Parameters.png
  docs/optimisation/global_diagram.png
  docs/optimisation/thermal_heuristic_fast_step_2.png
  docs/optimisation/thermal_smoothing_heuristic.png
  mkdocs.yml
Labels: size/M

#2080 Add logs to checks on number of columns, refactor
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/parts/common/cluster.h
  src/libs/antares/study/include/antares/study/parts/hydro/series.h
  src/libs/antares/study/include/antares/study/parts/load/container.h
  src/libs/antares/study/include/antares/study/parts/solar/container.h
  src/libs/antares/study/include/antares/study/parts/wind/container.h
  src/libs/antares/study/parts/hydro/series.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/include/antares/solver/simulation/timeseries-numbers.h
  src/solver/simulation/timeseries-numbers.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/L

#2084 Fix directory path for windows
  src/libs/antares/writer/immediate_file_writer.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
Labels: size/XS

#2058 FileTreeStudyLoader [ANT-1213]
  src/libs/antares/CMakeLists.txt
  src/libs/antares/file-tree-study-loader/CMakeLists.txt
  src/libs/antares/file-tree-study-loader/FileTreeStudyLoader.cpp
  src/libs/antares/file-tree-study-loader/include/antares/file-tree-study-loader/FileTreeStudyLoader.h
  src/libs/antares/study-loader/CMakeLists.txt
  src/libs/antares/study-loader/include/antares/study-loader/IStudyLoader.h
  src/libs/antares/study/study.cpp
  src/packaging/CMakeLists.txt
  src/solver/CMakeLists.txt
  src/solver/application/CMakeLists.txt
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
Labels: size/XL

#2045 Time Series generation refactor
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/parts/parts.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.hxx
  src/libs/antares/study/include/antares/study/parts/thermal/defines.h
  src/libs/antares/study/include/antares/study/parts/thermal/prepro.hxx
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/prepro.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/CMakeLists.txt
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/solver/ts-generator/include/antares/solver/ts-generator/law.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/solver/ts-generator/prepro.cpp
  src/tools/ts-generator/main.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalmodulation.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.h
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/constants.cpp
  src/ui/simulator/windows/inspector/constants.h
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XXL

#2086 Remove "not good" (`std::unique_ptr` passed by ref)
  src/solver/optimisation/include/antares/solver/optimisation/constraints/constraint_builder_utils.h
Labels: size/S

#2085 Use composition for TimeSeriesNumbers (instead of inheritance)
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/store-timeseries-numbers.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/include/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/libs/antares/study/scenario-builder/HydroMaxPowerTSNumberData.cpp
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/include/antares/solver/variable/economy/profitByPlant.h
  src/solver/variable/state.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/L

#2073 Rationalize consistency checks on the number of columns
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/store-timeseries-numbers.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/include/antares/study/parts/common/cluster.h
  src/libs/antares/study/include/antares/study/parts/hydro/series.h
  src/libs/antares/study/include/antares/study/parts/load/container.h
  src/libs/antares/study/include/antares/study/parts/solar/container.h
  src/libs/antares/study/include/antares/study/parts/wind/container.h
  src/libs/antares/study/include/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/include/antares/solver/simulation/timeseries-numbers.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/variable/include/antares/solver/variable/economy/profitByPlant.h
  src/solver/variable/state.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/series/CMakeLists.txt
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/XL

#2087 Exclude src/ui from sonarQ analysis
  sonar-project.properties
Labels: size/XS, ci

#2068 [CR23] Remove prefix "hgp", use "h" for max pumping & generation
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/area/scratchpad.cpp
  src/libs/antares/study/area/store-timeseries-numbers.cpp
  src/libs/antares/study/include/antares/study/area/scratchpad.h
  src/libs/antares/study/include/antares/study/area/store-timeseries-numbers.hxx
  src/libs/antares/study/include/antares/study/fwd.h
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/include/antares/study/parts/hydro/series.h
  src/libs/antares/study/include/antares/study/scenario-builder/HydroMaxPowerTSNumberData.h
  src/libs/antares/study/include/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/include/antares/study/scenario-builder/rules.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/scenario-builder/HydroMaxPowerTSNumberData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/generator.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.h
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-series.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/ui/action/handler/antares-study/area/create.cpp
  src/ui/action/handler/antares-study/area/timeseries.cpp
  src/ui/simulator/application/main/build/scenario-builder.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/components/datagrid/renderer/column.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/column.h
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-renderer.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-hydro-renderer.h
  src/ui/simulator/toolbox/components/datagrid/renderer/ts-management.cpp
Labels: size/XL

#2093 Revert "Bump upload-artifact to v4, use unique names for artifacts (#…
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
Labels: size/S

#2088 Improve new release workflow
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
Labels: size/S, ci

#2094 Fix build for OL8
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/writer/test_writer.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/S

#2096 Use SimTest@v9.1.0-rc4
  simtest.json
Labels: size/XS

#1985 [ANT-1330] yaml parser and Antlr4 integration
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/CMakeLists.txt
  src/libs/antares/CMakeLists.txt
  src/libs/antares/antlr-interface/CMakeLists.txt
  src/libs/antares/antlr-interface/Expr.g4
  src/libs/antares/antlr-interface/Expr.interp
  src/libs/antares/antlr-interface/Expr.tokens
  src/libs/antares/antlr-interface/ExprBaseVisitor.cpp
  src/libs/antares/antlr-interface/ExprBaseVisitor.h
  src/libs/antares/antlr-interface/ExprLexer.cpp
  src/libs/antares/antlr-interface/ExprLexer.h
  src/libs/antares/antlr-interface/ExprLexer.interp
  src/libs/antares/antlr-interface/ExprLexer.tokens
  src/libs/antares/antlr-interface/ExprParser.cpp
  src/libs/antares/antlr-interface/ExprParser.h
  src/libs/antares/antlr-interface/ExprVisitor.cpp
  src/libs/antares/antlr-interface/ExprVisitor.h
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/antlr4-interface/CMakeLists.txt
  src/tests/src/libs/antares/antlr4-interface/test_antlr_interface.cpp
  src/tests/src/libs/antares/array/tests-matrix-load.cpp
  src/tests/src/libs/antares/array/tests-matrix-save.cpp
  src/tests/src/libs/antares/benchmarking/test_duration_collector.cpp
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-series.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydroreader-class.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/libs/antares/writer/test_writer.cpp
  src/tests/src/libs/antares/yaml-parser/CMakeLists.txt
  src/tests/src/libs/antares/yaml-parser/test_yaml_parser.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tests/src/solver/utils/basis_status.cpp
Labels: size/XXL

#1837 Add optimization options in OR-Tools / XPRESS, refactor
  docs/CHANGELOG.md
  docs/reference-guide/10-command_line.md
  docs/reference-guide/13-file-format.md
  src/libs/antares/CMakeLists.txt
  src/libs/antares/InfoCollection/StudyInfoCollector.cpp
  src/libs/antares/checks/include/antares/checks/checkLoadedInputData.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/include/antares/exception/LoadingError.hpp
  src/libs/antares/optimization-options/CMakeLists.txt
  src/libs/antares/optimization-options/include/antares/optimization-options/options.h
  src/libs/antares/study/include/antares/study/load-options.h
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/load-options.cpp
  src/libs/antares/study/parameters.cpp
  src/packaging/CMakeLists.txt
  src/solver/CMakeLists.txt
  src/solver/application/application.cpp
  src/solver/misc/include/antares/solver/misc/options.h
  src/solver/misc/options.cpp
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/include/antares/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/utils/CMakeLists.txt
  src/solver/utils/include/antares/solver/utils/named_problem.h
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/solver/utils/include/antares/solver/utils/ortools_wrapper.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/ortools_utils.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
Labels: size/L

#2099 Fix a few warnings emitted by clang-19
  src/solver/ts-generator/hydro.cpp
  src/solver/utils/include/antares/solver/utils/named_problem.h
Labels: size/S, build, code quality

#2095 Fix "new release" script, make "target branch" field mandatory
  .github/workflows/new_release.yml
Labels: size/XS

#2100 Add more explicit example on how to set solver parameters from command line
  docs/reference-guide/10-command_line.md
Labels: size/XS

#2101 Fixing oracle 8 compilation related to boost test linking
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/benchmarking/CMakeLists.txt
  src/tests/src/libs/antares/benchmarking/test_duration_collector.cpp
  src/tests/src/libs/antares/concurrency/CMakeLists.txt
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/libs/antares/writer/CMakeLists.txt
  src/tests/src/libs/antares/writer/test_writer.cpp
Labels: bug, size/M, ci

#2097 Fix formula use in output var Profit by plant [ANT-1719]
  src/solver/variable/include/antares/solver/variable/economy/profitByPlant.h
Labels: bug, size/XS

#2106 Doc fixes after merge
  docs/reference-guide/10-command_line.md
  docs/user-guide/solver/07-thermal-heuristic.md
  docs/user-guide/solver/08-command-line.md
Labels: size/L, doc

#2108 Always create list.ini for thermal clusters when saving [ANT-1728]
  src/libs/antares/study/parts/thermal/cluster_list.cpp
Labels: bug, size/XS

#2107 Release/9.1
  docs/developer-guide/CHANGELOG.md
Labels: size/M

#2111 Fix linking for boost tests
  src/tests/src/libs/antares/inifile/test_inifile_io.cpp
Labels: size/XS

#2115 Fix missing synthesis results for links
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
Labels: size/M

#2110 Version 8.8.5
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
  src/CMakeLists.txt
  src/ext/yuni/src/yuni/io/filename-manipulation.cpp
  src/solver/variable/economy/profitByPlant.h
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/array/tests-matrix-load.cpp
  src/tests/src/libs/antares/array/tests-matrix-save.cpp
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/libs/antares/writer/test_zip_writer.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/L

#2117 Fix build for Mersenne-Twister pybind11 with clang
  src/libs/antares/mersenne-twister/CMakeLists.txt
Labels: size/XS

#2066 Replace Yuni::IO with std functions
  src/ext/yuni/src/yuni/core/string/traits/append.h
  src/libs/antares/io/file.cpp
  src/libs/antares/io/include/antares/io/file.h
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/header.cpp
  src/libs/antares/study/importlogs.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/libs/antares/study/include/antares/study/header.h
  src/libs/antares/study/include/antares/study/parts/hydro/allocation.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/include/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/include/antares/study/sets.h
  src/libs/antares/study/include/antares/study/sets.hxx
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/output.cpp
  src/libs/antares/study/parts/common/cluster.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/hydro/allocation.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/scenario-builder/sets.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/sys/policy.cpp
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/libs/antares/writer/CMakeLists.txt
  src/libs/antares/writer/immediate_file_writer.cpp
  src/libs/antares/writer/in_memory_writer.cpp
  src/libs/antares/writer/include/antares/writer/i_writer.h
  src/libs/antares/writer/include/antares/writer/in_memory_writer.h
  src/libs/antares/writer/private/immediate_file_writer.h
  src/libs/antares/writer/private/zip_writer.h
  src/libs/antares/writer/zip_writer.cpp
  src/solver/application/application.cpp
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/misc/include/antares/solver/misc/options.h
  src/solver/misc/options.cpp
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tools/batchrun/main.cpp
  src/ui/simulator/windows/sets.cpp
Labels: size/XL, cleaning, code quality

#2120 Fix non-reg tests (SimTest@9.1.0-rc5)
  simtest.json
Labels: size/XS

#2113 Version 8.6.7
  simtest.json
  src/CMakeLists.txt
  src/solver/variable/economy/profitByPlant.h
Labels: size/XS

#2121 BC marginal cost : remove "return"s that break the static chain
  src/solver/variable/include/antares/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
Labels: size/L

#2123 Using filesystem path to open ini files
  src/libs/antares/correlation/correlation.cpp
  src/libs/antares/correlation/include/antares/correlation/correlation.h
  src/libs/antares/inifile/include/antares/inifile/inifile.h
  src/libs/antares/inifile/inifile.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/header.cpp
  src/libs/antares/study/include/antares/study/sets.hxx
  src/libs/antares/study/parts/hydro/allocation.cpp
  src/libs/antares/study/parts/hydro/prepro.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/solver/constraints-builder/cbuilder.cpp
Labels: size/M, code quality

#2127 Feature/vcpkg linux fixes
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/array/tests-matrix-load.cpp
  src/tests/src/libs/antares/array/tests-matrix-save.cpp
  src/tests/src/libs/antares/benchmarking/test_duration_collector.cpp
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-series.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydroreader-class.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/libs/antares/writer/CMakeLists.txt
  src/tests/src/libs/antares/writer/test_writer.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tests/src/solver/utils/basis_status.cpp
  src/vcpkg.json
Labels: size/XXL

#2125 Split changelog according to branches, add missing versions
  docs/developer-guide/CHANGELOG.md
Labels: size/L, doc

#2129 Minor fixes for changelog
  docs/developer-guide/CHANGELOG.md
Labels: size/XL

#2078 Feature/vcpkg linux
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/CMakeLists.txt
  src/cmake/wxWidgets/FindwxWidgets.cmake
  src/libs/antares/writer/CMakeLists.txt
  src/packaging/Config.cmake.in
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/array/tests-matrix-load.cpp
  src/tests/src/libs/antares/array/tests-matrix-save.cpp
  src/tests/src/libs/antares/benchmarking/test_duration_collector.cpp
  src/tests/src/libs/antares/concurrency/test_concurrency.cpp
  src/tests/src/libs/antares/study/area/test-save-area-optimization-ini.cpp
  src/tests/src/libs/antares/study/area/test-save-link-properties.cpp
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-series.cpp
  src/tests/src/libs/antares/study/parts/hydro/test-hydroreader-class.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/series/timeseries-tests.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/libs/antares/writer/CMakeLists.txt
  src/tests/src/libs/antares/writer/test_writer.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
  src/tests/src/solver/simulation/test-store-timeseries-number.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tests/src/solver/utils/basis_status.cpp
  src/triplets/x64-linux-antares.cmake
  src/triplets/x64-linux-release.cmake
  src/triplets/x64-windows-antares.cmake
  src/triplets/x64-windows-release.cmake
  src/vcpkg.json
  vcpkg_manifest/vcpkg.json
Labels: size/XXL

#2134 Fix PDF generation for useguide
  docs/user-guide/03-getting_started.md
  docs/user-guide/04-migration-guides.md
  docs/user-guide/other-features/analyzer.md
  docs/user-guide/other-features/batchrun.md
  docs/user-guide/other-features/config.md
  docs/user-guide/other-features/kirchhoff-constraints-builder.md
  docs/user-guide/other-features/study-cleaner.md
  docs/user-guide/other-features/study-finder.md
  docs/user-guide/other-features/study-updater.md
  docs/user-guide/other-features/ui-simulator.md
  docs/user-guide/other-features/vacuum.md
  docs/user-guide/other-features/ybyaggregator.md
  docs/user-guide/solver/00-index.md
  docs/user-guide/solver/01-overview-solver.md
  docs/user-guide/solver/02-inputs.md
  docs/user-guide/solver/04-parameters.md
  docs/user-guide/solver/07-thermal-heuristic.md
  docs/user-guide/ts-generator/00-index.md
  docs/user-guide/ts-generator/01-overview-tsgenerator.md
  docs/user-guide/ts-generator/04-parameters.md
Labels: size/M

#2135 Fix version metadata in SonarQ & docs (v9.1)
  docs/pdf-doc-generation-with-sphinx/source/conf.py
  sonar-project.properties
Labels: size/XS

#2138 Restore correct behavior when options -h/--list-solvers are provided
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
Labels: bug, enhancement, size/S

#2139 [ubuntu workflow] remove vcpkg manual install
  .github/workflows/ubuntu.yml
Labels: size/XS

#2140 Fix circular dependencies on CMake targets
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/include/antares/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_period_string_generator_base.h
  src/solver/utils/CMakeLists.txt
  src/solver/utils/filename.cpp
  src/solver/utils/include/antares/solver/utils/filename.h
  src/solver/utils/include/antares/solver/utils/opt_period_string_generator.h
Labels: size/M
