Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-10, with the labels that each got.

#2449 Fix a crash occurring when first year not played
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
Labels: size/S

#2437 Use OR-Tools v9.11-rte1.1 [ANT-2069]
  ortools_tag
Labels: size/XS

#2382 Cucumber: add short tests & refactor some steps
  src/tests/cucumber/features/medium_tests.feature
  src/tests/cucumber/features/short_tests.feature
  src/tests/cucumber/features/steps/assertions.py
  src/tests/cucumber/features/steps/context_utils.py
  src/tests/cucumber/features/steps/output_utils.py
  src/tests/cucumber/features/steps/simulator_utils.py
  src/tests/cucumber/features/steps/steps.py
  src/tests/cucumber/features/steps/study_input_handler.py
  src/tests/cucumber/features/steps/study_output_handler.py
  src/tests/cucumber/requirements.txt
Labels: size/L, tests

#2439 Update .gitignore
  .gitignore
Labels: size/S

#2435 Using filesystem path [ANT-1999]
  src/api/API.cpp
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/header.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/libs/antares/study/include/antares/study/header.h
  src/libs/antares/study/include/antares/study/parts/common/cluster.h
  src/libs/antares/study/include/antares/study/parts/common/cluster_list.h
  src/libs/antares/study/include/antares/study/parts/hydro/series.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/series.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster_list.h
  src/libs/antares/study/include/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/include/antares/study/study.h
  src/libs/antares/study/load.cpp
  src/libs/antares/study/parts/common/cluster.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/save.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/study.extra.cpp
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/libs/antares/writer/immediate_file_writer.cpp
  src/libs/antares/writer/include/antares/writer/writer_factory.h
  src/libs/antares/writer/private/immediate_file_writer.h
  src/libs/antares/writer/private/zip_writer.h
  src/libs/antares/writer/writer_factory.cpp
  src/libs/antares/writer/zip_writer.cpp
  src/solver/application/application.cpp
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/solver/ts-generator/prepro.cpp
  src/solver/ts-generator/xcast/xcast.cpp
  src/tests/src/libs/antares/study/output-folder/study.cpp
  src/tools/ts-generator/linksTSgenerator.cpp
  src/tools/ts-generator/main.cpp
  src/tools/vacuum/antares-study.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/toolbox/components/mainpanel.cpp
  src/ui/simulator/toolbox/ext-source/handler/com.rte-france.antares.study.cpp
  src/ui/simulator/windows/analyzer/analyzer.cpp
  src/ui/simulator/windows/exportmap.cpp
  src/ui/simulator/windows/memorystatistics/memorystatistics.cpp
  src/ui/simulator/windows/saveas.cpp
Labels: size/XL, code quality

#2447 [ANT-2206] default value for time/scenario dependant
  src/solver/libModelObject/include/antares/solver/libObjectModel/valueType.h
  src/solver/modelConverter/modelConverter.cpp
  src/solver/modelParser/encoders.hxx
  src/solver/modelParser/include/antares/solver/modelParser/Library.h
  src/tests/src/solver/modelParser/testModelParser.cpp
  src/tests/src/solver/modelParser/testModelTranslator.cpp
Labels: size/M

#2445 Modeler 1.1c: Scenarize problem filler [ANT-2003]
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemBuilder.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemFiller.h
  src/solver/modeler/api/linearProblemBuilder.cpp
  src/tests/src/solver/modeler/api/mock-fillers/FillerContext.h
  src/tests/src/solver/modeler/api/mock-fillers/OneConstraintFiller.h
  src/tests/src/solver/modeler/api/mock-fillers/OneVarFiller.h
  src/tests/src/solver/modeler/api/mock-fillers/TwoVarsTwoConstraintsFiller.h
  src/tests/src/solver/modeler/api/testModelerLPbuilder.cpp
Labels: size/L, Modeleur

#2448 [ANT-2206] Full exemple
  src/solver/modelParser/encoders.hxx
  src/solver/modelParser/include/antares/solver/modelParser/Library.h
  src/tests/src/solver/modelParser/CMakeLists.txt
  src/tests/src/solver/modelParser/enum_operators.h
  src/tests/src/solver/modelParser/testModelParser.cpp
  src/tests/src/solver/modelParser/testModelTranslator.cpp
  src/tests/src/solver/modelParser/test_full.cpp
Labels: size/XL

#2459 Add a few const ref qualifiers to improve code readibility
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
Labels: size/S

#2460 Migration guide for version 9.2
  docs/user-guide/04-migration-guides.md
Labels: size/M, doc

#2461 Improve 3.1
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblem.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/linearProblem.h
  src/solver/modeler/ortoolsImpl/linearProblem.cpp
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/LegacyOrtoolsFiller.cpp
  src/solver/optimisation/include/antares/solver/optimisation/LegacyOrtoolsFiller.h
  src/solver/optimisation/include/antares/solver/optimisation/LegacyOrtoolsLinearProblem.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/tests/run-study-tests/actions_on_study/study_run.py
Labels: size/L

#2467 Allow extension of cucumber features and steps
  .github/workflows/cucumber-tests/action.yml
  src/tests/cucumber/CMakeLists.txt
  src/tests/cucumber/features/environment.py
  src/tests/cucumber/features/steps/__init__.py
  src/tests/cucumber/features/steps/common_steps/assertions.py
  src/tests/cucumber/features/steps/common_steps/simulator_utils.py
  src/tests/cucumber/features/steps/common_steps/steps.py
  src/tests/cucumber/features/steps/common_steps/study_input_handler.py
  src/tests/cucumber/features/steps/common_steps/study_output_handler.py
  src/tests/cucumber/features/steps/import_helper.py
Labels: size/M, tests

#2476 Fix User guide PDF generation
  docs/pdf-doc-generation-with-sphinx/create_pdf_doc.sh
Labels: size/XS, doc
