Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-09, with the labels that each got.

#2358 Test improvement trial
  src/tests/src/solver/expressions/test_CompareVisitor.cpp
Labels: size/M

#2360 use raw ptr instead of ref
  src/solver/expressions/include/antares/solver/expressions/visitors/CloneVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CompareVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvalVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearityVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/PrintVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/SubstitutionVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndexVisitor.h
  src/solver/expressions/visitors/CloneVisitor.cpp
  src/solver/expressions/visitors/CompareVisitor.cpp
  src/solver/expressions/visitors/EvalVisitor.cpp
  src/solver/expressions/visitors/LinearityVisitor.cpp
  src/solver/expressions/visitors/PrintVisitor.cpp
  src/solver/expressions/visitors/SubstitutionVisitor.cpp
  src/solver/expressions/visitors/TimeIndexVisitor.cpp
  src/tests/src/solver/expressions/test_CloneVisitor.cpp
  src/tests/src/solver/expressions/test_CompareVisitor.cpp
  src/tests/src/solver/expressions/test_DeepWideTrees.cpp
  src/tests/src/solver/expressions/test_LinearVisitor.cpp
  src/tests/src/solver/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/solver/expressions/test_SubstitutionVisitor.cpp
  src/tests/src/solver/expressions/test_TimeIndexVisitor.cpp
Labels: size/XL

#2290 Expression visitors : first implementation
  src/solver/CMakeLists.txt
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/IName.h
  src/solver/expressions/include/antares/solver/expressions/Registry.hxx
  src/solver/expressions/include/antares/solver/expressions/nodes/AddNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/BinaryNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ComparisonNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ComponentNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/DivisionNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/EqualNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ExpressionsNodes.h
  src/solver/expressions/include/antares/solver/expressions/nodes/GreaterThanOrEqualNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Leaf.h
  src/solver/expressions/include/antares/solver/expressions/nodes/LessThanOrEqualNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/LiteralNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/MultiplicationNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NegationNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/Node.h
  src/solver/expressions/include/antares/solver/expressions/nodes/NodesForwardDeclaration.h
  src/solver/expressions/include/antares/solver/expressions/nodes/ParameterNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/PortFieldNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/SubtractionNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/UnaryNode.h
  src/solver/expressions/include/antares/solver/expressions/nodes/VariableNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CloneVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/CompareVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvalVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/EvaluationContext.h
  src/solver/expressions/include/antares/solver/expressions/visitors/InvalidNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearStatus.h
  src/solver/expressions/include/antares/solver/expressions/visitors/LinearityVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/NodeVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/PrintVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/SubstitutionVisitor.h
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndex.h
  src/solver/expressions/include/antares/solver/expressions/visitors/TimeIndexVisitor.h
  src/solver/expressions/nodes/BinaryNode.cpp
  src/solver/expressions/nodes/ComponentNode.cpp
  src/solver/expressions/nodes/PortFieldNode.cpp
  src/solver/expressions/nodes/UnaryNode.cpp
  src/solver/expressions/visitors/CloneVisitor.cpp
  src/solver/expressions/visitors/CompareVisitor.cpp
  src/solver/expressions/visitors/EvalVisitor.cpp
  src/solver/expressions/visitors/EvaluationContext.cpp
  src/solver/expressions/visitors/InvalidNode.cpp
  src/solver/expressions/visitors/LinearityVisitor.cpp
  src/solver/expressions/visitors/PrintVisitor.cpp
  src/solver/expressions/visitors/SubstitutionVisitor.cpp
  src/solver/expressions/visitors/TimeIndexVisitor.cpp
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/expressions/test_CloneVisitor.cpp
  src/tests/src/solver/expressions/test_CompareVisitor.cpp
  src/tests/src/solver/expressions/test_DeepWideTrees.cpp
  src/tests/src/solver/expressions/test_LinearVisitor.cpp
  src/tests/src/solver/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/solver/expressions/test_SubstitutionVisitor.cpp
  src/tests/src/solver/expressions/test_TimeIndexVisitor.cpp
  src/tests/src/solver/expressions/test_main.cpp
  src/tests/src/solver/expressions/test_nodes.cpp
Labels: size/XXL, Modeleur

#2341 Remove adequacy patch lmr [ANT-1933]
  docs/user-guide/04-migration-guides.md
  docs/user-guide/solver/04-parameters.md
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/include/antares/exception/LoadingError.hpp
  src/libs/antares/study/include/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.cpp
  src/solver/optimisation/base_weekly_optimization.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.h
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_local_matching/adq_patch_local_matching.h
  src/solver/optimisation/include/antares/solver/optimisation/base_weekly_optimization.h
  src/solver/optimisation/include/antares/solver/optimisation/weekly_optimization.h
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/optimisation/weekly_optimization.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/adequacy_patch_runtime_data.h
  src/solver/simulation/include/antares/solver/simulation/economy.h
  src/tests/src/solver/optimisation/adequacy_patch/adequacy_patch.cpp
  src/ui/simulator/windows/options/adequacy-patch/adequacy-patch-options.cpp
Labels: size/XL, adq-patch

#2364 Properly set common data in API output when using playlist
  src/api/SimulationObserver.cpp
  src/api/private/SimulationObserver.h
Labels: size/S

#2306 Adequacy patch CSR - revamp output variables [ANT-1932]
  docs/user-guide/04-migration-guides.md
  docs/user-guide/solver/03-outputs.md
  src/libs/antares/study/include/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/post_processing.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/post_processing.h
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/unsupliedEnergyCsr.h
  src/tests/src/solver/optimisation/adequacy_patch/adequacy_patch.cpp
Labels: size/L

#2368 Add help button to website
  .github/ISSUE_TEMPLATE/support_request.md
  mkdocs.yml
Labels: size/S, doc

#2373 Fix windows build
  src/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/post_processing.cpp
Labels: bug, size/XS, build

#2375 Bump simtest version
  simtest.json
Labels: size/XS

#2371 Remove unused headers in src/solver (yuni, cstdint, sim_*.h)
  src/solver/constraints-builder/include/antares/solver/constraints-builder/grid.h
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/management.cpp
  src/solver/optimisation/adequacy_patch_csr/post_processing.cpp
  src/solver/simulation/TimeSeriesNumbersWriter.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/sim_extern_variables_globales.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/include/antares/solver/simulation/solver.data.h
  src/solver/simulation/include/antares/solver/simulation/solver.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/include/antares/solver/simulation/solver_utils.h
  src/solver/simulation/include/antares/solver/simulation/timeseries-numbers.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/sim_variables_globales.cpp
  src/solver/simulation/solver_utils.cpp
  src/solver/ts-generator/hydro.cpp
Labels: size/M, cleaning

#2372 Centos mirror list
  .github/workflows/centos7.yml
Labels: size/S, ci

#2374 API modeller : apply remarks
  src/solver/optim/ortoolsImpl/include/antares/solver/optim/ortoolsImpl/linearProblem.h
  src/solver/optim/ortoolsImpl/include/antares/solver/optim/ortoolsImpl/mipSolution.h
  src/solver/optim/ortoolsImpl/linearProblem.cpp
  src/solver/optim/ortoolsImpl/mipSolution.cpp
  src/tests/src/solver/optim/api/testApiOrtoolsLinearProblem.cpp
Labels: size/L

#2377 Modeler API : apply remarks of #2286 on unit tests
  src/solver/optim/api/include/antares/solver/optim/api/mipSolution.h
  src/solver/optim/ortoolsImpl/mipSolution.cpp
  src/tests/src/solver/optim/api/testApiOrtoolsLinearProblem.cpp
Labels: size/L

#2379 Release 8.8.8
  src/libs/antares/study/load.cpp
Labels: size/XS

#2385 Modeler API : make addVariable with 4 args private
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblem.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/linearProblem.h
  src/tests/src/solver/modeler/api/testApiOrtoolsLinearProblem.cpp
Labels: size/S

#2384 Fix/sonar issues from 2286
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/linearProblem.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipConstraint.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipSolution.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipVariable.h
Labels: size/S

#2286 Modeleur 1.1: API [ANT-1876]
  src/solver/CMakeLists.txt
  src/solver/modeler/CMakeLists.txt
  src/solver/modeler/api/CMakeLists.txt
  src/solver/modeler/api/include/antares/solver/modeler/api/hasBounds.h
  src/solver/modeler/api/include/antares/solver/modeler/api/hasName.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblem.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemBuilder.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemData.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemFiller.h
  src/solver/modeler/api/include/antares/solver/modeler/api/mipConstraint.h
  src/solver/modeler/api/include/antares/solver/modeler/api/mipSolution.h
  src/solver/modeler/api/include/antares/solver/modeler/api/mipVariable.h
  src/solver/modeler/api/linearProblemData.cpp
  src/solver/modeler/ortoolsImpl/CMakeLists.txt
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/linearProblem.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipConstraint.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipSolution.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipVariable.h
  src/solver/modeler/ortoolsImpl/linearProblem.cpp
  src/solver/modeler/ortoolsImpl/mipConstraint.cpp
  src/solver/modeler/ortoolsImpl/mipSolution.cpp
  src/solver/modeler/ortoolsImpl/mipVariable.cpp
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/modeler/CMakeLists.txt
  src/tests/src/solver/modeler/api/CMakeLists.txt
  src/tests/src/solver/modeler/api/testApiOrtoolsLinearProblem.cpp
Labels: size/XXL, feature, Modeleur

#2387 Add iterators on ASTs, allowing for loops, std::find/std::find_if, std::count/std::count_if, etc.
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/iterators/pre-order.h
  src/solver/expressions/iterators/pre-order.cpp
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/expressions/test_Iterators.cpp
Labels: size/L

#2388 Release 8.8.8 v2
  src/solver/simulation/sim_calcul_economique.cpp
Labels: bug, size/XS

#2380 Add contribution guidelines
  CONTRIBUTING.md
  docs/developer-guide/0-Overview.md
  docs/developer-guide/6-Contributing.md
  mkdocs.yml
Labels: size/L, code, doc

#2389 Mark overriden functions as such in hydroLevelsData
  src/libs/antares/study/include/antares/study/scenario-builder/hydroLevelsData.h
Labels: size/XS, code quality

#2393 Release 8.8.9
  docs/CHANGELOG.md
  src/CMakeLists.txt
  src/solver/simulation/sim_calcul_economique.cpp
Labels: bug, size/S

#2394 Revert "Fix bug hydro heuristic with mingen (ANT-1825) (#2258)"
  src/solver/simulation/sim_calcul_economique.cpp
Labels: bug, size/XS

#2392 Remove unused CoutDeDefaillanceEnReserve
  src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/XS, cleaning

#2397 rc 4
  src/CMakeLists.txt
Labels: size/XS

#2403 Add SumNode "wide" test
  src/tests/src/solver/expressions/test_DeepWideTrees.cpp
Labels: size/S

#2406 Modeler 2.4c: portfield substitution
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/visitors/PortfieldSubstitutionVisitor.h
  src/solver/expressions/visitors/PortfieldSubstitutionVisitor.cpp
  src/tests/cucumber/conf.yaml
  src/tests/src/solver/expressions/test_SubstitutionVisitor.cpp
Labels: size/L, Modeleur

#2402 Fix or-tools integration
  ortools_tag
  src/CMakeLists.txt
  src/solver/simulation/CMakeLists.txt
Labels: size/M

#2409 Partial revert following #2406
  src/tests/cucumber/conf.yaml
Labels: size/XS

#2412 Remove unused code & #defines
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/solver/hydro/daily/h2o_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.cpp
  src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/utils/mps_utils.cpp
Labels: size/M, cleaning

#2418 Use OR-Tools v9.11-rte1.1 [ANT-2069]
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
Labels: size/S, 8.8

#2407 Place CSR after hydro remix [ANT-2070]
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
Labels: size/S, 8.8

#2420 Reset adequacy patch enabled
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: bug, size/XS

#2422 Always output DENS if adequacy patch is enabled [ANT-1932]
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: size/XS

#2398 bump simtest
  simtest.json
Labels: size/XS

#2399 visualize ast with graphviz
  src/solver/expressions/CMakeLists.txt
  src/solver/expressions/include/antares/solver/expressions/nodes/NodesForwardDeclaration.h
  src/solver/expressions/include/antares/solver/expressions/nodes/SumNode.h
  src/solver/expressions/include/antares/solver/expressions/visitors/AstDOTStyleVisitor.h
  src/solver/expressions/nodes/SumNode.cpp
  src/solver/expressions/visitors/AstDOTStyleVisitor.cpp
  src/tests/src/solver/expressions/CMakeLists.txt
  src/tests/src/solver/expressions/test_AstDOTStyleVisitor.cpp
Labels: size/XL

#2427 Remove awkward operator<< overload, use operator() instead
  src/solver/expressions/include/antares/solver/expressions/visitors/AstDOTStyleVisitor.h
  src/solver/expressions/visitors/AstDOTStyleVisitor.cpp
  src/tests/src/solver/expressions/test_AstDOTStyleVisitor.cpp
Labels: size/M

#2419 Force enable-first-step=false
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, 8.8

#2426 Visitor AST into DOT : trial for more clarity
  src/solver/expressions/include/antares/solver/expressions/visitors/AstDOTStyleVisitor.h
  src/solver/expressions/visitors/AstDOTStyleVisitor.cpp
  src/tests/src/solver/expressions/test_AstDOTStyleVisitor.cpp
Labels: size/M

#2429 AST to DOT : forgotten commit
  src/solver/expressions/visitors/AstDOTStyleVisitor.cpp
Labels: size/XS

#2425 create one executable for multipe unit translations tests
  src/tests/src/solver/modeler/api/CMakeLists.txt
  src/tests/src/solver/modeler/api/LinearProblemBuilder.cmake
  src/tests/src/solver/modeler/api/LinearProblemWithOrtools.cmake
  src/tests/src/solver/modeler/api/testModelerLPbuilder.cpp
  src/tests/src/solver/modeler/api/testModelerLinearProblemWithOrtools.cpp
  src/tests/src/solver/modeler/api/test_main.cpp
Labels: size/M

#2414 Better handling of discontinued parameters
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: size/M, adq-patch

#2421 Adequacy patch CSR - revamp output variables [ANT-1932]
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/post_processing.cpp
  src/solver/optimisation/adequacy_patch_csr/post_processing.h
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/CMakeLists.txt
  src/solver/variable/economy/all.h
  src/solver/variable/economy/unsupliedEnergyCsr.h
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, 8.8

#2436 Release 8.8.10
  docs/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#2442 Use devtoolset-11 CentOS7
  .github/workflows/centos7.yml
  .github/workflows/install-cmake-328/action.yml
Labels: size/S

#2441 [DOC] Add changelog for branch 8.8.x
  docs/developer-guide/CHANGELOG.md
Labels: size/S, doc, 8.8

#2383 Modeleur 2.1: Lib for modeling objects [ANT-1877]
  src/solver/CMakeLists.txt
  src/solver/libModelObject/CMakeLists.txt
  src/solver/libModelObject/include/antares/solver/libObjectModel/constraint.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/expression.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/library.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/model.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/parameter.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/port.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/portField.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/portFieldDefinition.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/portType.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/valueType.h
  src/solver/libModelObject/include/antares/solver/libObjectModel/variable.h
  src/solver/libModelObject/model.cpp
Labels: size/XL, Modeleur

#2443 Fix broken ToC for changelog
  docs/developer-guide/CHANGELOG.md
Labels: size/XS, doc

#2444 Init test repo after the build
  .github/workflows/windows-vcpkg.yml
Labels: size/S, ci
