Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-03, with the labels that each got.

#1967 Tool for time series generation
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  src/libs/antares/study/include/antares/study/runtime/runtime.h
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/utils/CMakeLists.txt
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/solver/misc/include/antares/solver/misc/options.h
  src/solver/misc/options.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/solver/ts-generator/thermal.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tools/CMakeLists.txt
  src/tools/ts-generator/CMakeLists.txt
  src/tools/ts-generator/main.cpp
Labels: enhancement, size/L

#1972 Restore windows debug info format, for debug build
  src/cmake/common-settings.cmake
Labels: size/M

#1969 Correct the ts count for no gen thermal clusters ANT-1303
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
Labels: bug, size/S, to-backport

#1974 Use nproc for CI hosts
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/windows-vcpkg.yml
  src/tests/run-study-tests/actions_on_study/study_run.py
Labels: size/S, ci

#1973 Fix help header for antares-ts-generator
  src/tools/ts-generator/main.cpp
Labels: size/XS

#1976 Remove remaining Yuni::Mutex, cleaning
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/study.cpp
  src/tools/vacuum/antares-study.cpp
  src/tools/vacuum/antares-study.h
  src/tools/vacuum/modified-inode.cpp
  src/tools/vacuum/modified-inode.h
  src/tools/yby-aggregator/job.cpp
Labels: size/M, code quality

#1977 Remove Yuni::Bind from src, excluding src/ui
  src/libs/antares/paths/include/antares/paths/list.h
  src/libs/antares/paths/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/include/antares/study/cleaner.h
  src/libs/fswalker/fswalker.cpp
  src/libs/fswalker/fswalker.h
  src/tools/cleaner/main.cpp
  src/tools/updater/main.cpp
  src/tools/vacuum/modified-inode.cpp
  src/ui/action/handler/antares-study/constraint/offsets.cpp
  src/ui/action/handler/antares-study/constraint/weights.cpp
  src/ui/simulator/toolbox/components/map/settings.h
  src/ui/simulator/windows/cleaner.cpp
Labels: size/M

#1944 feat(tests): add large test
  src/solver/optim/api/LinearProblemBuilder.cpp
  src/solver/optim/api/include/antares/optim/api/LinearProblemBuilder.h
  src/solver/optim/api/include/antares/optim/api/LinearProblemData.h
  src/solver/optim/impl/LinearProblemImpl.cpp
  src/solver/optimisation/LegacyLinearProblemFillerImpl.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_global.cpp
  src/solver/optimisation/opt_global.h
  src/tests/poc/include/simple/Balance.h
  src/tests/poc/include/simple/ProductionPriceMinimization.h
  src/tests/poc/include/standard/ComponentFiller.h
  src/tests/poc/include/standard/PortConnection.h
  src/tests/poc/legacy-workflow/simple-study.cpp
  src/tests/poc/new-workflow/CMakeLists.txt
  src/tests/poc/new-workflow/scaling-test.cpp
  src/tests/poc/new-workflow/simple-test.cpp
  src/tests/poc/new-workflow/standard-test.cpp
Labels: size/L, poc

#1965 [ANT-1184] Document API design
  docs/Architecture/API_usage_example-Nominal_example_of_Simulator_API_usage.svg
  docs/Architecture/API_usage_example.puml
  docs/Architecture_Decision_Records/Expose_cpp_API.md
Labels: size/M

#1798 Delete "rename" process and useless calls around
  src/ext/yuni/src/tools/yuni-config/program.cpp
  src/ext/yuni/src/yuni/cmake/core/core.cmake
  src/ext/yuni/src/yuni/cmake/parser/importer.cpp
  src/ext/yuni/src/yuni/core/process/rename.cpp
  src/ext/yuni/src/yuni/core/process/rename.h
  src/ext/yuni/src/yuni/io/filename-manipulation.cpp
  src/ext/yuni/src/yuni/io/filename-manipulation.h
  src/libs/antares/resources/resources.cpp
  src/solver/CMakeLists.txt
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/tools/batchrun/main.cpp
  src/ui/simulator/application/application.cpp
  src/ui/simulator/toolbox/components/datagrid/component.cpp
  src/ui/simulator/windows/studylogs.cpp
Labels: size/L

#1927 Add "in memory" implementation for `IResultWriter`
  src/libs/antares/study/parameters.cpp
  src/libs/antares/writer/CMakeLists.txt
  src/libs/antares/writer/in_memory_writer.cpp
  src/libs/antares/writer/include/antares/writer/in_memory_writer.h
  src/libs/antares/writer/include/antares/writer/result_format.h
  src/libs/antares/writer/writer_factory.cpp
  src/libs/antares/writer/zip_writer.cpp
  src/tests/src/libs/antares/writer/CMakeLists.txt
  src/tests/src/libs/antares/writer/test_writer.cpp
Labels: size/L

#1989 [SONAR] Use 4 threads for analysis instead of 2
  sonar-project.properties
Labels: ci

#1984 Add missing parameter to command built by batchrun for OR-Tools
  src/tools/batchrun/main.cpp
Labels: bug, size/L

#1988 I/O for adequacy patch CSR fix
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: size/XS

#1992 Bump SimTest@9.1.0a
  simtest.json
Labels: size/XS, tests

#1990 Document migration 9.0 -> 9.1 better
  docs/reference-guide/13-file-format.md
  docs/reference-guide/17-v91.md
  docs/reference-guide/logic-hydro-maxP.drawio
  docs/reference-guide/logic-hydro-maxP.svg
  docs/reference-guide/migration.drawio
  docs/reference-guide/migration.svg
Labels: size/L, doc

#1994 Fix pdf generation
  docs/reference-guide/08-miscellaneous.md
  docs/reference-guide/11-modeling.md
  docs/reference-guide/13-file-format.md
  docs/reference-guide/17-v91.md
  docs/reference-guide/logic-hydro-maxP.png
  docs/reference-guide/migration.png
Labels: size/S

#1843 Hydro max power : adding unit tests for timeseries numbers
  src/libs/antares/study/parts/hydro/series.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/L, tests, RTE-i

#1975 Add tests for ts generator tool
  .github/workflows/ubuntu.yml
  src/distrib/win32/NSIS.template.in
  src/tests/CMakeLists.txt
  src/tests/run-study-tests/actions_on_study/study_run.py
  src/tests/run-study-tests/antares_tools/ts-generator/CMakeLists.txt
  src/tests/run-study-tests/antares_tools/ts-generator/conftest.py
  src/tests/run-study-tests/antares_tools/ts-generator/pytest.ini
  src/tests/run-study-tests/antares_tools/ts-generator/ts-generator.py
  src/tests/run-study-tests/conftest.py
  src/tests/run-study-tests/parse_studies/json_schema.json
  src/tests/run-study-tests/pytest.ini
  src/tests/run-study-tests/utils/find_output.py
  src/tools/ts-generator/main.cpp
Labels: size/L, tests

#1997 Revert "I/O for adequacy patch CSR fix"
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: size/XS

#2002 Add version 9.1
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
Labels: size/XS

#1982 [ANT-913] Adequacy patch CSR - fix DTG MRG
  src/libs/antares/study/include/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/include/antares/solver/optimisation/post_process_commands.h
  src/solver/optimisation/post_process_commands.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: size/L, to-backport

#2000 Use SimTest@9.1.0b, run all tests
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  simtest.json
Labels: size/S

#2003 Simplify for loop a bit
  src/solver/hydro/monthly/h2o_m_construire_les_variables.cpp
Labels: size/S, cleaning, code quality

#2005 Make computation of intermediate values more readable
  src/solver/optimisation/opt_restaurer_les_donnees.cpp
Labels: size/S

#2006 Invert dependency on TS-Generator data
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/fwd.h
  src/libs/antares/study/include/antares/study/parts/parts.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/solver/ts-generator/CMakeLists.txt
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/solver/ts-generator/include/antares/solver/ts-generator/law.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.hxx
  src/solver/ts-generator/prepro.cpp
  src/solver/ts-generator/thermal.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalmodulation.h
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/L

#2004 Add parameter latest to release workflow
  .github/workflows/new_release.yml
Labels: enhancement, size/S, ci

#1999 8.6.6
  docs/CHANGELOG.md
  src/CMakeLists.txt
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/optimisation/post_process_commands.h
  src/solver/ts-generator/thermal.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: bug, size/L

#1998 8.8.4
  docs/CHANGELOG.md
  src/CMakeLists.txt
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/libs/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/optimisation/post_process_commands.h
  src/solver/ts-generator/thermal.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/solver/optimisation/adequacy_patch.cpp
Labels: bug, size/L

#2011 Fix style for STS by group
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
Labels: size/L, code
