Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-02, with the labels that each got.

#1910 Use appendFormat
  src/solver/application/application.cpp
Labels: size/XS

#1908 Add total time logging at the end of the simulation
  src/solver/application/application.cpp
Labels: enhancement, size/S

#1909 Proposal for StudyVersion
  src/libs/antares/study/header.cpp
  src/libs/antares/study/output.cpp
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/tests/src/libs/antares/study/test_study.cpp
Labels: size/L

#1903 Include overflow variable in HydroPower constraint
  src/solver/optimisation/constraints/HydroPower.cpp
Labels: size/S

#1898 Change version behavior to allow more flexibility
  src/analyzer/atsp/load.cpp
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/antares/exception/LoadingError.hpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintLoader.cpp
  src/libs/antares/study/binding_constraint/EnvForLoading.h
  src/libs/antares/study/cleaner.h
  src/libs/antares/study/cleaner/cleaner.cpp
  src/libs/antares/study/finder/finder.cpp
  src/libs/antares/study/finder/finder.h
  src/libs/antares/study/header.cpp
  src/libs/antares/study/header.h
  src/libs/antares/study/header.hxx
  src/libs/antares/study/load.cpp
  src/libs/antares/study/output.cpp
  src/libs/antares/study/output.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters.h
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/parts/thermal/ecoInput.cpp
  src/libs/antares/study/save.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/constraint/test_constraint.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/tools/batchrun/main.cpp
  src/tools/cleaner/main.cpp
  src/tools/finder/main.cpp
  src/tools/kirchhoff-cbuilder/main.cpp
  src/tools/updater/main.cpp
  src/ui/simulator/application/main/cleaner.cpp
  src/ui/simulator/application/main/events.simulation.cpp
  src/ui/simulator/application/study.cpp
  src/ui/simulator/toolbox/components/mainpanel.cpp
  src/ui/simulator/windows/output/provider/outputs.cpp
  src/ui/simulator/windows/startupwizard.cpp
Labels: enhancement, size/XL, code quality

#1912 Version : fix build conflict with GNU flags
  src/libs/antares/study/version.cpp
  src/libs/antares/study/version.h
Labels: size/S, build

#1911 Release 9.0.0
  docs/CHANGELOG.md
  docs/index.md
  docs/reference-guide/13-file-format.md
  sonar-project.properties
  src/CMakeLists.txt
  src/libs/antares/study/version.cpp
Labels: size/M

#1913 Fix release workflow - run extended tests when requested
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: bug, size/S, ci

#1894 In-memory tests for CR23
  src/libs/antares/study/parts/hydro/series.h
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
Labels: size/M, RTE-i

#1917 Fix naming conflict with target `config`
  src/config/CMakeLists.txt
  src/packaging/CMakeLists.txt
Labels: size/XS

#1904 CR23 Reference Guide Update
  docs/reference-guide/13-file-format.md
Labels: size/S, RTE-i

#1922 Fix `RUN_EXTENDED_TESTS` being overriden at job level
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#1916 Release/v8.7.3
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  docs/CHANGELOG.md
  docs/build/3-Build.md
  ortools_tag
  simtest.json
  src/CMakeLists.txt
  src/cmake/common-settings.cmake
  src/cmake/utils.cmake
  src/ext/yuni/src/cmake/common-settings.cmake
  src/ext/yuni/src/cmake/target.cmake
  src/libs/antares/CMakeLists.txt
  src/solver/aleatoire/CMakeLists.txt
  src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/solver/main/CMakeLists.txt
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/simulation/CMakeLists.txt
  src/solver/ts-generator/CMakeLists.txt
  src/solver/utils/CMakeLists.txt
  src/solver/utils/include/antares/solver/utils/named_problem.h
  src/solver/utils/mps_utils.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_wrapper.h
  src/solver/variable/CMakeLists.txt
  src/tests/end-to-end/binding_constraints/CMakeLists.txt
  src/tests/end-to-end/simple_study/CMakeLists.txt
  src/ui/simulator/cmake/windows-output.cmake
Labels: size/L

#1925 Remove a few unused `SIM_*` function declarations
  src/solver/simulation/sim_allocation_tableaux.cpp
  src/solver/simulation/simulation.h
Labels: size/S, cleaning

#1930 De-duplicate bound for balance constraint
  src/solver/optim/api/include/antares/optim/api/LinearProblem.h
  src/solver/optim/impl/LinearProblemImpl.cpp
  src/solver/optim/impl/include/antares/optim/impl/LinearProblemImpl.h
  src/solver/optimisation/LegacyLinearProblemFillerImpl.cpp
  src/solver/optimisation/LegacyLinearProblemImpl.cpp
  src/solver/optimisation/LegacyLinearProblemImpl.h
  src/tests/poc/include/simple/Balance.h
  src/tests/poc/include/standard/ComponentFiller.h
Labels: size/S

#1932 Implement `LegacyLinearProblemFillerImpl::declareBalanceConstraints`
  src/solver/optim/api/CMakeLists.txt
  src/solver/optim/api/include/antares/optim/api/LinearProblemData.h
  src/solver/optim/impl/CMakeLists.txt
  src/solver/optimisation/LegacyLinearProblemFillerImpl.cpp
  src/solver/optimisation/LegacyLinearProblemFillerImpl.h
  src/solver/optimisation/LegacyLinearProblemImpl.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/M

#1931 add std example
  src/solver/optim/api/include/antares/optim/api/LinearProblemData.h
  src/tests/poc/include/standard/ComponentFiller.h
  src/tests/poc/include/standard/PortConnection.h
  src/tests/poc/new-workflow/standard-test.cpp
Labels: size/M

#1901 Rethinking variables & constraints dictionaries
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/construct_problem_variables.cpp
  src/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/set_problem_cost_function.cpp
  src/solver/optimisation/adequacy_patch_csr/set_variable_boundaries.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/opt_construction_variables_couts_demarrages.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_construction_variables_optimisees_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_bornes_couts_demarrage.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_quadratique.cpp
  src/solver/optimisation/opt_gestion_des_couts_couts_demarrage.cpp
  src/solver/optimisation/variables/VariableManagement.cpp
  src/solver/optimisation/variables/VariableManagement.h
  src/solver/optimisation/variables/VariableManagerUtils.cpp
  src/solver/optimisation/variables/VariableManagerUtils.h
Labels: size/XL

#1937 Update contributing info for PRs
  CONTRIBUTING.md
  README.md
Labels: size/S

#1934 release/v8.6.5
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-release.yml
  .github/workflows/windows-vcpkg.yml
  docs/build/3-Build.md
  ortools_tag
  simtest.json
  src/CMakeLists.txt
  src/cmake/common-settings.cmake
  src/cmake/utils.cmake
  src/ext/yuni/src/cmake/common-settings.cmake
  src/ext/yuni/src/cmake/target.cmake
  src/libs/antares/CMakeLists.txt
  src/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/utils/CMakeLists.txt
  src/solver/utils/include/antares/solver/utils/named_problem.h
  src/solver/utils/mps_utils.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/named_problem.h
  src/solver/utils/ortools_utils.cpp
  src/solver/utils/ortools_wrapper.h
  src/ui/common/component/spotlight/listbox-panel.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/renewable.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermal.areasummary.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/layers.cpp
  src/ui/simulator/windows/bindingconstraint/edit.cpp
  src/ui/simulator/windows/correlation/datasources.hxx
  src/ui/simulator/windows/hydro/dailypower.cpp
  src/ui/simulator/windows/hydro/management.cpp
Labels: size/L

#1928 Make latex readable in github
  docs/reference-guide/03-commands.md
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/06-time_series_analysis_and_generation.md
  docs/reference-guide/07-kirchhoffs_constraint_generator.md
  docs/reference-guide/08-miscellaneous.md
  docs/reference-guide/11-modeling.md
  docs/reference-guide/14-adequacy-patch.md
Labels: size/L

#1933 Query global data & fillers for legacy problem
  src/solver/optim/api/include/antares/optim/api/LinearProblemData.h
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/LegacyLinearProblemFillerImpl.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_global.cpp
  src/solver/optimisation/opt_global.h
Labels: size/M

#1943 Return pointer instead of reference
  src/solver/optimisation/LegacyLinearProblemFillerImpl.cpp
  src/solver/optimisation/LegacyLinearProblemImpl.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/S

#1946 Enable $ delimiter for latex expressions
  docs/javascripts/mathjax.js
  mkdocs.yml
Labels: size/S

#1862 Doc/update v 8.7
  docs/reference-guide/04-active_windows.md
  docs/reference-guide/05-output_files.md
  docs/reference-guide/08-miscellaneous.md
  docs/reference-guide/11-modeling.md
  docs/reference-guide/Random_Parameters.png
Labels: size/L

#1949 Enable dependabot for github actions
  .github/dependabot.yml
Labels: size/S

#1948 fix area & interco exported for each week
  src/solver/optimisation/opt_optimisation_lineaire.cpp
Labels: size/XS

#1915 Allow releases on other branches than develop
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M

#1955 Revert "Allow releases on other branches than develop"
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M

#1942 Add python binding for Mersenne-Twister
  .gitignore
  src/CMakeLists.txt
  src/libs/antares/mersenne-twister/CMakeLists.txt
  src/libs/antares/mersenne-twister/mersenne_twister_pybind11.cpp
Labels: size/M

#1957 Enable workflow for dependabot branches
  .github/workflows/branchNameValidation.yml
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/docker.yml
  .github/workflows/doxygen.yml
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/S

#1918 Remove version from exe
  .github/workflows/build-userguide.yml
  .github/workflows/centos7.yml
  .github/workflows/new_release.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/analyzer/CMakeLists.txt
  src/config/CMakeLists.txt
  src/distrib/unix/rpm/create-rpms.sh
  src/distrib/win32/NSIS.template.in
  src/libs/antares/locator/locator.cpp
  src/packaging/CMakeLists.txt
  src/solver/CMakeLists.txt
  src/tests/CMakeLists.txt
  src/tools/batchrun/CMakeLists.txt
  src/tools/cleaner/CMakeLists.txt
  src/tools/config/CMakeLists.txt
  src/tools/finder/CMakeLists.txt
  src/tools/kirchhoff-cbuilder/CMakeLists.txt
  src/tools/updater/CMakeLists.txt
  src/tools/vacuum/CMakeLists.txt
  src/tools/yby-aggregator/CMakeLists.txt
  src/ui/simulator/CMakeLists.txt
Labels: size/L

#1958 Fix centos & ol8 ci
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
Labels: size/XS

#1961 Add unit tests for legacy workflow
  src/solver/optim/api/include/antares/optim/api/LinearProblemBuilder.h
  src/solver/optim/impl/LinearProblemImpl.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_global.cpp
  src/solver/optimisation/opt_global.h
  src/solver/utils/CMakeLists.txt
  src/solver/utils/include/antares/solver/utils/ortools_wrapper.h
  src/solver/utils/ortools_utils.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/tests/poc/CMakeLists.txt
  src/tests/poc/include/simple/Balance.h
  src/tests/poc/include/standard/ComponentFiller.h
  src/tests/poc/legacy-workflow/CMakeLists.txt
  src/tests/poc/legacy-workflow/simple-study.cpp
Labels: size/L

#1960 Remove unitcount limit for time series generation ANT-1248
  src/solver/ts-generator/thermal.cpp
Labels: bug, size/S, code quality

#1963 Revert "Bump actions/upload-artifact from 3 to 4": hidden dependency to newer glibc
  .github/workflows/build-userguide.yml
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu-system-deps-build.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M
