Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2024-04, with the labels that each got.

#2015 Avoid copies for loops
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/study/area/area.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/libs/antares/study/parts/renewable/cluster_list.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/scenario-builder/RenewableTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
  src/libs/antares/study/study.cpp
  src/libs/antares/study/ui-runtimeinfos.cpp
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/hydro/management/management.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/simulation/timeseries-numbers.cpp
  src/solver/ts-generator/thermal.cpp
  src/solver/variable/include/antares/solver/variable/adequacy/overallCost.h
  src/solver/variable/include/antares/solver/variable/area.inc.hxx
  src/solver/variable/include/antares/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/include/antares/solver/variable/economy/dispatchableGeneration.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/profitByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/renewableGeneration.h
  src/solver/variable/include/antares/solver/variable/economy/thermalAirPollutantEmissions.h
  src/solver/variable/include/antares/solver/variable/surveyresults/reportbuilder.hxx
  src/solver/variable/surveyresults/surveyresults.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/src/libs/antares/study/test_study.cpp
  src/tests/src/solver/simulation/test-time_series.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/renewable-cluster-order.cpp
  src/ui/simulator/toolbox/components/htmllistbox/datasource/thermal-cluster-order.cpp
  src/ui/simulator/windows/inspector/property.cluster.update.cpp
Labels: size/L, cleaning

#2016 Add deprecation notice for STS legacy variables
  src/libs/antares/study/parameters.cpp
Labels: size/S

#2017 STS groups : output titles to uppercase
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
Labels: enhancement, size/XS

#2018 Document changes for v9.1.0
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
Labels: size/M, cleaning, doc

#2007 STS groups : make group categories dynamic rather than fixed
  docs/CHANGELOG.md
  docs/reference-guide/13-file-format.md
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parts/short-term-storage/STStorageOutputCaptions.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/short-term-storage/STStorageOutputCaptions.cpp
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/adequacy/all.h
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/shortTermStorage.h
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
Labels: size/XL

#2020 Extract functions for STS groups
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
Labels: size/M

#2021 Use SimTest@v9.1.0-rc3
  simtest.json
Labels: size/XS

#2023 Doc: update "build" doc
  docs/build/0-INSTALL.md
  docs/build/1-Development-requirements.md
  docs/build/2-Dependencies-install.md
  docs/build/3-Build.md
  docs/build/4-Tests-dev.md
  docs/build/4-Tests-user.md
  docs/build/5-Installer-creation.md
  docs/build/6-dev-advice.md
  docs/build/ortools-integration.md
  mkdocs.yml
Labels: size/L, doc

#2022 Doc: update home, changelog & CI pages. Also update readme.
  .github/workflows/windows-vcpkg.yml
  CONTRIBUTING.md
  INSTALL.md
  README.md
  docs/CHANGELOG.md
  docs/build/0-INSTALL.md
  docs/build/0-Introduction.md
  docs/build/continuous-integration.md
  docs/index.md
  docs/overrides/partials/toc-item.html
  docs/stylesheets/extra.css
  mkdocs.yml
  src/distrib/win32/sourcefiles.inc.nsh
Labels: size/XL, doc

#2019 Add I/O for links' TS generation
  docs/CHANGELOG.md
  docs/reference-guide/13-file-format.md
  simtest.json
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/area/links.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/cleaner/cleaner-v20.cpp
  src/libs/antares/study/include/antares/study/area/area.h
  src/libs/antares/study/include/antares/study/area/links.h
  src/libs/antares/study/include/antares/study/load-options.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/STStorageOutputCaptions.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.hxx
  src/libs/antares/study/include/antares/study/parts/thermal/defines.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/short-term-storage/STStorageOutputCaptions.cpp
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/libs/antares/study/parts/thermal/cluster_list.cpp
  src/solver/ts-generator/CMakeLists.txt
  src/solver/ts-generator/availability.cpp
  src/solver/ts-generator/include/antares/solver/ts-generator/generator.h
  src/solver/ts-generator/include/antares/solver/ts-generator/law.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.hxx
  src/solver/ts-generator/prepro.cpp
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/adequacy/all.h
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/shortTermStorage.h
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/end-to-end/utils/utils.cpp
  src/tests/end-to-end/utils/utils.h
  src/tools/ts-generator/main.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/area/thermalprepro.h
  src/ui/simulator/toolbox/components/datagrid/renderer/connection.cpp
  src/ui/simulator/windows/inspector/accumulator.hxx
  src/ui/simulator/windows/inspector/constants.cpp
  src/ui/simulator/windows/inspector/constants.h
  src/ui/simulator/windows/inspector/frame.cpp
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/XXL, feature, doc

#2026 Remove unused logs.hxx
  src/libs/antares/logs/CMakeLists.txt
  src/libs/antares/logs/include/antares/logs/logs.h
  src/libs/antares/logs/include/antares/logs/logs.hxx
Labels: size/M, cleaning

#2030 Cleanup link variables includes
  src/solver/variable/CMakeLists.txt
  src/solver/variable/adequacy/links.cpp
  src/solver/variable/economy/links.cpp
  src/solver/variable/include/antares/solver/variable/adequacy/all.h
  src/solver/variable/include/antares/solver/variable/adequacy/links.h
  src/solver/variable/include/antares/solver/variable/commons/links/links.cpp.inc.hxx
  src/solver/variable/include/antares/solver/variable/commons/links/links.h
  src/solver/variable/include/antares/solver/variable/commons/links/links.hxx
  src/solver/variable/include/antares/solver/variable/commons/links/links.hxx.inc.hxx
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/links.h
Labels: size/XXL

#2027 Update format-code.sh, remove unused generator files
  src/ext/yuni/src/yuni/core/bind/bind.h.generator.commonstypes.hpp
  src/ext/yuni/src/yuni/core/bind/bind.h.generator.hpp
  src/ext/yuni/src/yuni/core/bind/bind.hxx.generator.hpp
  src/ext/yuni/src/yuni/core/bind/traits.h.generator.hpp
  src/ext/yuni/src/yuni/core/event/observer/item.h.generator.hpp
  src/ext/yuni/src/yuni/core/event/observer/item.hxx.generator.hpp
  src/ext/yuni/src/yuni/core/event/traits.h.generator.hpp
  src/ext/yuni/src/yuni/core/preprocessor/vaargs.h.generator.hpp
  src/format-code.sh
Labels: size/XXL

#2031 Remove unnecessary ".inc.hxx" files
  src/solver/variable/CMakeLists.txt
  src/solver/variable/adequacy/area.cpp
  src/solver/variable/adequacy/area.memory-estimation.cpp
  src/solver/variable/adequacy/bc.memory-estimation.cpp
  src/solver/variable/economy/area.cpp
  src/solver/variable/economy/area.memory-estimation.cpp
  src/solver/variable/economy/bc.memory-estimation.cpp
  src/solver/variable/include/antares/solver/variable/area.hxx
  src/solver/variable/include/antares/solver/variable/area.inc.hxx
  src/solver/variable/include/antares/solver/variable/area.memory-estimation.inc.hxx
  src/solver/variable/include/antares/solver/variable/bc.memory-estimation.inc.hxx
  src/solver/variable/include/antares/solver/variable/bindConstraints.hxx
Labels: size/XL

#2043 Remove deps-build Actions
  .github/workflows/centos7-system-deps-build.yml
  .github/workflows/ubuntu-system-deps-build.yml
Labels: size/L

#2047 [ANT-1634] Bug on GUI : double-click on study.antares does not work anymore
  src/ext/yuni/src/yuni/io/filename-manipulation.cpp
Labels: bug, size/XS, Prio: High

#2044 Create & forward declare BasisStatus struct, reduce build time
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/include/antares/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/utils/CMakeLists.txt
  src/solver/utils/basis_status.cpp
  src/solver/utils/basis_status_impl.cpp
  src/solver/utils/basis_status_impl.h
  src/solver/utils/include/antares/solver/utils/basis_status.h
  src/solver/utils/include/antares/solver/utils/named_problem.h
  src/solver/utils/named_problem.cpp
  src/solver/utils/ortools_utils.cpp
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/utils/CMakeLists.txt
  src/tests/src/solver/utils/basis_status.cpp
Labels: size/L, code, build

#2055 Remove Fixture Test Suite
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/src/libs/antares/study/constraint/test_group.cpp
Labels: size/M

#2057 Use Ranges when possible
  src/solver/optimisation/adequacy_patch_local_matching/adequacy_patch_weekly_optimization.cpp
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
Labels: size/M

#2053 Remove export target
  src/packaging/CMakeLists.txt
Labels: size/XS

#2059 Remove study cleaner tool
  src/distrib/win32/NSIS.template.in
  src/tools/CMakeLists.txt
  src/tools/cleaner/CMakeLists.txt
  src/tools/cleaner/main.cpp
  src/tools/cleaner/win32/cleaner.ico
  src/tools/cleaner/win32/cleaner.rc.cmake
  src/ui/simulator/CMakeLists.txt
  src/ui/simulator/application/main/cleaner.cpp
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/windows/cleaner.cpp
  src/ui/simulator/windows/cleaner.h
Labels: size/XL

#2052 Remove Study::Ptr variant for CBuilder
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/create.cpp
  src/solver/constraints-builder/include/antares/solver/constraints-builder/cbuilder.h
  src/solver/constraints-builder/load.cpp
  src/tools/kirchhoff-cbuilder/main.cpp
  src/ui/simulator/application/main/constraintsbuilder.cpp
  src/ui/simulator/windows/constraints-builder/constraintsbuilder.cpp
Labels: size/M

#2051 Remove Study::Ptr variant for RetrieveListFromStudy
  src/libs/antares/study/include/antares/study/output.h
  src/libs/antares/study/include/antares/study/output.hxx
  src/ui/simulator/application/study.cpp
Labels: size/S

#2056 Refactor Application
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
Labels: size/L

#2054 Move Run<X>Mode in dedicated files
  src/packaging/CMakeLists.txt
  src/solver/CMakeLists.txt
  src/solver/application/application.cpp
  src/solver/main/CMakeLists.txt
  src/solver/main/adequacy.cpp
  src/solver/main/economy.cpp
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/adequacy_mode.cpp
  src/solver/simulation/economy_mode.cpp
  src/solver/simulation/include/antares/solver/simulation/adequacy_mode.h
  src/solver/simulation/include/antares/solver/simulation/economy.h
  src/solver/simulation/include/antares/solver/simulation/economy_mode.h
  src/tests/end-to-end/simple_study/CMakeLists.txt
Labels: size/L

#2061 Remove Yuni Strings in solver/ [ANT-1198]
  src/ext/yuni/src/yuni/core/logs/handler/callback.h
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/solver/constraints-builder/cbuilder.cpp
  src/solver/constraints-builder/include/antares/solver/constraints-builder/cbuilder.h
  src/solver/misc/include/antares/solver/misc/options.h
  src/ui/simulator/application/main/logs.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/toolbox/jobs/job.cpp
  src/ui/simulator/toolbox/jobs/job.h
Labels: size/M, cleaning, code quality
