Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-07, with the labels that each got.

#2893 Revert chocolatey cache
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2874 Infeasibility caused by hydro (attempt 2) [ANT-3122]
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/run-study-tests/check_on_results/integrity_compare.py
Labels: size/L, 9.3

#2894 Run parallel tests on windows only in extended tests
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2897 Use range-based for loops
  src/libs/antares/InfoCollection/StudyInfoCollector.cpp
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/correlation/correlation.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/sys/policy.cpp
Labels: size/L

#2895 9.3-rc3
  simtest.json
  src/CMakeLists.txt
Labels: size/XS

#2827 [ANT-2034] InMemory modeler test
  .github/workflows/sonarcloud.yml
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/study.h
  src/modeler/CMakeLists.txt
  src/modeler/FileWriter.cpp
  src/modeler/FileWriter.h
  src/modeler/loadFiles/CMakeLists.txt
  src/modeler/loadFiles/FileLoader.cpp
  src/modeler/loadFiles/include/antares/solver/modeler/loadFiles/Fileloader.h
  src/modeler/loadFiles/include/antares/solver/modeler/loadFiles/data.h
  src/modeler/loadFiles/include/antares/solver/modeler/loadFiles/loadFiles.h
  src/modeler/loadFiles/loadAll.cpp
  src/modeler/main.cpp
  src/modeler/modeler/CMakeLists.txt
  src/modeler/modeler/Modeler.cpp
  src/modeler/modeler/include/antares/solver/modeler/ILoader.h
  src/modeler/modeler/include/antares/solver/modeler/IWriter.h
  src/modeler/modeler/include/antares/solver/modeler/Modeler.h
  src/modeler/modeler/include/antares/solver/modeler/data.h
  src/packaging/CMakeLists.txt
  src/study/system-model/include/antares/study/system-model/library.h
  src/study/system-model/library.cpp
  src/tests/CMakeLists.txt
  src/tests/cucumber/features/modeler-features/test_launcher_1.feature
  src/tests/cucumber/features/modeler-features/test_launcher_2.feature
  src/tests/cucumber/features/modeler-features/test_launcher_3.feature
  src/tests/cucumber/features/modeler-features/test_launcher_4.feature
  src/tests/cucumber/features/modeler-features/test_launcher_5.feature
  src/tests/cucumber/features/modeler-features/test_launcher_6.feature
  src/tests/cucumber/features/modeler-features/test_launcher_7.feature
  src/tests/cucumber/features/modeler-features/us2.5.feature
  src/tests/end-to-end/CMakeLists.txt
  src/tests/end-to-end/modeler/CMakeLists.txt
  src/tests/end-to-end/modeler/test-modeler.cpp
  src/tests/inmemory-modeler/CMakeLists.txt
  src/tests/inmemory-modeler/include/inmemory-modeler.h
  src/tests/inmemory-modeler/inmemory-modeler.cpp
  src/tests/src/modeler/loadFiles/CMakeLists.txt
  src/tests/src/solver/optim-model-filler/CMakeLists.txt
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
  src/tests/src/study/system-model/test_component.cpp
Labels: size/XXL

#2908 Bump simtest to 9.3.0f
  simtest.json
Labels: size/XS

#2907 Add 2 future parameters in generaldata.ini [ANT-3504]
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/include/antares/study/parameters/adq-patch-params.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parameters/adq-patch-params.cpp
Labels: size/S

#2911 Remove useless std::shared_ptr around `SimulationHandler`
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints_with_mustrun.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/inmemory-study/include/in-memory-study.h
Labels: size/L, cleaning

#2913 Documentation for 9.3
  docs/user-guide/04-migration-guides.md
  docs/user-guide/solver/03-outputs.md
Labels: size/M, doc, 9.3

#2905 TS analyzer : removal
  README.md
  docs/user-guide/03-getting_started.md
  docs/user-guide/other-features/00-index.md
  docs/user-guide/other-features/analyzer.md
  docs/user-guide/other-features/kirchhoff-constraints-builder.md
  docs/user-guide/ts-generator/02-inputs.md
  docs/user-guide/ts-generator/03-outputs.md
  docs/user-guide/ts-generator/05-algorithm.md
  mkdocs.yml
  sonar-project.properties
  src/CMakeLists.txt
  src/analyzer/CMakeLists.txt
  src/analyzer/atsp/atsp.cpp
  src/analyzer/atsp/atsp.h
  src/analyzer/atsp/atsp.hxx
  src/analyzer/atsp/cache.cpp
  src/analyzer/atsp/correlations.cpp
  src/analyzer/atsp/load.cpp
  src/analyzer/atsp/misc.cpp
  src/analyzer/atsp/preflight.cpp
  src/analyzer/main.cpp
  src/analyzer/win32/analyzer.ico
  src/analyzer/win32/analyzer.rc.cmake
  src/distrib/unix/rpm/create-rpms.sh
  src/distrib/win32/NSIS.template.in
  src/format-code.sh
  src/libs/antares/locator/include/antares/locator/locator.h
  src/libs/antares/locator/locator.cpp
  src/ui/simulator/CMakeLists.txt
  src/ui/simulator/application/main/analyzer.cpp
  src/ui/simulator/application/main/create.cpp
  src/ui/simulator/application/main/events.simulation.cpp
  src/ui/simulator/application/main/internal-ids.h
  src/ui/simulator/application/main/main.cpp
  src/ui/simulator/application/main/main.h
  src/ui/simulator/application/main/menu.cpp
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/cmake/components.cmake
  src/ui/simulator/toolbox/components/datagrid/renderer/analyzer/areas.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/analyzer/areas.h
  src/ui/simulator/toolbox/components/datagrid/renderer/constraintsbuilder/links.h
  src/ui/simulator/windows/analyzer/analyzer.cpp
  src/ui/simulator/windows/analyzer/analyzer.h
  src/ui/simulator/windows/analyzer/analyzer.hxx
  src/ui/simulator/windows/constraints-builder/constraintsbuilder.h
Labels: size/XXL

#2916 Add sts inflow to scenario migration
  docs/user-guide/04-migration-guides.md
Labels: size/XS, doc, 9.3

#2917 Test problems in-memory [ANT-3514]
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/inmemory-study/include/in-memory-study.h
Labels: size/L

#2920 Changelog 9.3.0
  docs/developer-guide/CHANGELOG.md
Labels: size/L

#2926 Performance for problem building : avoid maps copy
  src/solver/optim-model-filler/LinearExpression.cpp
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/solver/optim-model-filler/TimeDependentLinearExpression.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/TimeDependentLinearExpression.h
Labels: size/M

#2929 Factorise antlr4 lib linking resolution
  src/cmake/utils.cmake
  src/expressions/antlr-interface/CMakeLists.txt
  src/libs/antares/additionalConstraintRhsExpression/CMakeLists.txt
  src/libs/antares/scenarioGroupParser/scenarioBuilderExpression/CMakeLists.txt
Labels: size/M

#2927 Remove warnings on gcc
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/parts/hydro/prepro.cpp
  src/libs/antares/study/parts/short-term-storage/makeGroupsOfHoursFromString.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
  src/solver/hydro/monthly/h2o_m_construire_les_contraintes.cpp
  src/solver/hydro/monthly/h2o_m_construire_les_variables.cpp
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/monthly/h2o_m_initialiser_les_second_membre.cpp
  src/solver/utils/ortools_quadratic_wrapper.cpp
  src/tests/end-to-end/modeler/test-modeler.cpp
  src/tests/src/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/io/data-series-csv-importer/testDataSeriesCsvImporter.cpp
  src/tests/src/io/yml-importers/testModelTranslator.cpp
  src/tests/src/libs/antares/scenarioBuilderExpression/test_scenario_builder_expr.cpp
  src/tests/src/optimisation/linear-problem-data/testDataSeriesRepo.cpp
  src/tests/src/optimisation/linear-problem-data/testScenarioGroupRepo.cpp
  src/tests/src/optimisation/linear-problem/testLinearProblemMpsolverImpl.cpp
  src/tests/src/solver/hydro/monthly.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearExpressionVisitor.cpp
Labels: size/L

#2937 Add documentation for `include-export-solutions` for migration guide
  docs/user-guide/04-migration-guides.md
Labels: size/XS, doc

#2940 [doc] Improve doc for STS additional constraints
  docs/user-guide/04-migration-guides.md
Labels: size/XS, doc, 9.3, 9.2

#2947 Fix ccache save/load
  .github/workflows/sonarcloud.yml
Labels: size/L
