Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-01, with the labels that each got.

#2550 Add attribute `enabled` to additional constraints, adapt tests [ANT-1855]
  src/libs/antares/study/include/antares/study/parts/short-term-storage/additionalConstraints.h
  src/libs/antares/study/parts/short-term-storage/additionalConstraints.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/solver/optimisation/constraints/ShortTermStorageCumulation.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: size/L

#2548 High-level API: provide output path instead of returning it [ANT-2561]
  src/api/API.cpp
  src/api/include/antares/api/SimulationResults.h
  src/api/include/antares/api/solver.h
  src/api/private/API.h
  src/api/solver.cpp
  src/api_client_example/src/API_client.cpp
  src/api_client_example/src/API_client.h
  src/api_client_example/tests/test.cpp
  src/format-code.sh
  src/solver/application/application.cpp
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/api_lib/test_api.cpp
Labels: size/M

#2552 Improve `add_boost_test` CMake function
  src/tests/macros.cmake
Labels: size/XS, tests, build, code quality

#2531 Add variable MRG PRICE CSR [ANT-2562]
  .github/workflows/ubuntu.yml
  src/CMakeLists.txt
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_structure_probleme_economique.h
  src/solver/variable/economy/all.h
  src/solver/variable/economy/priceCSR.h
Labels: size/L

#2555 Fix NonMovable class
  src/ext/yuni/src/yuni/core/nonmovable.h
Labels: size/XS, code

#2556 Changelog 8.8.12
  docs/CHANGELOG.md
Labels: size/S, doc, 8.8

#2561 Set modeler name for logs (instead of [noname])
  src/solver/modeler/main.cpp
Labels: size/XS

#2564 Fix yaml-cpp target to avoid cmake warnings
  src/solver/modelParser/CMakeLists.txt
  src/solver/modeler/parameters/CMakeLists.txt
  src/solver/systemParser/CMakeLists.txt
  src/tests/src/libs/antares/yaml-parser/CMakeLists.txt
Labels: size/XS, build

#2562 Print solution values in the logs if a solution exists
  src/solver/modeler/api/include/antares/solver/modeler/api/mipSolution.h
  src/solver/modeler/main.cpp
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipSolution.h
  src/solver/modeler/ortoolsImpl/mipSolution.cpp
Labels: size/M

#2559 Add variable MRG PRICE CSR in 9.2 [ANT-2562]
  src/libs/antares/study/parameters/adq-patch-params.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/priceCSR.h
Labels: size/L

#2565 Write raw optimization results [ANT-2302]
  docs/user-guide/solver/static-modeler/04-parameters.md
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/parameters.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/utils/filename.cpp
  src/solver/utils/include/antares/solver/utils/filename.h
Labels: size/M

#2568 Move .clang-format at project root
  .clang-format
  src/format-code.sh
Labels: size/XS

#2558 2.5b build linear problem from components
  src/solver/modeler/CMakeLists.txt
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblem.h
  src/solver/modeler/api/include/antares/solver/modeler/api/mipSolution.h
  src/solver/modeler/main.cpp
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/linearProblem.h
  src/solver/modeler/ortoolsImpl/include/antares/solver/modeler/ortoolsImpl/mipSolution.h
  src/solver/modeler/ortoolsImpl/linearProblem.cpp
  src/solver/modeler/ortoolsImpl/mipSolution.cpp
Labels: size/M

#2570 Small improvements for hydro remix
  src/solver/simulation/shave-peaks-by-remix-hydro.cpp
Labels: size/S

#2532 New hydro remix algorithm
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/include/antares/solver/simulation/shave-peaks-by-remix-hydro.h
  src/solver/simulation/shave-peaks-by-remix-hydro.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/test-hydro-remix.cpp
Labels: size/XXL

#2566 Accurate shave peaks algorithm integration
  src/libs/antares/study/fwd.cpp
  src/libs/antares/study/include/antares/study/fwd.h
  src/packaging/CMakeLists.txt
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/common-hydro-remix.cpp
Labels: size/L

#2578 Don't activate 8.8 long tests if we're in release
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS, 8.8

#2569 Fix recently introduced build warnings
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/variable/include/antares/solver/variable/economy/priceCSR.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/M

#2580 Output results : fix annual aggregation
  src/solver/variable/storage/intermediate.cpp
Labels: size/XS

#2581 auto format with clang-format
  .github/workflows/clang-format.yml
Labels: size/M

#2582 Revert "auto format with clang-format"
  .github/workflows/clang-format.yml
Labels: size/M

#2576 GUI bug: wrong indexes for thermal clusters in scenario builder [ANT-2580]
  src/libs/antares/study/include/antares/study/parts/common/cluster.h
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/variable/include/antares/solver/variable/adequacy/overallCost.h
  src/solver/variable/include/antares/solver/variable/area.hxx
  src/solver/variable/include/antares/solver/variable/economy/dispatchableGeneration.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/profitByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/thermalAirPollutantEmissions.h
  src/solver/variable/include/antares/solver/variable/state.h
  src/solver/variable/state.cpp
  src/tests/inmemory-study/in-memory-study.cpp
Labels: bug, size/L, GUI

#2585 Backport bug on annual aggregation [ANT-2630]
  src/solver/variable/storage/intermediate.cpp
Labels: bug, size/XS, 8.8

#2584 Remove unused enum class
  src/libs/antares/study/include/antares/study/parameters/adq-patch-params.h
Labels: cleaning

#2587 Parallel tests run twice on ubuntu CI
  .github/workflows/ubuntu.yml
Labels: bug, size/XS, ci

#2489 Fix milp bug
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/solver/variable/state.cpp
Labels: size/M

#2590 Remove new/delete from analyzer
  src/analyzer/atsp/atsp.cpp
  src/analyzer/atsp/atsp.h
  src/analyzer/atsp/cache.cpp
  src/analyzer/atsp/correlations.cpp
  src/analyzer/atsp/load.cpp
  src/analyzer/atsp/preflight.cpp
  src/tools/updater/main.cpp
Labels: size/M

#2591 Rename encoders.hxx -> decoders.hxx
  src/solver/CMakeLists.txt
  src/solver/modelParser/CMakeLists.txt
  src/solver/modelParser/decoders.hxx
  src/solver/modelParser/parser.cpp
  src/solver/systemParser/CMakeLists.txt
  src/solver/systemParser/decoders.hxx
  src/solver/systemParser/parser.cpp
Labels: size/XS

#2588 Remove manual allocations for set of areas, simplify code
  src/solver/variable/include/antares/solver/variable/setofareas.h
  src/solver/variable/include/antares/solver/variable/setofareas.hxx
Labels: size/M, code quality

#2592 Reserve out vectors to avoid copies and reallocations
  src/solver/modelConverter/modelConverter.cpp
Labels: size/XS

#2595 Remove a few new/delete in src/solver/variable
  src/solver/variable/include/antares/solver/variable/adequacy/overallCost.h
  src/solver/variable/include/antares/solver/variable/adequacy/spilledEnergy.h
  src/solver/variable/include/antares/solver/variable/commons/hydro.h
  src/solver/variable/include/antares/solver/variable/commons/load.h
  src/solver/variable/include/antares/solver/variable/commons/miscGenMinusRowPSP.h
  src/solver/variable/include/antares/solver/variable/commons/psp.h
  src/solver/variable/include/antares/solver/variable/commons/solar.h
  src/solver/variable/include/antares/solver/variable/commons/spatial-aggregate.h
  src/solver/variable/include/antares/solver/variable/commons/wind.h
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageWithdrawalByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/avail-dispatchable-generation.h
  src/solver/variable/include/antares/solver/variable/economy/balance.h
  src/solver/variable/include/antares/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
  src/solver/variable/include/antares/solver/variable/economy/dispatchable-generation-margin.h
  src/solver/variable/include/antares/solver/variable/economy/domesticUnsuppliedEnergy.h
  src/solver/variable/include/antares/solver/variable/economy/dtgMarginAfterCsr.h
  src/solver/variable/include/antares/solver/variable/economy/hydroCost.h
  src/solver/variable/include/antares/solver/variable/economy/hydrostorage.h
  src/solver/variable/include/antares/solver/variable/economy/inflow.h
  src/solver/variable/include/antares/solver/variable/economy/links/congestionFee.h
  src/solver/variable/include/antares/solver/variable/economy/links/congestionFeeAbs.h
  src/solver/variable/include/antares/solver/variable/economy/links/flowLinear.h
  src/solver/variable/include/antares/solver/variable/economy/links/flowLinearAbs.h
  src/solver/variable/include/antares/solver/variable/economy/links/hurdleCosts.h
  src/solver/variable/include/antares/solver/variable/economy/links/marginalCost.h
  src/solver/variable/include/antares/solver/variable/economy/localMatchingRuleViolations.h
  src/solver/variable/include/antares/solver/variable/economy/lold.h
  src/solver/variable/include/antares/solver/variable/economy/loldCsr.h
  src/solver/variable/include/antares/solver/variable/economy/lolp.h
  src/solver/variable/include/antares/solver/variable/economy/lolpCsr.h
  src/solver/variable/include/antares/solver/variable/economy/max-mrg-csr.h
  src/solver/variable/include/antares/solver/variable/economy/max-mrg.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnits.h
  src/solver/variable/include/antares/solver/variable/economy/nbOfDispatchedUnitsByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/nonProportionalCost.h
  src/solver/variable/include/antares/solver/variable/economy/npCostByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/operatingCost.h
  src/solver/variable/include/antares/solver/variable/economy/overallCost.h
  src/solver/variable/include/antares/solver/variable/economy/overallCostCsr.h
  src/solver/variable/include/antares/solver/variable/economy/overflow.h
  src/solver/variable/include/antares/solver/variable/economy/price.h
  src/solver/variable/include/antares/solver/variable/economy/priceCSR.h
  src/solver/variable/include/antares/solver/variable/economy/productionByDispatchablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/productionByRenewablePlant.h
  src/solver/variable/include/antares/solver/variable/economy/profitByPlant.h
  src/solver/variable/include/antares/solver/variable/economy/pumping.h
  src/solver/variable/include/antares/solver/variable/economy/reservoirlevel.h
  src/solver/variable/include/antares/solver/variable/economy/spilledEnergy.h
  src/solver/variable/include/antares/solver/variable/economy/unsupliedEnergy.h
  src/solver/variable/include/antares/solver/variable/economy/unsupliedEnergyCsr.h
  src/solver/variable/include/antares/solver/variable/economy/waterValue.h
  src/solver/variable/include/antares/solver/variable/storage/intermediate.h
Labels: size/XL

#2601 Clean up container.h / container.hxx
  src/solver/variable/include/antares/solver/variable/container.h
  src/solver/variable/include/antares/solver/variable/container.hxx
Labels: size/M, cleaning

#2593 Add unit tests on class `Antares::Solver::Variable::IntermediateValues`
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/variable/CMakeLists.txt
  src/tests/src/solver/variable/test_intermediate.cpp
Labels: size/M

#2598 Fix segfault on BP studies
  src/libs/antares/study/scenario-builder/ThermalTSNumberData.cpp
Labels: size/XS

#2600 Throw exception instead of pointer to exception
  src/solver/simulation/common-hydro-remix.cpp
Labels: size/XS

#2597 [ANT-2608] add of unit tests for time dependant expression
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/L

#2605 Fix function `ThermalCluster::getMarketBidCost` [ANT-2527] (backport)
  src/libs/antares/study/parts/thermal/cluster.cpp
Labels: bug, size/XS, 8.8

#2607 9.2 rc 9
  simtest.json
  src/CMakeLists.txt
Labels: size/XS

#2602 Remove recently introduced build warnings
  src/libs/antares/study/parts/thermal/constant_cost_provider.cpp
  src/solver/simulation/common-hydro-remix.cpp
Labels: size/S

#2615 Simplify ComponentFiller::addVariables
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
Labels: size/M
