Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-09, with the labels that each got.

#3015 "mc-" + int does not append to string
  src/solver/ts-generator/CMakeLists.txt
  src/solver/ts-generator/hydro.cpp
  src/solver/ts-generator/xcast/xcast.cpp
Labels: size/S

#3016 Throw exception properly
  src/solver/lps/CMakeLists.txt
  src/solver/lps/LpsFromAntares.cpp
Labels: size/S

#3017 Several warning fixes
  src/ext/yuni/src/yuni/core/process/program/program.cpp
  src/solver/hydro/include/antares/solver/hydro/management/finalLevelValidator.h
  src/solver/hydro/management/HydroInputsChecker.cpp
  src/solver/hydro/management/finalLevelValidator.cpp
  src/tests/src/solver/simulation/test-hydro-final-reservoir-level-functions.cpp
Labels: size/S

#3020 Remove hash
  src/ext/yuni/src/CMakeLists.txt
  src/ext/yuni/src/yuni/cmake/core/core.cmake
  src/ext/yuni/src/yuni/core/hash/table.h
  src/ext/yuni/src/yuni/core/hash/table/table.h
  src/ext/yuni/src/yuni/core/hash/table/table.hxx
  src/ext/yuni/src/yuni/job/job.cpp
Labels: size/L

#3034 Missing virtual destructor
  src/solver/simulation/include/antares/solver/simulation/storage-for-remix.h
Labels: size/XS

#3030 Fix pragma diagnostic pop could not pop, no matching push
  src/tests/src/solver/optimisation/constraints/constraints_builder.cpp
Labels: size/XS

#3032 private field 'pJobCount' is not used
  src/libs/fswalker/fswalker.cpp
  src/libs/fswalker/fswalker.h
Labels: size/XS

#3031 Fix unqualified call to 'std::move'
  src/tests/inmemory-modeler/inmemory-modeler.cpp
Labels: size/XS

#3023 Remove dead code in file name manipulation
  src/ext/yuni/src/yuni/io/filename-manipulation.cpp
  src/ext/yuni/src/yuni/io/filename-manipulation.h
  src/ext/yuni/src/yuni/io/filename-manipulation.hxx
Labels: size/L

#2980 Remove duplication in "variable de sorties"
  docs/developer-guide/TimeSeriesVariablesDesign.md
  src/solver/variable/include/antares/solver/variable/commons/generation.h
  src/solver/variable/include/antares/solver/variable/commons/hour_utils.h
  src/solver/variable/include/antares/solver/variable/commons/hydro.h
  src/solver/variable/include/antares/solver/variable/commons/load.h
  src/solver/variable/include/antares/solver/variable/commons/solar.h
  src/solver/variable/include/antares/solver/variable/commons/timeseries_base.h
  src/solver/variable/include/antares/solver/variable/commons/wind.h
Labels: size/XXL

#3040 ANT-3697 : fix contraint on weekly hydro generation amount (ANT-3697)
  src/libs/antares/study/area/scratchpad.cpp
Labels: size/XS

#3041 Logs time used to build modeler problem [ANT-3759]
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/modeler/modeler/Modeler.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/M

#3045 Add disabled test case for SumNode conversion with more than two operands
  src/tests/src/io/yml-importers/testConvertorVisitor.cpp
Labels: size/S

#3036 Optional overflow for short-term storage objects [ANT-3695]
  simtest.json
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/series.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/constraints/ShortTermStorageLevel.cpp
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_rename_problem.h
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_rename_problem.cpp
  src/solver/optimisation/variables/VariableManagement.cpp
  src/solver/optimisation/variables/VariableManagement.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/inmemory-study/include/in-memory-study.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: size/L

#3035 [ANT-3638] Remove H cost from Ov cost
  src/solver/variable/include/antares/solver/variable/economy/overallCost.h
  src/solver/variable/include/antares/solver/variable/economy/overallCostCsr.h
Labels: size/S

#2975 Remix by shaving peaks : adapt for multi storage [ANT-3175]
  src/packaging/CMakeLists.txt
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.h
  src/solver/optimisation/include/antares/solver/optimisation/optim_post_process_list.h
  src/solver/optimisation/include/antares/solver/optimisation/post_process_commands.h
  src/solver/optimisation/optim_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/base_post_process.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/hydro-for-remix.cpp
  src/solver/simulation/include/antares/solver/simulation/base_post_process.h
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/hydro-for-remix.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/create-storage-for-remix.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/remix-utils.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/shave-peaks-by-remix-help.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/shave-peaks-by-remix-storage-gen.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/storage-for-remix-interface.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/storage-for-remix-no-levels.h
  src/solver/simulation/include/antares/solver/simulation/remix-storage/storage-for-remix-with-levels.h
  src/solver/simulation/include/antares/solver/simulation/remix-utils.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/include/antares/solver/simulation/storage-for-remix.h
  src/solver/simulation/remix-storage/CMakeLists.txt
  src/solver/simulation/remix-storage/create-storage-for-remix.cpp
  src/solver/simulation/remix-storage/shave-peaks-by-remix-help.cpp
  src/solver/simulation/remix-storage/shave-peaks-by-remix-storage-gen.cpp
  src/solver/simulation/remix-storage/storage-for-remix-list-sort.cpp
  src/solver/simulation/remix-storage/storage-for-remix-no-levels.cpp
  src/solver/simulation/remix-storage/storage-for-remix-with-levels.cpp
  src/solver/simulation/shave-peaks-by-remix-storage-gen.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/remix-storage/CMakeLists.txt
  src/tests/src/solver/simulation/remix-storage/test-hydro-remix.cpp
  src/tests/src/solver/simulation/remix-storage/tests-on-remix-utils.cpp
  src/tests/src/solver/simulation/remix-storage/tests-on-shave-peak-by-remix-help.cpp
Labels: size/XXL

#3071 Field initialization order
  src/solver/simulation/remix-storage/storage-for-remix-with-levels.cpp
Labels: size/M

#3070 Disable warning in antlr
  src/expressions/antlr-interface/CMakeLists.txt
Labels: size/XS, build

#3080 Remove \n in ortools_tag
  ortools_tag
Labels: size/XS

#3091 Change None to NaN in cucumber step
  src/tests/cucumber/features/steps/common_steps/modeler_output_handler.py
Labels: size/XS

#3085 Use simple structures for linear expression representation instead of Eigen's sparse matrices
  src/expressions/include/antares/expressions/nodes/ParameterNode.h
  src/expressions/include/antares/expressions/visitors/EvalVisitor.h
  src/expressions/include/antares/expressions/visitors/TimeIndexVisitor.h
  src/expressions/visitors/EvalVisitor.cpp
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/io/inputs/yml-system/converter.cpp
  src/io/outputs/SimulationTableCsv.cpp
  src/io/outputs/include/antares/io/outputs/SimulationTableGenerator.h
  src/modeler-optimisation-container/include/antares/modeler-optimisation-container/OptimEntityContainer.h
  src/modeler/FileWriter.h
  src/modeler/modeler/Modeler.cpp
  src/modeler/modeler/include/antares/solver/modeler/data.h
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblemBuilder.h
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblemFiller.h
  src/optimisation/linear-problem-api/linearProblemBuilder.cpp
  src/solver/optim-model-filler/CMakeLists.txt
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/Dimensions.cpp
  src/solver/optim-model-filler/LinearExpression.cpp
  src/solver/optim-model-filler/LinearExpressionEigen.cpp
  src/solver/optim-model-filler/ReadLinearConstraintVisitor.cpp
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/Dimensions.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpressionEigen.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearConstraintVisitor.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearExpressionVisitor.h
  src/solver/optimisation/ComponentToAreaConnectionFiller.cpp
  src/solver/optimisation/LegacyFiller.cpp
  src/solver/optimisation/include/antares/solver/optimisation/ComponentToAreaConnectionFiller.h
  src/solver/optimisation/include/antares/solver/optimisation/LegacyFiller.h
  src/solver/optimisation/include/antares/solver/optimisation/constraints/PMinMaxDispatchableGenerationGroup.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/study/system-model/component.cpp
  src/study/system-model/include/antares/study/system-model/component.h
  src/study/system-model/include/antares/study/system-model/constraint.h
  src/study/system-model/model.cpp
  src/tests/inmemory-modeler/include/inmemory-modeler.h
  src/tests/src/expressions/test_DeepWideTrees.cpp
  src/tests/src/io/outputs/testSimulationTable.cpp
  src/tests/src/io/yml-importers/test_full.cpp
  src/tests/src/optimisation/linear-problem-data/testScenarioGroupRepo.cpp
  src/tests/src/optimisation/linear-problem/mock-fillers/FillerContext.h
  src/tests/src/optimisation/linear-problem/mock-fillers/OneConstraintFiller.h
  src/tests/src/optimisation/linear-problem/mock-fillers/OneVarFiller.h
  src/tests/src/optimisation/linear-problem/testLinearProblemBuilder.cpp
  src/tests/src/study/system-model/test_component.cpp
  src/vcpkg.json
Labels: size/XXL

#3086 Modeler 5.4: Evaluate comparisons [ANT-3620]
  src/expressions/include/antares/expressions/visitors/EvalVisitor.h
  src/expressions/visitors/EvalVisitor.cpp
  src/tests/src/expressions/test_PrintAndEvalVisitors.cpp
Labels: size/M, Modeleur

#3094 Flatten `SumNode` to avoid deep recursion
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/tests/src/io/yml-importers/testConvertorVisitor.cpp
  src/tests/src/solver/optim-model-filler/test_readLinExprVisitor_sum_connections.cpp
Labels: size/M

#3095 Use gcc-11 for ubuntu & sonarcloud jobs
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
Labels: size/XS, ci

#3099 Clean & simplify class OptimEntityContainer
  src/expressions/visitors/EvalVisitor.cpp
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/io/outputs/SimulationTableGenerator.cpp
  src/modeler-optimisation-container/include/antares/modeler-optimisation-container/OptimEntityContainer.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearExpressionVisitor.h
Labels: size/M, cleaning, code quality

#3096 Code comments on districts [ANT-3408]
  src/solver/variable/include/antares/solver/variable/commons/spatial-aggregate.h
Labels: size/S

#3101 Remove unused methods `getOptimalValue` and `getOptimalValues`
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/mipSolution.h
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/mipSolution.h
  src/optimisation/linear-problem-mpsolver-impl/mipSolution.cpp
  src/tests/src/io/outputs/testSimulationTable.cpp
  src/tests/src/optimisation/linear-problem/testLinearProblemMpsolverImpl.cpp
Labels: size/M, cleaning

#3109 fix variable global Index
  src/expressions/include/antares/expressions/nodes/VariableNode.h
  src/expressions/visitors/CloneVisitor.cpp
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/modeler-optimisation-container/OptimEntityContainer.cpp
  src/tests/end-to-end/modeler/test-modeler.cpp
  src/tests/inmemory-modeler/include/inmemory-modeler.h
  src/tests/inmemory-modeler/inmemory-modeler.cpp
  src/tests/src/expressions/test_AstDOTStyleVisitor.cpp
  src/tests/src/expressions/test_LinearVisitor.cpp
  src/tests/src/expressions/test_nodes.cpp
  src/tests/src/io/yml-importers/testConvertorVisitor.cpp
Labels: size/M
