Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-06, with the labels that each got.

#2831 Add some unit tests for hydro
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/hydro/CMakeLists.txt
  src/tests/src/solver/hydro/monthly.cpp
Labels: size/M, tests

#2841 [ANT-3236] Simplify for loop
  src/solver/hydro/monthly/h2o_m_ajouter_bruit.cpp
Labels: size/S

#2840 Fix missing ortools dll in windows zip asset
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2847 Document STS additional constraints @ v9.2.0
  docs/user-guide/04-migration-guides.md
Labels: size/S, 9.2

#2845 Hydro monthly heuristic : add a new overflow optimization variable for v9.2.x [ANT-3236]
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/solver/hydro/include/antares/solver/hydro/management/management.h
  src/solver/hydro/include/antares/solver/hydro/monthly/h2o_m_donnees_annuelles.h
  src/solver/hydro/include/antares/solver/hydro/monthly/h2o_m_donnees_optimisation.h
  src/solver/hydro/management/daily.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/h2o_m_ajouter_bruit.cpp
  src/solver/hydro/monthly/h2o_m_construire_les_contraintes.cpp
  src/solver/hydro/monthly/h2o_m_construire_les_variables.cpp
  src/solver/hydro/monthly/h2o_m_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/monthly/h2o_m_initialiser_les_second_membre.cpp
  src/solver/hydro/monthly/h2o_m_instanciation.cpp
  src/tests/src/solver/hydro/monthly.cpp
Labels: size/XL, 9.2

#2846 Improve deprecation notice
  src/libs/antares/study/parameters.cpp
Labels: size/M, 9.3

#2850 (v9.2.x) Part 1/2 : Set primal tolerance to 1e-6 in ortools_utils [ANT-3122]
  src/solver/utils/ortools_utils.cpp
Labels: size/XS

#2851 (v9.2.x) missing ortools dll in zip asset (win)
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2855 [ANT-3359] Scenario-group is optional in component and default to "default"
  src/io/inputs/yml-system/decoders.hxx
  src/tests/resources/modeler/1_1/input/system.yml
  src/tests/resources/modeler/1_2/input/system.yml
  src/tests/resources/modeler/1_3/input/system.yml
  src/tests/resources/modeler/1_4/input/system.yml
  src/tests/resources/modeler/1_5/input/system.yml
  src/tests/resources/modeler/1_6/input/system.yml
  src/tests/resources/modeler/2_1/input/system.yml
  src/tests/resources/modeler/2_2/input/system.yml
  src/tests/resources/modeler/2_3/input/system.yml
  src/tests/resources/modeler/2_4/input/system.yml
  src/tests/resources/modeler/3_1/input/system.yml
  src/tests/resources/modeler/3_2/input/system.yml
  src/tests/resources/modeler/3_3/input/system.yml
  src/tests/resources/modeler/4_1/input/system.yml
  src/tests/resources/modeler/4_2/input/system.yml
  src/tests/resources/modeler/4_3/input/system.yml
  src/tests/resources/modeler/5_1/input/system.yml
  src/tests/resources/modeler/6_1/input/system.yml
  src/tests/resources/modeler/6_2/input/system.yml
  src/tests/resources/modeler/6_3/input/system.yml
  src/tests/resources/modeler/7_1/input/system.yml
  src/tests/resources/modeler/7_2/input/system.yml
  src/tests/resources/modeler/7_3/input/system.yml
  src/tests/resources/modeler/7_4/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.1/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.4/input/system.yml
  src/tests/src/modeler/loadFiles/testLoadModelerFiles.cpp
Labels: size/XXL

#2860 Remove useless logging
  src/solver/utils/ortools_utils.cpp
Labels: size/XS, 9.2

#2862 Fix compilation warning (implicit double -> float conversion)
  src/tests/src/libs/antares/yaml-parser/test_yaml_parser.cpp
Labels: size/XS, code quality

#2853 Add changelog for v9.2.1
  docs/developer-guide/CHANGELOG.md
Labels: size/M, doc, 9.2

#2861 [ANT-2034] Various warnings or linter fixes
  src/expressions/include/antares/expressions/visitors/EvaluationContext.h
  src/expressions/include/antares/expressions/visitors/NodeVisitor.h
  src/expressions/visitors/EvalVisitor.cpp
  src/expressions/visitors/EvaluationContext.cpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/scenario-builder/ShortTermInflowsTSNumberData.h
  src/libs/antares/study/include/antares/study/scenario-builder/TSnumberData.h
  src/libs/antares/study/include/antares/study/scenario-builder/scBuilderDataInterface.h
  src/libs/antares/study/parts/short-term-storage/makeGroupsOfHoursFromString.cpp
  src/libs/antares/study/scenario-builder/ShortTermAdditionalConstraintsTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ShortTermInflowsTSNumberData.cpp
  src/libs/antares/study/scenario-builder/TSnumberData.cpp
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/ILinearProblemData.h
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblem.h
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/mipConstraint.h
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/mipSolution.h
  src/optimisation/linear-problem-data-impl/dataSeriesRepo.cpp
  src/optimisation/linear-problem-data-impl/include/antares/optimisation/linear-problem-data-impl/dataSeries.h
  src/optimisation/linear-problem-data-impl/include/antares/optimisation/linear-problem-data-impl/dataSeriesRepo.h
  src/optimisation/linear-problem-data-impl/include/antares/optimisation/linear-problem-data-impl/linearProblemData.h
  src/optimisation/linear-problem-data-impl/include/antares/optimisation/linear-problem-data-impl/timeSeriesSet.h
  src/optimisation/linear-problem-data-impl/linearProblemData.cpp
  src/optimisation/linear-problem-data-impl/timeSeriesSet.cpp
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/mipConstraint.h
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/mipSolution.h
  src/optimisation/linear-problem-mpsolver-impl/linearProblem.cpp
  src/optimisation/linear-problem-mpsolver-impl/mipConstraint.cpp
  src/solver/optim-model-filler/ReadLinearConstraintVisitor.cpp
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/solver/optim-model-filler/TimeDependentLinearExpression.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/TimeDependentLinearExpression.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/VariableDictionary.h
  src/solver/optimisation/ComponentToAreaConnectionFiller.cpp
  src/solver/optimisation/LegacyFiller.cpp
  src/tests/src/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearExpressionVisitor.cpp
Labels: size/L

#2842 Simtest 9.3.0b
  simtest.json
Labels: size/XS

#2865 Add Gurobi to list of queried solvers [ANT-3381]
  src/solver/utils/ortools_utils.cpp
  src/tests/src/solver/utils/test_ortools_utils.cpp
Labels: size/XS, 9.3

#2859 or-tools : update to v9.13 [ANT-3350]
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
  src/CMakeLists.txt
  src/ports/sirius-solver/portfile.cmake
  src/ports/sirius-solver/vcpkg.json
  src/vcpkg.json
Labels: size/M

#2866 Fix 8.8 dll
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  docker/Dockerfile
Labels: size/S

#2870 9.3 rc 2
  src/CMakeLists.txt
Labels: size/XS

#2871 Bump simtest to 9.3.0c
  simtest.json
Labels: size/XS

#2864 Use correct keys for ccache, update ccache for windows
  .github/workflows/centos7.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M, ci

#2879 Simplify applyToMatrix calls, remove useless CheckValidity template specializations
  src/libs/antares/study/include/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/scenario-builder/ShortTermAdditionalConstraintsTSNumberData.cpp
Labels: size/S

#2884 Always save ccache
  .github/workflows/oracle8.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2883 Cache chocolatey and installed utilities (Windows)
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2882 Random TS numbers for STS inflows & additional constraints [ANT-3415]
  src/solver/simulation/timeseries-numbers.cpp
Labels: size/M

#2886 Save sts inflows in legacy GUI [ANT-3425]
  src/libs/antares/series/series.cpp
Labels: size/XS

#2887 Bypass JIT only for STS [ANT-3425]
  src/libs/antares/series/include/antares/series/series.h
  src/libs/antares/series/series.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
Labels: size/S

#2890 doc(fmt): fix bullepoint formatting
  docs/user-guide/04-migration-guides.md
Labels: size/S, doc
