Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-05, with the labels that each got.

#2789 Add fixed variables support to OR-Tools quadratic wrapper
  src/solver/utils/ortools_quadratic_wrapper.cpp
  src/tests/cucumber/features/solver-features/short_tests.feature
  src/tests/src/solver/utils/test_ortools_quadratic_wrapper.cpp
Labels: bug, size/S

#2794 Fix linking issues by linking against solver-lib
  src/solver/variable/include/antares/solver/variable/commons/spatial-aggregate.h
  src/tests/src/libs/antares/study/series/CMakeLists.txt
  src/tests/src/solver/lps/CMakeLists.txt
  src/tests/src/solver/optimisation/constraints/CMakeLists.txt
  src/tests/src/solver/simulation/CMakeLists.txt
Labels: size/M

#2786 New modeler : make test 7.1 pass
  src/expressions/visitors/EvalVisitor.cpp
  src/modeler/main.cpp
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_7.feature
  src/tests/resources/modeler/7_1/input/data-series/load_ts_base028.tsv
  src/tests/resources/modeler/7_1/input/data-series/wind_ts_base028.tsv
  src/tests/resources/modeler/7_1/input/model-libraries/andromede_v1_models.yml
  src/tests/resources/modeler/7_1/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_1/input/system.yml
  src/tests/resources/modeler/7_1/parameters.yml
  src/tests/src/expressions/test_PrintAndEvalNodes.cpp
Labels: size/XXL

#2795 Add a few unit tests for "math utils" functions
  src/tests/src/libs/antares/test_utils.cpp
Labels: size/M

#2777 Use antlr to process st additional constraints [ANT-3091]
  .github/workflows/sonarcloud.yml
  docs/Architecture_Decision_Records/2025-04-22-remove-regex-and-use-antlr.md
  sonar-project.properties
  src/format-code.sh
  src/libs/antares/CMakeLists.txt
  src/libs/antares/additionalConstraintRhsExpression/CMakeLists.txt
  src/libs/antares/additionalConstraintRhsExpression/HoursField.g4
  src/libs/antares/additionalConstraintRhsExpression/HoursField.interp
  src/libs/antares/additionalConstraintRhsExpression/HoursField.tokens
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldBaseVisitor.cpp
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldBaseVisitor.h
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldLexer.cpp
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldLexer.h
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldLexer.interp
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldLexer.tokens
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldParser.cpp
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldParser.h
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldVisitor.cpp
  src/libs/antares/additionalConstraintRhsExpression/HoursFieldVisitor.h
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/parts/short-term-storage/HoursCollectorVisitor.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/makeGroupsOfHoursFromString.h
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/makeGroupsOfHoursFromString.cpp
  src/packaging/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/CMakeLists.txt
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/test-on-making-hour-groups-from-string.cpp
Labels: size/XXL

#2790 Fix fixed variable value in quadratic optimization
  src/solver/optimisation/opt_gestion_des_bornes_cas_quadratique.cpp
Labels: bug, size/XS

#2785 Ceiling error with xpress and accurate [ANT-3167]
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/solver/optimisation/opt_nombre_min_groupes_demarres_couts_demarrage.cpp
  src/solver/variable/state.cpp
  src/tests/src/libs/antares/test_utils.cpp
Labels: size/M

#2806 Fix monthly generating capacity [ANT-3095]
  src/solver/hydro/management/monthly.cpp
Labels: size/XS

#2802 Binding constraints RHS : refactor to avoid repetitions
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/include/antares/solver/simulation/sim_binding_constraints_rhs.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_binding_constraints.cpp
  src/solver/simulation/sim_binding_constraints_rhs.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/end-to-end/binding_constraints/CMakeLists.txt
  src/tests/end-to-end/binding_constraints/test_binding_constraints.cpp
  src/tests/end-to-end/binding_constraints/test_binding_constraints_with_mustrun.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/inmemory-study/include/in-memory-study.h
Labels: size/XL

#2800 Add tests 7.2, 7.2, 7.4
  .github/workflows/branchNameValidation.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  docs/developer-guide/6-Contributing.md
  docs/developer-guide/continuous-integration.md
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_7.feature
  src/tests/cucumber/features/modeler-features/test_launcher_1.feature
  src/tests/cucumber/features/modeler-features/test_launcher_2.feature
  src/tests/cucumber/features/modeler-features/test_launcher_3.feature
  src/tests/cucumber/features/modeler-features/test_launcher_4.feature
  src/tests/cucumber/features/modeler-features/test_launcher_5.feature
  src/tests/cucumber/features/modeler-features/test_launcher_6.feature
  src/tests/cucumber/features/modeler-features/test_launcher_7.feature
  src/tests/cucumber/features/modeler-features/us2.5.feature
  src/tests/cucumber/features/steps/common_steps/modeler_steps.py
  src/tests/resources/modeler/7_2/input/data-series/load_ts_base028.tsv
  src/tests/resources/modeler/7_2/input/data-series/wind_ts_base028.tsv
  src/tests/resources/modeler/7_2/input/model-libraries/andromede_v1_models.yml
  src/tests/resources/modeler/7_2/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_2/input/system.yml
  src/tests/resources/modeler/7_2/parameters.yml
  src/tests/resources/modeler/7_3/input/data-series/load_ts_base028.tsv
  src/tests/resources/modeler/7_3/input/data-series/wind_ts_base028.tsv
  src/tests/resources/modeler/7_3/input/model-libraries/andromede_v1_models.yml
  src/tests/resources/modeler/7_3/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_3/input/system.yml
  src/tests/resources/modeler/7_3/parameters.yml
  src/tests/resources/modeler/7_4/input/data-series/load_ts_base028.tsv
  src/tests/resources/modeler/7_4/input/data-series/wind_ts_base028.tsv
  src/tests/resources/modeler/7_4/input/model-libraries/andromede_v1_models.yml
  src/tests/resources/modeler/7_4/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_4/input/system.yml
  src/tests/resources/modeler/7_4/parameters.yml
Labels: size/XXL

#2793 Output variable : near price cap [ANT-3038]
  src/solver/variable/CMakeLists.txt
  src/solver/variable/economy/all.h
  src/solver/variable/economy/nearPriceCap.h
Labels: size/L, 8.8

#2808 Document file scenariobuilder.dat, add short-term storage feature
  docs/user-guide/solver/02-inputs.md
Labels: size/M, doc

#2811 Fix prefix for short-term storage
  src/libs/antares/study/scenario-builder/rules.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
Labels: size/S

#2812 Simplify ComponentToAreaConnectionFiller
  src/solver/optimisation/ComponentToAreaConnectionFiller.cpp
  src/solver/optimisation/LegacyOrtoolsLinearProblem.cpp
  src/solver/optimisation/include/antares/solver/optimisation/ComponentToAreaConnectionFiller.h
  src/tests/src/solver/optimisation/test_componentToAreaConnectionFiller.cpp
Labels: size/M

#2810 Near price cap hours on develop [ANT-3038]
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/nearPriceCap.h
Labels: size/L, 9.3

#2807 Add behave short tests 9 to 20
  src/tests/cucumber/features/solver-features/short_tests.feature
  src/tests/cucumber/features/steps/common_steps/solver_output_handler.py
  src/tests/cucumber/features/steps/common_steps/solver_steps.py
Labels: size/L

#2803 Package OR-Tools shared libs [ANT-3227]
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  docker/Dockerfile
Labels: size/L

#2815 Near price cap hours on v9.2.x
  src/solver/variable/CMakeLists.txt
  src/solver/variable/include/antares/solver/variable/economy/all.h
  src/solver/variable/include/antares/solver/variable/economy/nearPriceCap.h
Labels: size/L

#2813 Scenarize short-term storage additional constraints [ANT-3037]
  docs/user-guide/solver/02-inputs.md
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/include/antares/study/parts/short-term-storage/additionalConstraints.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/include/antares/study/scenario-builder/ShortTermAdditionalConstraintsTSNumberData.h
  src/libs/antares/study/include/antares/study/scenario-builder/ShortTermInflowsTSNumberData.h
  src/libs/antares/study/include/antares/study/scenario-builder/applyToMatrix.hxx
  src/libs/antares/study/include/antares/study/scenario-builder/rules.h
  src/libs/antares/study/parts/short-term-storage/additionalConstraints.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/scenario-builder/ShortTermAdditionalConstraintsTSNumberData.cpp
  src/libs/antares/study/scenario-builder/ShortTermInflowsTSNumberData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/solver/optimisation/constraints/ShortTermStorageCumulation.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_second_membre_cas_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-read-line.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-get-set.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/tests/src/solver/optimisation/constraints/constraints_builder.cpp
Labels: size/XL

#2814 [ANT-3092] Valeur par defaut des bornes des variables
  docs/user-guide/modeler/02-inputs.md
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/tests/resources/modeler/1_4/input/model-libraries/lib_example_1_4.yml
  src/tests/resources/modeler/6_2/input/model-libraries/lib_example_6_2.yml
  src/tests/resources/modeler/6_3/input/model-libraries/lib_example_6_3.yml
  src/tests/resources/modeler/7_1/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_2/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_3/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/7_4/input/model-libraries/antares_historic.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/input/model-libraries/lib_example2.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/input/model-libraries/lib_example2.yml
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/L

#2826 Fix behave comparison tolerance
  src/tests/cucumber/features/steps/common_steps/assertions.py
Labels: size/XS
