Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-02, with the labels that each got.

#2604 Update Contributing.md with log conventions
  docs/developer-guide/6-Contributing.md
Labels: size/S, doc

#2612 Define exception classes as subclasses
  src/solver/modeler/dataSeries/CMakeLists.txt
  src/solver/modeler/dataSeries/dataSeriesRepo.cpp
  src/solver/modeler/dataSeries/dataSeriesRepoExceptions.cpp
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/dataSeriesRepo.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/dataSeriesRepoExceptions.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/scenarioGroupRepo.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/scenarioGroupRepoExceptions.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/timeSeriesSet.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/timeSeriesSetExceptions.h
  src/solver/modeler/dataSeries/scenarioGroupRepo.cpp
  src/solver/modeler/dataSeries/scenarioGroupRepoExceptions.cpp
  src/solver/modeler/dataSeries/timeSeriesSet.cpp
  src/solver/modeler/dataSeries/timeSeriesSetExceptions.cpp
  src/tests/src/solver/modeler/dataSeries/testDataSeriesRepo.cpp
  src/tests/src/solver/modeler/dataSeries/testScenarioGroupRepo.cpp
  src/tests/src/solver/modeler/dataSeries/testTimeSeriesSet.cpp
Labels: size/L

#2577 Data for modeler (epic 4.1)
  src/packaging/CMakeLists.txt
  src/solver/modeler/CMakeLists.txt
  src/solver/modeler/api/CMakeLists.txt
  src/solver/modeler/api/include/antares/solver/modeler/api/ILinearProblemData.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemBuilder.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemData.h
  src/solver/modeler/api/include/antares/solver/modeler/api/linearProblemFiller.h
  src/solver/modeler/api/linearProblemBuilder.cpp
  src/solver/modeler/dataSeries/CMakeLists.txt
  src/solver/modeler/dataSeries/dataSeriesRepo.cpp
  src/solver/modeler/dataSeries/dataSeriesRepoExceptions.cpp
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/dataSeries.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/dataSeriesRepo.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/linearProblemData.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/scenarioGroupRepo.h
  src/solver/modeler/dataSeries/include/antares/solver/modeler/dataSeries/timeSeriesSet.h
  src/solver/modeler/dataSeries/linearProblemData.cpp
  src/solver/modeler/dataSeries/scenarioGroupRepo.cpp
  src/solver/modeler/dataSeries/scenarioGroupRepoExceptions.cpp
  src/solver/modeler/dataSeries/timeSeriesSet.cpp
  src/solver/modeler/dataSeries/timeSeriesSetExceptions.cpp
  src/solver/modeler/main.cpp
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
  src/solver/optimisation/CMakeLists.txt
  src/solver/optimisation/LegacyFiller.cpp
  src/solver/optimisation/include/antares/solver/optimisation/LegacyFiller.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/tests/src/solver/modeler/CMakeLists.txt
  src/tests/src/solver/modeler/api/CMakeLists.txt
  src/tests/src/solver/modeler/api/mock-fillers/FillerContext.h
  src/tests/src/solver/modeler/api/mock-fillers/OneConstraintFiller.h
  src/tests/src/solver/modeler/api/mock-fillers/OneVarFiller.h
  src/tests/src/solver/modeler/api/mock-fillers/TwoVarsTwoConstraintsFiller.h
  src/tests/src/solver/modeler/api/testModelerLPbuilder.cpp
  src/tests/src/solver/modeler/dataSeries/CMakeLists.txt
  src/tests/src/solver/modeler/dataSeries/main.cpp
  src/tests/src/solver/modeler/dataSeries/testDataSeriesRepo.cpp
  src/tests/src/solver/modeler/dataSeries/testLinearProblemData.cpp
  src/tests/src/solver/modeler/dataSeries/testScenarioGroupRepo.cpp
  src/tests/src/solver/modeler/dataSeries/testTimeSeriesSet.cpp
  src/tests/src/solver/optim-model-filler/CMakeLists.txt
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
  src/tests/src/solver/optimisation/adequacy_patch/CMakeLists.txt
Labels: size/XL

#2603 Unit test for the RHS of cumulative constraints
  src/tests/src/solver/optimisation/constraints/constraints_builder.cpp
Labels: size/L

#2613 Increase precision for LOLD[CSR] and MRG PRICE[CSR] [ANT-2443]
  src/solver/variable/economy/lold.h
  src/solver/variable/economy/loldCsr.h
  src/solver/variable/economy/price.h
  src/solver/variable/economy/priceCSR.h
Labels: size/XS, 8.8

#2617 Add modeler non-regression tests
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  src/solver/modeler/main.cpp
  src/tests/cucumber/CMakeLists.txt
  src/tests/cucumber/features/modeler-features/epic2/us2.5.feature
  src/tests/cucumber/features/solver-features/medium_tests.feature
  src/tests/cucumber/features/solver-features/short_tests.feature
  src/tests/cucumber/features/steps/common_steps/modeler_output_handler.py
  src/tests/cucumber/features/steps/common_steps/modeler_utils.py
  src/tests/cucumber/features/steps/common_steps/steps.py
  src/tests/resources/modeler/epic2/us2.5/study_2.5.1/input/model-libraries/lib_example1.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.1/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.1/parameters.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/input/model-libraries/lib_example2.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/parameters.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/input/model-libraries/lib_example1.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/input/model-libraries/lib_example2.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/parameters.yml
Labels: size/L

#2238 Remove doc related to the GUI
  docs/developer-guide/2-Dependencies-install.md
  docs/developer-guide/3-Build.md
  docs/developer-guide/5-Installer-creation.md
  docs/ref_guides/system-map-editor-reference-guide.pdf
  docs/user-guide/05-attribution_notices.md
  docs/user-guide/other-features/kirchhoff-constraints-builder.md
  src/distrib/win32/NSIS.template.in
Labels: size/M, GUI, cleaning, doc

#2609 Feature/copilot instructions
  .github/copilot-instructions.md
Labels: size/XS

#2625 Fix the upgrade from v8.8 to 9.2 of hydro power matrices [ANT-2742]
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/include/antares/study/parts/hydro/hydromaxtimeseriesreader.h
  src/libs/antares/study/include/antares/study/parts/hydro/series.h
  src/libs/antares/study/parameters.cpp
  src/libs/antares/study/parts/hydro/container.cpp
  src/libs/antares/study/parts/hydro/hydromaxtimeseriesreader.cpp
  src/libs/antares/study/parts/hydro/series.cpp
  src/libs/antares/study/study.importprepro.cpp
Labels: size/L

#2629 Trial for improve issue 2033
  src/io/inputs/data-series-csv-importer/DataSeriesRepoImporter.cpp
Labels: size/S

#2633 Fix migration guide
  docs/user-guide/04-migration-guides.md
Labels: size/M, doc

#2637 Add tests for time-series handling
  src/expressions/visitors/EvalVisitor.cpp
  src/io/inputs/yml-system/converter.cpp
  src/io/inputs/yml-system/decoders.hxx
  src/io/inputs/yml-system/include/antares/io/inputs/yml-system/system.h
  src/solver/modeler/main.cpp
  src/tests/cucumber/features/modeler-features/epic2/us2.8.feature
  src/tests/resources/modeler/1_1/input/data-series/gen1_max_p_1_1.tsv
  src/tests/resources/modeler/1_1/input/data-series/gen1_prop_cost_1_1.tsv
  src/tests/resources/modeler/1_1/input/data-series/gen2_max_p_1_1.tsv
  src/tests/resources/modeler/1_1/input/data-series/gen2_prop_cost_1_1.tsv
  src/tests/resources/modeler/1_1/input/data-series/load_1_1.tsv
  src/tests/resources/modeler/1_1/input/model-libraries/lib_example_1_1.yml
  src/tests/resources/modeler/1_1/input/system.yml
  src/tests/resources/modeler/1_1/parameters.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.1/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/input/system.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.4/input/system.yml
  src/tests/src/io/yml-importers/testSystemConverter.cpp
  src/tests/src/io/yml-importers/testYmlSystem.cpp
Labels: size/L

#2642 update optim api
  src/expressions/visitors/EvalVisitor.cpp
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/linearProblem.cpp
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/tests/src/optimisation/linear-problem/testLinearProblemMpsolverImpl.cpp
Labels: size/XL

#2643 Fix std::bad_array_new_length exception in SurveyResults::SurveyResults
  src/solver/variable/surveyresults/surveyresults.cpp
  src/tests/src/solver/variable/CMakeLists.txt
  src/tests/src/solver/variable/test_surveyresults.cpp
Labels: bug, size/M

#2644 Bump simtest to 9.2.0k
  simtest.json
Labels: size/XS

#2641 Add end to end tests to sonarcloud
  .github/workflows/sonarcloud.yml
Labels: size/M

#2645 Call study saveToFolder in unit tests
  sonar-project.properties
  src/tests/end-to-end/simple_study/simple-study.cpp
Labels: size/S

#2646 Avoid copying a large map
  src/expressions/include/antares/expressions/visitors/EvalVisitor.h
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblemFiller.h
  src/optimisation/linear-problem-data-impl/linearProblemData.cpp
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/linearProblem.cpp
  src/solver/modeler/main.cpp
  src/solver/optim-model-filler/LinearExpression.cpp
  src/solver/optim-model-filler/ReadLinearConstraintVisitor.cpp
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
  src/tests/src/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/optimisation/linear-problem/testLinearProblemMpsolverImpl.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearExpressionVisitor.cpp
Labels: size/M

#2640 Slightly improve condition coverage on parameters.cpp
  src/libs/antares/study/include/antares/study/parameters.h
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
Labels: size/S

#2647 Fix sonarcloud end to end tests
  .github/workflows/sonarcloud.yml
Labels: size/S

#2649 More exclusion for sonar coverage
  .github/workflows/sonarcloud.yml
  sonar-project.properties
  src/libs/antares/date/date.cpp
  src/libs/antares/resources/resources.cpp
  src/libs/antares/study/parts/thermal/cluster.cpp
Labels: size/L

#2653 Fix build
  src/io/inputs/yml-system/converter.cpp
  src/study/system-model/include/antares/study/system-model/system.h
  src/study/system-model/system.cpp
  src/tests/src/study/system-model/test_system.cpp
Labels: size/M

#2652 Add named mps tests to sonarcloud
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: size/M

#2651 Fix a doc typo
  docs/user-guide/solver/04-parameters.md
Labels: size/XS

#2634 Increase coverage on hydro common data (hydro.ini) [ANT-1825]
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/parts/hydro/container.cpp
  src/tests/src/libs/antares/study/parts/hydro/CMakeLists.txt
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-common.cpp
Labels: size/L

#2630 Improve vcpkg configuration
  .gitignore
  src/ports/sirius-solver/portfile.cmake
  src/ports/sirius-solver/vcpkg.json
  src/vcpkg-configuration.json
  src/vcpkg.json
Labels: size/M

#2657 add timeStep field LinearConstraint
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/ReadLinearConstraintVisitor.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearConstraintVisitor.h
Labels: size/M

#2658 Place all unit test executables in the same build subdirectory
  src/tests/macros.cmake
Labels: size/XS, tests

#2660 simtest 8.8.x
  simtest.json
  src/CMakeLists.txt
Labels: size/XS

#2659 Correct cluster count, load constraints even for disabled clusters [ANT-2746]
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.hxx
Labels: size/XS, 8.8

#2635 Fix binding constraint TS loading in 8.8 [ANT-2746]
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintSaver.cpp
Labels: bug, size/M, 8.8

#2655 Add variable dictionnary in ComponentFiller
  src/solver/optim-model-filler/CMakeLists.txt
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/VariableDictionary.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/VariableDictionary.h
  src/tests/cucumber/features/modeler-features/epic2/us2.5.feature
  src/tests/cucumber/features/steps/common_steps/steps.py
  src/tests/resources/modeler/epic2/us2.5/study_2.5.4/output/problem.lp
  src/tests/src/solver/optim-model-filler/CMakeLists.txt
  src/tests/src/solver/optim-model-filler/test_VariableDictionary.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/XL, Modeleur

#2665 use vector wrapper
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/VariableDictionary.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/VariableDictionary.h
  src/tests/src/solver/optim-model-filler/test_VariableDictionary.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/L
