Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-04, with the labels that each got.

#2740 Remove compilation warnings for GCC
  src/expressions/include/antares/expressions/visitors/EvalVisitor.h
  src/expressions/nodes/TimeSumNode.cpp
  src/expressions/visitors/EvalVisitor.cpp
  src/expressions/visitors/LinearityVisitor.cpp
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/solver/utils/ortools_quadratic_wrapper.cpp
  src/tests/src/solver/optimisation/constraints/constraints_builder.cpp
  src/tests/src/solver/utils/test_ortools_quadratic_wrapper.cpp
Labels: size/M, build

#2743 Fix broken link in mkdocs.yml
  mkdocs.yml
Labels: size/XS

#2720 Remove macro ndebug
  src/libs/antares/array/include/antares/array/matrix.hxx
  src/libs/antares/correlation/correlation.cpp
  src/libs/antares/date/date.cpp
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/binding_constraint/BindingConstraint.cpp
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/include/antares/study/parts/hydro/allocation.h
  src/libs/antares/study/include/antares/study/runtime/runtime.h
  src/libs/antares/study/parts/hydro/allocation.cpp
  src/libs/antares/study/runtime/runtime.cpp
  src/libs/antares/study/study.cpp
  src/solver/hydro/management/monthly.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
Labels: size/M, code quality

#2733 Add checks for duplicates on study objects [ANT-2127]
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/include/antares/exception/LoadingError.hpp
  src/libs/antares/study/CMakeLists.txt
  src/libs/antares/study/duplicates.cpp
  src/libs/antares/study/include/antares/study/duplicates.h
  src/libs/antares/study/parts/common/cluster_list.cpp
  src/solver/application/application.cpp
  src/tests/src/libs/antares/study/CMakeLists.txt
  src/tests/src/libs/antares/study/test_duplicates.cpp
Labels: size/L

#2745 Add documentation on the ANTLR4 code generation process
  docs/developer-guide/7-antlr4.md
  mkdocs.yml
Labels: size/S

#2713 Add doc for overflow spilled cost difference
  docs/user-guide/solver/02-inputs.md
Labels: size/XS, doc, 9.2

#2746 Work on port rules
  src/expressions/antlr-interface/Expr.g4
  src/expressions/antlr-interface/Expr.interp
  src/expressions/antlr-interface/Expr.tokens
  src/expressions/antlr-interface/ExprBaseVisitor.h
  src/expressions/antlr-interface/ExprLexer.cpp
  src/expressions/antlr-interface/ExprLexer.h
  src/expressions/antlr-interface/ExprLexer.interp
  src/expressions/antlr-interface/ExprLexer.tokens
  src/expressions/antlr-interface/ExprParser.cpp
  src/expressions/antlr-interface/ExprParser.h
  src/expressions/antlr-interface/ExprVisitor.h
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/io/inputs/model-converter/include/antares/io/inputs/model-converter/convertorVisitor.h
  src/tests/src/io/yml-importers/testConvertorVisitor.cpp
Labels: size/XL

#2738 Bump OR-Tools version to v9.11-rte1.4
  docs/developer-guide/2-Dependencies-install.md
  docs/user-guide/05-attribution_notices.md
  ortools_tag
  src/optimisation/linear-problem-mpsolver-impl/CMakeLists.txt
  src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/solver/utils/CMakeLists.txt
  src/tests/src/solver/infeasible-problem-analysis/CMakeLists.txt
  src/tests/src/solver/utils/CMakeLists.txt
Labels: size/S

#2748 Add doc for behave.ini
  src/tests/cucumber/readme.md
Labels: size/S

#2707 Small typo
  docs/user-guide/04-migration-guides.md
Labels: size/XS, doc

#2682 Migrate some tests to cucumber
  src/tests/cucumber/features/environment.py
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_1.feature
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_2.feature
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_3.feature
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_4.feature
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_5.feature
  src/tests/cucumber/features/modeler-features/epic2/us2.5.feature
  src/tests/cucumber/features/solver-features/hybrid_studies.feature
  src/tests/cucumber/features/solver-features/medium_tests.feature
  src/tests/cucumber/features/solver-features/short_tests.feature
  src/tests/cucumber/features/solver-features/tests_for_v9.2.feature
  src/tests/cucumber/features/steps/common_steps/assertions.py
  src/tests/cucumber/features/steps/common_steps/modeler_output_handler.py
  src/tests/cucumber/features/steps/common_steps/modeler_steps.py
  src/tests/cucumber/features/steps/common_steps/modeler_utils.py
  src/tests/cucumber/features/steps/common_steps/simulator_utils.py
  src/tests/cucumber/features/steps/common_steps/solver_input_handler.py
  src/tests/cucumber/features/steps/common_steps/solver_output_handler.py
  src/tests/cucumber/features/steps/common_steps/solver_steps.py
  src/tests/cucumber/features/steps/common_steps/steps.py
  src/tests/cucumber/readme.md
  src/tests/run-study-tests/antares_tools/ts-generator/ts-generator.py
  src/tests/run-study-tests/parse_studies/cucumber_collector.py
  src/tests/run-study-tests/parse_studies/look_for_studies.py
  src/tests/run-study-tests/readme.md
  src/tests/run-study-tests/requirements.txt
  src/tests/run-study-tests/test_from_json.py
Labels: size/XL

#2749 Change control for sts injection/withdrawal efficiency [ANT-3100]
  simtest.json
  src/libs/antares/study/parts/short-term-storage/properties.cpp
Labels: bug, size/S, 9.2

#2754 Add documentation for hybrid area connections
  docs/user-guide/modeler/00-index.md
  docs/user-guide/modeler/02-inputs.md
  docs/user-guide/modeler/08-command-line.md
  docs/user-guide/modeler/08-hybrid-studies.md
  docs/user-guide/solver/00-index.md
  docs/user-guide/solver/08-hybrid-studies.md
  docs/user-guide/solver/09-appendix.md
  docs/user-guide/solver/10-command-line.md
  mkdocs.yml
Labels: size/L, doc

#2753 [behave] Update solver steps
  src/tests/cucumber/features/steps/common_steps/simulator_utils.py
  src/tests/cucumber/features/steps/common_steps/solver_steps.py
Labels: size/M

#2756 Remove verbose log
  src/solver/utils/ortools_utils.cpp
Labels: size/XS

#2755 Add continuous-delivery for windows & simplify it
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M

#2757 Fix dependency issue for clients
  src/io/inputs/model-converter/CMakeLists.txt
  src/io/inputs/yml-model/CMakeLists.txt
  src/io/inputs/yml-system/CMakeLists.txt
  src/modeler/loadFiles/CMakeLists.txt
  src/packaging/Config.cmake.in
Labels: size/S

#2758 Fix Oracle continuous-delivery
  .github/workflows/oracle8.yml
Labels: size/XS

#2752 Fix/connections tests 6 x
  src/expressions/CMakeLists.txt
  src/expressions/include/antares/expressions/NodeRegistry.h
  src/expressions/include/antares/expressions/expression.h
  src/expressions/include/antares/expressions/visitors/NodeVisitor.h
  src/expressions/include/antares/expressions/visitors/TimeIndexVisitor.h
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/modeler/main.cpp
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/VariableDictionary.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/VariableDictionary.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/tests/cucumber/features/modeler-features/epic2/test_launcher_6.feature
  src/tests/resources/modeler/6_1/input/model-libraries/lib_example_6_1.yml
  src/tests/resources/modeler/6_1/input/system.yml
  src/tests/resources/modeler/6_1/parameters.yml
  src/tests/resources/modeler/6_2/input/data-series/gen1_prop_cost_6_2.tsv
  src/tests/resources/modeler/6_2/input/data-series/gen2_max_p_6_2.tsv
  src/tests/resources/modeler/6_2/input/data-series/gen_1_fixed_cost_6_2.tsv
  src/tests/resources/modeler/6_2/input/model-libraries/lib_example_6_2.yml
  src/tests/resources/modeler/6_2/input/system.yml
  src/tests/resources/modeler/6_2/parameters.yml
  src/tests/resources/modeler/6_3/input/data-series/gen_1_fixed_cost_6_3.tsv
  src/tests/resources/modeler/6_3/input/data-series/gen_2_fixed_cost_6_3.tsv
  src/tests/resources/modeler/6_3/input/model-libraries/lib_example_6_3.yml
  src/tests/resources/modeler/6_3/input/system.yml
  src/tests/resources/modeler/6_3/parameters.yml
  src/tests/src/expressions/CMakeLists.txt
  src/tests/src/expressions/test_TimeIndexVisitor.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/XL

#2760 Don't write modeler files if there's no solutions
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/XS

#2765 New cmd line options for solver
  docs/user-guide/solver/04-parameters.md
  docs/user-guide/solver/10-command-line.md
  src/api/API.cpp
  src/libs/antares/InfoCollection/StudyInfoCollector.cpp
  src/libs/antares/checks/CMakeLists.txt
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/checks/checksOnLPsolver.cpp
  src/libs/antares/checks/include/antares/checks/checkLoadedInputData.h
  src/libs/antares/checks/include/antares/checks/checksOnLPsolver.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/include/antares/exception/LoadingError.hpp
  src/libs/antares/optimization-options/include/antares/optimization-options/options.h
  src/libs/antares/optimization-options/options.cpp
  src/libs/antares/study/include/antares/study/load-options.h
  src/libs/antares/study/parameters.cpp
  src/optimisation/linear-problem-mpsolver-impl/CMakeLists.txt
  src/solver/application/application.cpp
  src/solver/application/include/antares/application/application.h
  src/solver/misc/include/antares/solver/misc/options.h
  src/solver/misc/options.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.cpp
  src/solver/optimisation/adequacy_patch_csr/solve_problem.h
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_appel_solveur_quadratique.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_fonctions.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_appel_solveur_quadratique.cpp
  src/solver/optimisation/opt_optimisation_hebdo.cpp
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/optimisation/opt_pilotage_optimisation_quadratique.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-eco-adq.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/utils/include/antares/solver/utils/ortools_quadratic_wrapper.h
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/solver/utils/include/antares/solver/utils/ortools_wrapper.h
  src/solver/utils/ortools_quadratic_wrapper.cpp
  src/solver/utils/ortools_utils.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/libs/antares/optimization-options/CMakeLists.txt
  src/tests/libs/antares/optimization-options/test_optimization_options.cpp
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
  src/tests/src/solver/utils/test_ortools_quadratic_wrapper.cpp
  src/tools/batchrun/main.cpp
  src/ui/simulator/windows/simulation/run.cpp
Labels: size/XL

#2768 Removing time index constructor
  src/expressions/include/antares/expressions/visitors/TimeIndexVisitor.h
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/tests/src/expressions/test_TimeIndexVisitor.cpp
Labels: size/M

#2766 Fix double free and leak
  src/solver/hydro/daily2/h2o2_j_instanciation.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/include/antares/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/management/monthly.cpp
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.cpp
Labels: size/S

#2769 Use ubuntu 22.04 for CI 8.8
  .github/workflows/build-userguide.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
Labels: ci, 8.8

#2771 Check constraints width if the sizes are only ones
  src/libs/antares/utils/utils.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
Labels: size/S

#2761 [ANT-2997] use official actions
  .github/workflows/sonarcloud.yml
Labels: size/S

#2774 Remove some warnings
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/solver/optimisation/include/antares/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
  src/study/system-model/component.cpp
  src/study/system-model/connection.cpp
Labels: size/XS

#2776 [ANT-3122] Part 1/2 : Set primal tolerance to 1e-6 in ortools_utils
  src/solver/utils/ortools_utils.cpp
Labels: size/XS

#2767 Fix double free and leak
  src/solver/hydro/daily2/h2o2_j_instanciation.cpp
  src/solver/hydro/daily2/h2o2_j_resoudre_le_probleme_lineaire.cpp
  src/solver/hydro/include/antares/solver/hydro/daily2/h2o2_j_donnees_optimisation.h
  src/solver/hydro/monthly/h2o_m_resoudre_le_probleme_lineaire.cpp
Labels: size/S

#2764 Correct turbine max formula 8.8 [ANT-3095]
  src/solver/hydro/management/monthly.cpp
Labels: size/S, 8.8

#2759 Mauvaise valeur turbine max mensuelle [ANT-3095]
  simtest.json
  src/libs/antares/study/area/scratchpad.cpp
  src/solver/hydro/include/antares/solver/hydro/management/management.h
  src/solver/hydro/management/management.cpp
  src/solver/hydro/management/monthly.cpp
Labels: size/M

#2782 export ortools bin directory to env var
  .github/workflows/windows-vcpkg.yml
Labels: size/XS

#2781 Rename lp-solver -> linear-solver, move some options in the "Optimization" section in the help page
  docs/user-guide/solver/04-parameters.md
  docs/user-guide/solver/10-command-line.md
  src/solver/misc/options.cpp
  src/tools/batchrun/main.cpp
Labels: size/L

#2783 Try fixing unfeasible tests for 8.8
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
Labels: size/XS, 8.8

#2784 Add missing changes on 8.8.15
  docs/CHANGELOG.md
  src/CMakeLists.txt
  src/libs/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/binding_constraint/BindingConstraintGroupRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp
  src/libs/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/libs/antares/study/ui-runtimeinfos.h
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
  src/ui/simulator/toolbox/components/map/manager.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/windows/inspector/data.h
  src/ui/simulator/windows/inspector/inspector.cpp
  src/ui/simulator/windows/inspector/inspector.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: size/L

#2780 Bump OR-Tools to v9.12
  .github/workflows/windows-vcpkg.yml
  ortools_tag
  src/solver/utils/ortools_utils.cpp
  src/tests/src/solver/utils/test_ortools_utils.cpp
Labels: size/S

#2787 [ANT-2901] 3.5 - Hybrid area connections from yaml
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/io/inputs/model-converter/modelConverter.cpp
  src/io/inputs/yml-model/decoders.hxx
  src/io/inputs/yml-model/include/antares/io/inputs/yml-model/Library.h
  src/io/inputs/yml-system/converter.cpp
  src/io/inputs/yml-system/decoders.hxx
  src/io/inputs/yml-system/include/antares/io/inputs/yml-system/system.h
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/study/system-model/component.cpp
  src/study/system-model/connection.cpp
  src/study/system-model/include/antares/study/system-model/component.h
  src/study/system-model/include/antares/study/system-model/connection.h
  src/study/system-model/include/antares/study/system-model/portType.h
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/io/yml-importers/test-system-with-connexions.cpp
  src/tests/src/io/yml-importers/testSystemConverter.cpp
  src/tests/src/io/yml-importers/test_full.cpp
  src/tests/src/solver/optim-model-filler/test_readLinExprVisitor_sum_connections.cpp
  src/tests/src/study/system-model/CMakeLists.txt
  src/tests/src/study/system-model/test_component.cpp
  src/tests/src/study/system-model/test_library.cpp
Labels: size/L

#2788 Fix windows CI
  src/study/system-model/include/antares/study/system-model/component.h
  src/study/system-model/include/antares/study/system-model/portType.h
Labels: size/XS
