Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-10, with the labels that each got.

#3116 v9.3.1
  docs/developer-guide/CHANGELOG.md
  sonar-project.properties
  src/CMakeLists.txt
  src/vcpkg.json
Labels: size/L

#3115 Remove unused "Hashable" class
  src/expressions/CMakeLists.txt
  src/expressions/hashable.cpp
  src/expressions/include/antares/expressions/hashable.h
  src/expressions/include/antares/expressions/nodes/PortFieldNode.h
  src/expressions/include/antares/expressions/nodes/PortFieldSumNode.h
  src/expressions/nodes/PortFieldNode.cpp
  src/expressions/nodes/PortFieldSumNode.cpp
Labels: size/L, cleaning

#3118 Fix tests
  src/io/outputs/SimulationTableGenerator.cpp
  src/modeler-optimisation-container/OptimEntityContainer.cpp
  src/modeler-optimisation-container/include/antares/modeler-optimisation-container/OptimEntityContainer.h
  src/modeler/modeler/Modeler.cpp
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/linearProblem.cpp
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/LinearExpression.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
  src/solver/optimisation/ComponentToAreaConnectionFiller.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/tests/src/expressions/CMakeLists.txt
  src/tests/src/expressions/UtilMocks.h
  src/tests/src/expressions/test_DeepWideTrees.cpp
  src/tests/src/io/outputs/testSimulationTable.cpp
  src/tests/src/io/yml-importers/testModelConverter.cpp
  src/tests/src/io/yml-importers/test_full.cpp
  src/tests/src/modeler/mockModelerObjects.cpp
  src/tests/src/modeler/mockModelerObjects.h
  src/tests/src/optimisation/linear-problem/mock-fillers/FillerContext.h
  src/tests/src/optimisation/linear-problem/mock-fillers/OneConstraintFiller.h
  src/tests/src/optimisation/linear-problem/mock-fillers/OneVarFiller.h
  src/tests/src/optimisation/linear-problem/mock-fillers/TwoVarsTwoConstraintsFiller.h
  src/tests/src/optimisation/linear-problem/testLinearProblemBuilder.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearConstraintVisitor.cpp
  src/tests/src/solver/optimisation/test_componentToAreaConnectionFiller.cpp
  src/tests/src/study/system-model/test_component.cpp
Labels: size/XXL

#3121 Tests reintegration
  src/tests/src/expressions/UtilMocks.h
  src/tests/src/expressions/test_DeepWideTrees.cpp
  src/tests/src/expressions/test_PrintAndEvalVisitors.cpp
  src/tests/src/modeler/mockModelerObjects.cpp
  src/tests/src/modeler/mockModelerObjects.h
  src/tests/src/solver/optimisation/test_componentToAreaConnectionFiller.cpp
Labels: size/XL

#3123 Fix a few code smells following #3093
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/io/outputs/SimulationTableGenerator.cpp
  src/modeler-optimisation-container/OptimEntityContainer.cpp
  src/modeler/modeler/Modeler.cpp
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/tests/inmemory-modeler/inmemory-modeler.cpp
Labels: size/M

#3125 Remove `protected` keyword, use constructor/getter instead
  src/libs/antares/writer/immediate_file_writer.cpp
  src/libs/antares/writer/in_memory_writer.cpp
  src/libs/antares/writer/include/antares/writer/i_writer.h
  src/libs/antares/writer/private/immediate_file_writer.h
  src/libs/antares/writer/zip_writer.cpp
  src/tests/src/solver/infeasible-problem-analysis/test-unfeasible-problem-analyzer.cpp
Labels: size/M

#3126 Add modeler test 10_4 for comparison operator
  src/tests/cucumber/features/modeler-features/test_launcher_10.feature
  src/tests/resources/modeler/10_4/case_description.txt
  src/tests/resources/modeler/10_4/input/data-series/load_ts.tsv
  src/tests/resources/modeler/10_4/input/model-libraries/library-eo.yml
  src/tests/resources/modeler/10_4/input/system.yml
  src/tests/resources/modeler/10_4/parameters.yml
Labels: size/L
