Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-08, with the labels that each got.

#2935 Remove a few unused headers
  src/expressions/include/antares/expressions/iterators/pre-order.h
  src/expressions/include/antares/expressions/nodes/SumNode.h
  src/expressions/include/antares/expressions/visitors/EvaluationContext.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/additionalConstraints.h
  src/libs/antares/study/include/antares/study/parts/thermal/ecoInput.h
  src/libs/antares/study/include/antares/study/scenario-builder/applyToMatrix.hxx
  src/solver/hydro/daily/h2o_j_instanciation.cpp
  src/solver/hydro/include/antares/solver/hydro/daily/h2o_j_donnees_optimisation.h
  src/solver/hydro/include/antares/solver/hydro/daily/h2o_j_fonctions.h
  src/solver/hydro/include/antares/solver/hydro/monthly/h2o_m_donnees_optimisation.h
  src/solver/infeasible-problem-analysis/include/antares/solver/infeasible-problem-analysis/unfeasibility-analysis.h
  src/solver/lps/include/antares/solver/lps/LpsFromAntares.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/TimeDependentLinearExpression.h
  src/solver/optimisation/include/antares/solver/optimisation/constraints/constraint_builder_utils.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/BindingConstraintsTimeSeriesNumbersWriter.h
  src/solver/simulation/include/antares/solver/simulation/timeseries-numbers.h
  src/solver/ts-generator/include/antares/solver/ts-generator/prepro.h
  src/solver/variable/include/antares/solver/variable/commons/links/links.h
  src/solver/variable/include/antares/solver/variable/container.hxx
  src/tests/src/libs/antares/array/tests-matrix-load.h
  src/tests/src/libs/antares/array/tests-matrix-save.h
Labels: size/M, cleaning

#2930 Generate & upload HTML report for unit tests
  .github/workflows/ubuntu.yml
  src/tests/format_xml_report.xsl
  src/tests/macros.cmake
  src/tests/merge_all.sh
Labels: size/M, tests, ci

#2932 Add optional overflow variable for short-term storage [ANT-3637]
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/constraints/ShortTermStorageLevel.cpp
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_rename_problem.h
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_rename_problem.cpp
  src/solver/optimisation/variables/VariableManagement.cpp
  src/solver/optimisation/variables/VariableManagement.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/inmemory-study/include/in-memory-study.h
Labels: size/L, 9.3

#2922 Hydro remix algo : simplification
  src/packaging/CMakeLists.txt
  src/solver/simulation/CMakeLists.txt
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/hydro-for-remix.cpp
  src/solver/simulation/include/antares/solver/simulation/hydro-for-remix.h
  src/solver/simulation/include/antares/solver/simulation/remix-utils.h
  src/solver/simulation/include/antares/solver/simulation/shave-peaks-by-remix-hydro.h
  src/solver/simulation/include/antares/solver/simulation/shave-peaks-by-remix-storage-gen.h
  src/solver/simulation/include/antares/solver/simulation/storage-for-remix.h
  src/solver/simulation/shave-peaks-by-remix-hydro.cpp
  src/solver/simulation/shave-peaks-by-remix-storage-gen.cpp
  src/tests/src/solver/simulation/CMakeLists.txt
  src/tests/src/solver/simulation/test-hydro-remix.cpp
Labels: size/XXL

#2951 Update sonar scanner
  .github/workflows/sonarcloud.yml
Labels: size/XS

#2957 9.2 Fix segfault when exporting binding constraints
  src/solver/variable/include/antares/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
Labels: size/XS

#2955 8.8 Fix segfault when exporting binding constraints
  simtest.json
  src/solver/variable/economy/bindingConstraints/bindingConstraintsMarginalCost.h
Labels: size/XS

#2958 Release/9.2.x rc1
  docs/developer-guide/CHANGELOG.md
  sonar-project.properties
  src/CMakeLists.txt
  src/vcpkg.json
Labels: size/L

#2943 Fix final level computation in monthly hydro heuristic
  src/solver/hydro/management/monthly.cpp
Labels: size/XS

#2961 Changelog for branch 9.2.x
  docs/developer-guide/CHANGELOG.md
Labels: size/S, doc

#2963 Revert "Add optional overflow variable for short-term storage"
  src/libs/antares/study/include/antares/study/parts/short-term-storage/properties.h
  src/libs/antares/study/parts/short-term-storage/properties.cpp
  src/solver/optimisation/constraints/ConstraintBuilder.cpp
  src/solver/optimisation/constraints/ShortTermStorageLevel.cpp
  src/solver/optimisation/include/antares/solver/optimisation/constraints/ConstraintBuilder.h
  src/solver/optimisation/include/antares/solver/optimisation/opt_rename_problem.h
  src/solver/optimisation/opt_construction_variables_optimisees_lineaire.cpp
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/opt_rename_problem.cpp
  src/solver/optimisation/variables/VariableManagement.cpp
  src/solver/optimisation/variables/VariableManagement.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/end-to-end/simple_study/simple-study.cpp
  src/tests/inmemory-study/in-memory-study.cpp
  src/tests/inmemory-study/include/in-memory-study.h
Labels: size/L

#2965 Changelog 9.3
  docs/developer-guide/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/S

#2934 Forbid study path with non ascii chars
  src/api/solver.cpp
  src/libs/antares/checks/checkLoadedInputData.cpp
  src/libs/antares/checks/include/antares/checks/checkLoadedInputData.h
  src/libs/antares/exception/LoadingError.cpp
  src/libs/antares/exception/include/antares/exception/LoadingError.hpp
  src/libs/antares/study/load.cpp
  src/libs/antares/utils/include/antares/utils/utils.h
  src/libs/antares/utils/utils.cpp
  src/solver/application/application.cpp
  src/solver/misc/include/antares/solver/misc/options.h
  src/solver/misc/options.cpp
  src/tests/src/libs/antares/CMakeLists.txt
  src/tests/src/libs/antares/checks/CMakeLists.txt
  src/tests/src/libs/antares/checks/tests-checks.cpp
  src/tests/src/libs/antares/test_utils.cpp
  src/tests/src/solver/CMakeLists.txt
  src/tests/src/solver/misc/CMakeLists.txt
  src/tests/src/solver/misc/tests-options.cpp
  src/tests/src/solver/simulation/tests-ts-numbers.cpp
  src/tests/src/utils/unit_test_utils.cpp
  src/tests/src/utils/unit_test_utils.h
  src/ui/simulator/application/main/drag-drop.hxx
  src/ui/simulator/application/study.cpp
  src/ui/simulator/cmake/application.cmake
  src/ui/simulator/windows/saveas.cpp
Labels: bug, size/XL

#2972 Modeler - fix various problems with time & scenarios [ANT-3712]
  src/expressions/include/antares/expressions/RotateIndex.h
  src/expressions/visitors/EvalVisitor.cpp
  src/expressions/visitors/LinearityVisitor.cpp
  src/expressions/visitors/PrintVisitor.cpp
  src/expressions/visitors/TimeIndexVisitor.cpp
  src/libs/antares/study/include/antares/study/study.h
  src/modeler/modeler/Modeler.cpp
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/ILinearProblemData.h
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/solver/optim-model-filler/TimeDependentLinearExpression.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/TimeDependentLinearExpression.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/sim_calcul_economique.cpp
  src/tests/inmemory-modeler/inmemory-modeler.cpp
  src/tests/src/expressions/test_DeepWideTrees.cpp
  src/tests/src/expressions/test_PrintAndEvalNodes.cpp
  src/tests/src/io/yml-importers/testConvertorVisitor.cpp
  src/tests/src/optimisation/linear-problem/mock-fillers/FillerContext.h
  src/tests/src/optimisation/linear-problem/testLinearProblemBuilder.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
  src/tests/src/solver/optim-model-filler/test_linearExpression.cpp
  src/tests/src/solver/optim-model-filler/test_readLinExprVisitor_sum_connections.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearConstraintVisitor.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearExpressionVisitor.cpp
  src/tests/src/solver/optimisation/test_componentToAreaConnectionFiller.cpp
Labels: bug, size/L

#2976 Load only needed solvers [ANT-3543]
  src/libs/antares/checks/checksOnLPsolver.cpp
  src/solver/misc/options.cpp
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/solver/utils/ortools_utils.cpp
Labels: size/M

#2959 Hydro remix : more simplifications
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/hydro-for-remix.cpp
  src/solver/simulation/include/antares/solver/simulation/hydro-for-remix.h
  src/solver/simulation/include/antares/solver/simulation/remix-utils.h
  src/solver/simulation/include/antares/solver/simulation/shave-peaks-by-remix-storage-gen.h
  src/solver/simulation/include/antares/solver/simulation/storage-for-remix.h
  src/solver/simulation/shave-peaks-by-remix-storage-gen.cpp
  src/tests/src/solver/simulation/test-hydro-remix.cpp
Labels: size/L

#2978 [Doc] Fix starting index for year and time-series
  docs/user-guide/modeler/02-inputs.md
Labels: size/L, doc

#2984 Remove dependency on chocolatey / fossies.org
  .github/workflows/download-extract-precompiled-libraries-tgz/action.yml
  .github/workflows/download-extract-precompiled-libraries-zip/action.yml
  .github/workflows/install-cmake-328/action.yml
  .github/workflows/run-tests/action.yml
  .github/workflows/windows-vcpkg.yml
Labels: size/M, cleaning, ci

#2991 Short term storage : simplify results data structure
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/variable/include/antares/solver/variable/economy/STSbyGroup.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageCashFlowByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageInjectionByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageLevelsByCluster.h
  src/solver/variable/include/antares/solver/variable/economy/STStorageWithdrawalByCluster.h
Labels: size/M

#2997 Refactor unique ID check
  src/study/system-model/include/antares/study/system-model/model.h
  src/study/system-model/model.cpp
  src/tests/src/study/system-model/test_library.cpp
Labels: size/L

#2996 Simplify logging handling in node visitor
  src/expressions/include/antares/expressions/visitors/EvalVisitor.h
  src/expressions/include/antares/expressions/visitors/NodeVisitor.h
  src/expressions/visitors/NodeVisitor.cpp
Labels: size/M

#2964 [ANT-3617] modeler 5.1 column base storage
  src/io/outputs/CMakeLists.txt
  src/io/outputs/SimulationTableCsv.cpp
  src/io/outputs/include/antares/io/outputs/SimulationTableCsv.h
  src/io/outputs/include/antares/io/outputs/columns.h
  src/io/outputs/include/antares/io/outputs/storage.h
  src/solver/optimisation/OptimisationsSimulationTable.cpp
  src/solver/optimisation/include/antares/solver/optimisation/OptimisationsSimulationTable.h
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/adequacy.h
  src/solver/simulation/include/antares/solver/simulation/economy.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/tests/src/io/outputs/testSimulationTable.cpp
Labels: size/L

#2999 Add cucumber test step for simulation table
  src/io/outputs/SimulationTableCsvFile.cpp
  src/io/outputs/SimulationTableGenerator.cpp
  src/tests/cucumber/features/modeler-features/test_launcher_1.feature
  src/tests/cucumber/features/modeler-features/test_launcher_2.feature
  src/tests/cucumber/features/modeler-features/test_launcher_3.feature
  src/tests/cucumber/features/modeler-features/test_launcher_4.feature
  src/tests/cucumber/features/modeler-features/test_launcher_5.feature
  src/tests/cucumber/features/modeler-features/test_launcher_6.feature
  src/tests/cucumber/features/modeler-features/us2.5.feature
  src/tests/cucumber/features/solver-features/hybrid_studies.feature
  src/tests/cucumber/features/steps/common_steps/modeler_output_handler.py
  src/tests/cucumber/features/steps/common_steps/modeler_steps.py
  src/tests/cucumber/features/steps/common_steps/solver_steps.py
Labels: size/L

#3006 Fix array default initialization
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/solver/optimisation/constraints/Group1.cpp
Labels: size/XS

#3003 Reduce code duplication & complexity in Simulation Table generation
  src/io/outputs/SimulationTableGenerator.cpp
  src/io/outputs/include/antares/io/outputs/SimulationTableGenerator.h
  src/modeler/FileWriter.cpp
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/tests/src/io/outputs/testSimulationTable.cpp
Labels: size/XL

#3009 Clean some warnings
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/study.cpp
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearConstraintVisitor.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearExpressionVisitor.h
Labels: size/S
