Repository AntaresSimulatorTeam/Antares_Simulator, pull requests merged in 2025-03, with the labels that each got.

#2599 Fix accurate remix hydro [ANT-1825]
  docs/developer-guide/CHANGELOG.md
  docs/user-guide/04-migration-guides.md
  src/libs/antares/study/include/antares/study/parts/hydro/container.h
  src/libs/antares/study/parts/hydro/container.cpp
  src/solver/hydro/daily/h2o_j_initialiser_les_bornes_des_variables.cpp
  src/solver/hydro/management/daily.cpp
  src/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.cpp
  src/solver/optimisation/include/antares/solver/optimisation/post_process_commands.h
  src/solver/optimisation/opt_decompte_variables_et_contraintes.cpp
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
  src/solver/optimisation/opt_gestion_des_couts_cas_lineaire.cpp
  src/solver/optimisation/optim_post_process_list.cpp
  src/solver/optimisation/post_process_commands.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/common-hydro-levels.cpp
  src/solver/simulation/common-hydro-remix.cpp
  src/solver/simulation/include/antares/solver/simulation/common-eco-adq.h
  src/solver/simulation/include/antares/solver/simulation/shave-peaks-by-remix-hydro.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/shave-peaks-by-remix-hydro.cpp
  src/solver/simulation/sim_alloc_probleme_hebdo.cpp
  src/solver/simulation/sim_calcul_economique.cpp
  src/solver/variable/include/antares/solver/variable/economy/reservoirlevel.h
  src/tests/src/libs/antares/study/parameters/parameters-tests.cpp
  src/tests/src/libs/antares/study/parts/hydro/CMakeLists.txt
  src/tests/src/libs/antares/study/parts/hydro/test-hydro-common.cpp
  src/tests/src/solver/simulation/test-hydro-remix.cpp
Labels: size/XL

#2648 Improve logging & loading of STS elements introduced in v9.2.0 [ANT-2730]
  src/libs/antares/study/area/list.cpp
  src/libs/antares/study/include/antares/study/parts/short-term-storage/cluster.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/container.h
  src/libs/antares/study/include/antares/study/parts/short-term-storage/series.h
  src/libs/antares/study/parts/short-term-storage/cluster.cpp
  src/libs/antares/study/parts/short-term-storage/container.cpp
  src/libs/antares/study/parts/short-term-storage/series.cpp
  src/tests/src/libs/antares/study/short-term-storage-input/short-term-storage-input-output.cpp
Labels: size/L, 9.2

#2674 [ANT-2890] Check scenario year for Binding constraints
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
Labels: bug, size/XS

#2675 [ANT-2890] Check scenario year for Binding constraints 8.8
  src/libs/antares/study/scenario-builder/BindingConstraintsTSNumbersData.cpp
Labels: bug, size/XS, 8.8

#2676 Small doc fix
  docs/user-guide/04-migration-guides.md
Labels: size/XS, doc

#2679 Fix broken link in doc
  docs/user-guide/modeler/01-overview-modeler.md
  mkdocs.yml
Labels: size/XS

#2681 Improve unit tests for cost computation (non-constant modulation) [ANT-2527]
  src/tests/src/libs/antares/study/thermal-price-definition/thermal-price-definition.cpp
Labels: size/S

#2677 Add tests for TSData getters & setters
  src/libs/antares/study/include/antares/study/scenario-builder/NTCTSNumberData.h
  src/libs/antares/study/scenario-builder/NTCTSNumberData.cpp
  src/libs/antares/study/scenario-builder/rules.cpp
  src/tests/src/libs/antares/study/scenario-builder/CMakeLists.txt
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-file-save.cpp
  src/tests/src/libs/antares/study/scenario-builder/test-sc-builder-get-set.cpp
  src/ui/simulator/toolbox/components/datagrid/renderer/scenario-builder-ntc-renderer.cpp
Labels: size/L

#2610 Use ubuntu 22.04, update OR-Tools
  .github/workflows/build-userguide.yml
  .github/workflows/new_release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows-vcpkg.yml
  ortools_tag
Labels: size/S

#2670 Feature/visitor use variable dict 2
  src/solver/optim-model-filler/CMakeLists.txt
  src/solver/optim-model-filler/ComponentFiller.cpp
  src/solver/optim-model-filler/FullKey.cpp
  src/solver/optim-model-filler/LinearExpression.cpp
  src/solver/optim-model-filler/PartialKey.cpp
  src/solver/optim-model-filler/ReadLinearConstraintVisitor.cpp
  src/solver/optim-model-filler/ReadLinearExpressionVisitor.cpp
  src/solver/optim-model-filler/TimeDependentLinearExpression.cpp
  src/solver/optim-model-filler/VariableDictionary.cpp
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ComponentFiller.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/FullKey.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/PartialKey.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearConstraintVisitor.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/ReadLinearExpressionVisitor.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/TimeDependentLinearExpression.h
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/VariableDictionary.h
  src/tests/src/solver/optim-model-filler/test_linearExpression.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearConstraintVisitor.cpp
  src/tests/src/solver/optim-model-filler/test_readLinearExpressionVisitor.cpp
Labels: size/XL

#2686 Modeler doc small correction
  docs/user-guide/modeler/02-inputs.md
Labels: size/XS

#2688 Create a permanent release from develop
  .github/workflows/centos7.yml
  .github/workflows/oracle8.yml
  .github/workflows/ubuntu.yml
Labels: size/M

#2669 Improve modeler API & main class
  src/CMakeLists.txt
  src/format-code.sh
  src/io/inputs/data-series-csv-importer/CMakeLists.txt
  src/modeler/CMakeLists.txt
  src/modeler/loadFiles/CMakeLists.txt
  src/modeler/loadFiles/handleErrors.cpp
  src/modeler/loadFiles/include/antares/solver/modeler/loadFiles/loadFiles.h
  src/modeler/loadFiles/readDataSeries.cpp
  src/modeler/loadFiles/readLibraries.cpp
  src/modeler/loadFiles/readParameters.cpp
  src/modeler/loadFiles/readSystem.cpp
  src/modeler/main.cpp
  src/modeler/parameters/CMakeLists.txt
  src/modeler/parameters/encoder.hxx
  src/modeler/parameters/include/antares/solver/modeler/parameters/modelerParameters.h
  src/modeler/parameters/include/antares/solver/modeler/parameters/parseModelerParameters.h
  src/modeler/parameters/parseModelerParameters.cpp
  src/optimisation/linear-problem-data-impl/CMakeLists.txt
  src/optimisation/linear-problem-data-impl/include/antares/optimisation/linear-problem-data-impl/linearProblemData.h
  src/solver/CMakeLists.txt
  src/solver/optimisation/CMakeLists.txt
  src/tests/resources/modeler/epic2/us2.5/study_2.5.4/output/problem.lp
  src/tests/src/modeler/loadFiles/CMakeLists.txt
  src/tests/src/optimisation/linear-problem/CMakeLists.txt
  src/tests/src/solver/optim-model-filler/CMakeLists.txt
Labels: size/L

#2694 Remove dynamic allocations, use local variables instead
  src/solver/variable/include/antares/solver/variable/economy/balance.h
Labels: size/M

#2691 Changelog 9.2
  docs/developer-guide/CHANGELOG.md
  src/CMakeLists.txt
Labels: size/L, 9.2

#2695 Doc: correct python command to install dependencies
  docs/developer-guide/1-Development-requirements.md
Labels: doc

#2662 Modeler 4.7: Import connections and ports
  src/expressions/CMakeLists.txt
  src/io/inputs/model-converter/CMakeLists.txt
  src/io/inputs/model-converter/convertorVisitor.cpp
  src/io/inputs/model-converter/include/antares/io/inputs/model-converter/modelConverter.h
  src/io/inputs/model-converter/modelConverter.cpp
  src/io/inputs/yml-model/decoders.hxx
  src/io/inputs/yml-model/include/antares/io/inputs/yml-model/Library.h
  src/study/system-model/include/antares/study/system-model/model.h
  src/study/system-model/include/antares/study/system-model/port.h
  src/study/system-model/include/antares/study/system-model/portFieldDefinition.h
  src/study/system-model/include/antares/study/system-model/portType.h
  src/study/system-model/model.cpp
  src/tests/src/io/yml-importers/testConvertorVisitor.cpp
  src/tests/src/io/yml-importers/testModelTranslator.cpp
  src/tests/src/io/yml-importers/testSystemConverter.cpp
  src/tests/src/io/yml-importers/testYmlModel.cpp
  src/tests/src/io/yml-importers/test_full.cpp
Labels: size/XL, Modeleur

#2683 Pass strings by const reference when reading scenariobuilder.dat
  src/libs/antares/study/include/antares/study/scenario-builder/rules.h
  src/libs/antares/study/scenario-builder/rules.cpp
Labels: size/M, code quality

#2693 Enable extra linear solvers: PDLP & HiGHS
  docs/developer-guide/CHANGELOG.md
  docs/user-guide/modeler/04-parameters.md
  docs/user-guide/solver/09-command-line.md
  ortools_tag
  src/modeler/main.cpp
  src/solver/utils/include/antares/solver/utils/ortools_utils.h
  src/solver/utils/ortools_utils.cpp
  src/tests/resources/modeler/1_4/parameters.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.2/parameters.yml
  src/tests/resources/modeler/epic2/us2.5/study_2.5.3/parameters.yml
  src/tests/src/solver/utils/CMakeLists.txt
  src/tests/src/solver/utils/test_main.cpp
  src/tests/src/solver/utils/test_ortools_utils.cpp
Labels: size/L

#2696 Fix non-passing tests
  .github/workflows/ubuntu.yml
  simtest.json
  src/tests/run-study-tests/test_unfeasible_problem.py
Labels: size/XS

#2702 Fix ortools unit tests
  docs/user-guide/modeler/04-parameters.md
  docs/user-guide/solver/09-command-line.md
  src/CMakeLists.txt
  src/tests/src/api_internal/test_api.cpp
  src/tests/src/solver/utils/test_ortools_utils.cpp
Labels: bug, size/M

#2708 Fix undefined behavior in BCs [ANT-2994]
  src/libs/antares/study/binding_constraint/BindingConstraintGroup.cpp
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraint.h
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraintGroup.h
  src/libs/antares/study/include/antares/study/binding_constraint/BindingConstraintsRepository.h
  src/libs/antares/study/include/antares/study/ui-runtimeinfos.h
  src/ui/simulator/toolbox/components/map/manager.cpp
  src/ui/simulator/toolbox/input/thermal-cluster.cpp
  src/ui/simulator/windows/inspector/data.h
  src/ui/simulator/windows/inspector/inspector.cpp
  src/ui/simulator/windows/inspector/inspector.h
  src/ui/simulator/windows/inspector/property.update.cpp
Labels: bug, size/M

#2710 Fix Sonarcloud jobs failing silently
  .github/workflows/sonarcloud.yml
Labels: size/S

#2711 Add unit tests for BindingConstraintGroup::numberOfTimeseries
  src/tests/src/libs/antares/study/constraint/test_group.cpp
Labels: size/M, tests

#2712 Remove unused Parameters member data
  src/libs/antares/study/include/antares/study/parameters.h
  src/libs/antares/study/parameters.cpp
Labels: size/S, cleaning

#2709 Fix changelog for 9.2.0
  docs/developer-guide/CHANGELOG.md
Labels: size/XS, doc

#2700 Fix memory leak, double free
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/XS, code quality

#2704 Use MPSolver* instead of void*, remove static_casts
  src/solver/optimisation/include/antares/solver/optimisation/opt_structure_probleme_a_resoudre.h
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
  src/solver/optimisation/opt_liberation_problemes_simplexe.cpp
Labels: size/S, code quality

#2689 Doc : updating output changelog
  docs/user-guide/solver/03-outputs.md
Labels: size/S

#2715 Try latest SimTest tag
  simtest.json
Labels: size/XS

#2722 Don't rebuild optimization problem at every simplex resolution
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/S

#2723 Small refactor around `PROBLEME_SIMPLEXE_NOMME -> MPSolver` conversion
  src/solver/optimisation/opt_appel_solveur_lineaire.cpp
Labels: size/M

#2725 Use `std::call_once` to avoid race conditions in `ThermalCluster::getCostProvider`
  src/libs/antares/study/include/antares/study/parts/thermal/cluster.h
  src/libs/antares/study/parts/thermal/cluster.cpp
Labels: size/M

#2727 Use std::identity from header <functional>
  src/solver/optim-model-filler/include/antares/solver/optim-model-filler/LinearExpression.h
Labels: size/S

#2726 Use std::call_once for the export of area-1-1.txt & interco-1-1.txt
  src/solver/optimisation/opt_optimisation_lineaire.cpp
  src/solver/simulation/adequacy.cpp
  src/solver/simulation/economy.cpp
  src/solver/simulation/include/antares/solver/simulation/adequacy.h
  src/solver/simulation/include/antares/solver/simulation/economy.h
  src/solver/simulation/include/antares/solver/simulation/sim_structure_probleme_economique.h
  src/solver/simulation/include/antares/solver/simulation/solver.h
  src/solver/simulation/include/antares/solver/simulation/solver.hxx
  src/solver/simulation/sim_calcul_economique.cpp
Labels: size/M

#2729 Use indices for getVariable & getConstraint, don't reconstruct name
  src/optimisation/linear-problem-api/include/antares/optimisation/linear-problem-api/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/include/antares/optimisation/linear-problem-mpsolver-impl/linearProblem.h
  src/optimisation/linear-problem-mpsolver-impl/linearProblem.cpp
  src/solver/optimisation/LegacyFiller.cpp
  src/tests/src/optimisation/linear-problem/mock-fillers/OneVarFiller.h
  src/tests/src/optimisation/linear-problem/testLinearProblemBuilder.cpp
  src/tests/src/optimisation/linear-problem/testLinearProblemMpsolverImpl.cpp
  src/tests/src/solver/optim-model-filler/test_componentFiller.cpp
Labels: size/L

#2732 Fix unfeasible problems with <0 hydro infows [ANT-3043]
  src/solver/optimisation/opt_gestion_des_bornes_cas_lineaire.cpp
Labels: size/XS

#2737 Fix leak using matrix_to_buffer_dumper_factory::get_dumper
  src/libs/antares/array/include/antares/array/matrix-to-buffer.h
  src/libs/antares/array/include/antares/array/matrix-to-buffer.hxx
  src/libs/antares/array/include/antares/array/matrix.hxx
Labels: size/M
